### ISSUE TITLE
Socks5 proxy authentication

### ISSUE THREAD

**Issue by pisarm** [nodemailer/nodemailer#1014]
Hello,
 I am trying to use nodemailer for sending emails through a SOCKS5 proxy, Dante v1.4.1 https://www.inet.no/dante/ installed on Debian 9. 

I am using a small node test project with only two dependencies. Nodemailer 6.1.1 and socks library 2.3.2. 

```
const nodemailer = require("nodemailer");

let transporter = nodemailer.createTransport({
    host: "smtp.some.dk",
    port: 465,
    secure: true,
    auth: {
        user: "someuser",
        pass: "secret"
    },
    proxy: "socks5://proxyuser:proxypass@1.2.3.4:1080"
});

transporter.set('proxy_socks_module', require('socks'));

const message = {
    from: 'test@some.dk',
    to: 'me@other.dk',
    subject: 'Testing proxy..',
    text: '..and thank you for the fish!'
};

transporter.sendMail(message, (error, info) => {
   console.log("error", error);
   console.log("info", info);
})
```

Using this code I get the following error from the socks library:

```
error { Error: Received invalid Socks5 initial handshake (no accepted authentication type)
    at SocksClientError (/Users/fp/Projects/Spikes/nodemailer_proxy/node_modules/socks/build/common/util.js:8:9)
    at SocksClient._closeSocket (/Users/fp/Projects/Spikes/nodemailer_proxy/node_modules/socks/build/client/socksclient.js:363:32)
    at SocksClient.handleInitialSocks5HandshakeResponse (/Users/fp/Projects/Spikes/nodemailer_proxy/node_modules/socks/build/client/socksclient.js:479:18)
    at SocksClient.processData (/Users/fp/Projects/Spikes/nodemailer_proxy/node_modules/socks/build/client/socksclient.js:296:26)
    at SocksClient.onDataReceived (/Users/fp/Projects/Spikes/nodemailer_proxy/node_modules/socks/build/client/socksclient.js:280:14)
    at Socket._onDataReceived (/Users/fp/Projects/Spikes/nodemailer_proxy/node_modules/socks/build/client/socksclient.js:200:47)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
  options: 
   { proxy: { ipaddress: '1.2.3.4', port: 1080, type: 5 },
     destination: { host: 'smtp.some.dk', port: 465 },
     command: 'connect',
     userId: 'proxyuser',
     password: 'proxypass' } }
```

The problem seems to be that the userId and password properties should be on the proxy object instead of directly on the options object.

If I change just that in index.js, in the mailer folder authentication works.

Original
```
if (proxy.auth) {
    let username = decodeURIComponent(proxy.auth.split(':').shift());
    let password = decodeURIComponent(proxy.auth.split(':').pop());
    if (proxyV2) {
        connectionOpts.userId = username;
        connectionOpts.password = password;
    } else if (proxyType === 4) {
        connectionOpts.userid = username;
    } else {
        connectionOpts.authentication = {
            username,
            password
        };
    }
}
```

Changed
```
if (proxy.auth) {
    let username = decodeURIComponent(proxy.auth.split(':').shift());
    let password = decodeURIComponent(proxy.auth.split(':').pop());
    if (proxyV2) {
        connectionOpts.proxy.userId = username;
        connectionOpts.proxy.password = password;
    } else if (proxyType === 4) {
        connectionOpts.userid = username;
    } else {
        connectionOpts.authentication = {
            username,
            password
        };
    }
}
```

Please let me know if you need more details or if you would like me to submit a PR with the fix.

Best regards
 Flemming

**Comment by evgeny-s** [comment]
any updates here?

**Comment by pisarm** [comment]
Looking at the master branch this is fixed. So should not be an issue any longer.
