### ISSUE TITLE
Seeing issue with corporate proxy : Greeting not recived

### ISSUE THREAD

**Issue by bsricharan** [nodemailer/nodemailer#1024]
I could not get nodemailer work in corporate proxy . it works absolutely fine without proxy when i am off network . do i need to get a port open from the company based on below data?

using following settings

this.transporter = nodemailer.createTransport({
      logger : true,
      debug: true,
      host: "smtp.googlemail.com",
      secure: true,
      auth: {
        user: "delphixuserhwse@gmail.com",
        pass: "delphix123"
      },
      port: 465,
      proxy: "proxyurl which is correct",
      requireTLS: true,
      tls: {
        rejectUnauthorized: false
      }
    });

error log 
[2019-06-11 16:50:49] DEBUG Sending mail using SMTP/6.2.1[client:6.2.1]
[2019-06-11 16:50:49] INFO  Using proxied socket from 11.0.6.39:8080 to smtp.googlemail.com:465
[2019-06-11 16:50:49] INFO  [R7yJfgNSQk] Secure connection established to 11.0.6.39:8080
[2019-06-11 16:51:19] ERROR [R7yJfgNSQk] Greeting never received
[2019-06-11 16:51:19] DEBUG [R7yJfgNSQk] Closing connection to the server using "end"
[2019-06-11 16:51:19] ERROR Send Error: Greeting never received
{ Error: Greeting never received
    at SMTPConnection._formatError (C:\hwse\hwse-client-db-copy\app-api\node_modules\nodemailer\lib\smtp-connection\index.js:781:19)
    at SMTPConnection._onError (C:\hwse\hwse-client-db-copy\app-api\node_modules\nodemailer\lib\smtp-connection\index.js:767:20)
    at Timeout._greetingTimeout.setTimeout (C:\hwse\hwse-client-db-copy\app-api\node_modules\nodemailer\lib\smtp-connection\index.js:708:22)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) code: 'ETIMEDOUT', command: 'CONN' }
[2019-06-11 16:51:19] INFO  [R7yJfgNSQk] Connection closed

**Comment by HaritDivyesh** [comment]
Hi @bsricharan ,
Were you able to resolve this? I am in exactly the same situation: it works fine on my machine without corporate proxy, but getting _Greeting not received_ error when running from within company network.

**Comment by markb-trustifi** [comment]
> Greeting never received

When you are having this error the email is actually lost? I think, this is some internal error that the user shouldn't care about.
