### ISSUE TITLE
office365  error 502 Command not implemented 

### ISSUE THREAD

**Issue by saostad** [nodemailer/nodemailer#1025]
recently I am getting error message below when I am trying to send an email via Office365 account:

```
Error: Invalid login: 502 Command not implemented
    at SMTPConnection._formatError (C:\Users\SOstad\Projects\ad-companies\node_modules\nodemailer\lib\smtp-connection\index.js:781:19)
    at SMTPConnection._actionAUTHComplete (C:\Users\SOstad\Projects\ad-companies\node_modules\nodemailer\lib\smtp-connection\index.js:1516:34)
    at SMTPConnection.<anonymous> (C:\Users\SOstad\Projects\ad-companies\node_modules\nodemailer\lib\smtp-connection\index.js:554:26)
    at SMTPConnection._processResponse (C:\Users\SOstad\Projects\ad-companies\node_modules\nodemailer\lib\smtp-connection\index.js:940:20)
    at SMTPConnection._onData (C:\Users\SOstad\Projects\ad-companies\node_modules\nodemailer\lib\smtp-connection\index.js:746:14)
    at Socket.SMTPConnection._onSocketData (C:\Users\SOstad\Projects\ad-companies\node_modules\nodemailer\lib\smtp-connection\index.js:189:46)
    at Socket.emit (events.js:200:13)
    at Socket.EventEmitter.emit (domain.js:471:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11) {
  code: 'EAUTH',
  response: '502 Command not implemented',
  responseCode: 502,
  command: 'AUTH PLAIN'
}
```

this is my transporter:
```
const transporter = nodemailer.createTransport({
  host: "smtp.office365.com",
  port: 587,
  auth: {
    user: process.env.EMAIL_USER ? process.env.EMAIL_USER : "",
    pass: process.env.EMAIL_PASS ? process.env.EMAIL_PASS : "",
  },
  secure: false,
  tls: { ciphers: "SSLv3" },
  authMethod: "PLAIN",
});

```

I tried other authMethod options that mentioned in documents but none of them didn't help: 

> options.authMethods optional array of allowed authentication methods, defaults to [‘PLAIN’, ‘LOGIN’]. Only the methods listed in this array are allowed, so if you set it to [‘XOAUTH2’] then PLAIN and LOGIN are not available. Use [‘PLAIN’, ‘LOGIN’, ‘XOAUTH2’] to allow all three. Authentication is only allowed in secure mode (either the server is started with secure:true option or STARTTLS command is used)

**Comment by saostad** [comment]
Problem solved, it was a firewall problem
