### ISSUE TITLE
Can not send a large attachments

### ISSUE THREAD

**Issue by rols2015** [nodemailer/nodemailer#1047]
Hello.
I an trying to send an attachment ~50 Mb and getting the following error:
Did anyone have the same problem with such large attachments?
```javascript
{ Error: Message failed: 550 Error reading data, max message size exceeded
    at SMTPConnection._formatError (/alex/project/node_modules/smtp-connection/lib/smtp-connection.js:466:15)
    at SMTPConnection._actionStream (/alex/project/node_modules/smtp-connection/lib/smtp-connection.js:1051:30)
    at SMTPConnection.<anonymous> (/alex/project/node_modules/smtp-connection/lib/smtp-connection.js:680:14)
    at SMTPConnection._processResponse (/alex/project/node_modules/smtp-connection/lib/smtp-connection.js:604:16)
    at SMTPConnection._onData (/alex/project/node_modules/smtp-connection/lib/smtp-connection.js:431:10)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  code: 'EMESSAGE',
  response: '550 Error reading data, max message size exceeded',
  responseCode: 550 }```

**Comment by EyePulp** [comment]
@rols2015 That response is coming from your destination mail server, not from `nodemailer`.  Wherever you're trying to send to has a limit defined for inbound message sizes.

**Comment by rols2015** [comment]
@EyePulp yes, already confirmed with my devops team. Thank you!
