### ISSUE TITLE
Nodemailer AuthO getting Invalid Request Error at Post request

### ISSUE THREAD

**Issue by jessicadsewell** [nodemailer/nodemailer#1048]
Nodemailer worked for me yesterday, but hours later I get this error back:

[0] { Error: invalid_request
[0]     at postRequest (/Users/jessicasewell/Desktop/code/Projects/Project-3/pupper_2/node_modules/nodemailer/lib/xoauth2/index.js:259:33)
[0]     at PassThrough.req.once (/Users/jessicasewell/Desktop/code/Projects/Project-3/pupper_2/node_modules/nodemailer/lib/xoauth2/index.js:328:20)
[0]     at Object.onceWrapper (events.js:277:13)
[0]     at PassThrough.emit (events.js:189:13)
[0]     at endReadableNT (_stream_readable.js:1125:12)
[0]     at process._tickCallback (internal/process/next_tick.js:63:19) code: 'EAUTH', command: 'AUTH XOAUTH2' }

Can someone tell me where this is pointing to?

**Comment by andris9** [comment]
Your OAuth2 access token expires in an hour and Nodemailer is not able to provision a new one using a valud refresh token

**Comment by jessicadsewell** [comment]
I have the token auto refreshing in the settings of OAuth playground... here is my transporter:

var transport = {
  host: 'smtp.gmail.com',
  port: 465,
  secure: true,
  auth: {
    type: 'OAuth2',
    user: "pupperconnectionapp@gmail.com",
    clientId: process.env.clientId,
    clientSecret: process.env.clientSecret,
    refreshToken: process.env.refreshToken,
    accessToken: process.env.accessToken,
    expires: 3600
  }
}
var transporter = nodemailer.createTransport(transport);

**Comment by jessicadsewell** [comment]
Turns out this was an issue with accessing my .env.
