### ISSUE TITLE
Error: Invalid login: 535 5.7.3 Authentication unsuccessful [SN4PR0601CA0002.namprd06.prod.outlook.com]

### ISSUE THREAD

**Issue by yashdogra31** [nodemailer/nodemailer#1071]
**Hi Team

i am getting the following error while trying to send mail via node cloud application :**

{ Error: Invalid login: 535 5.7.3 Authentication unsuccessful [SN4PR0601CA0002.namprd06.prod.outlook.com]

   2019-10-07T15:49:59.05+0530 [APP/PROC/WEB/0] OUT     at SMTPConnection._formatError (/home/vcap/deps/0/node_modules/nodemailer/lib/smtp-connection/index.js:605:19)

   2019-10-07T15:49:59.05+0530 [APP/PROC/WEB/0] OUT     at SMTPConnection._actionAUTHComplete (/home/vcap/deps/0/node_modules/nodemailer/lib/smtp-connection/index.js:1340:34)

   2019-10-07T15:49:59.05+0530 [APP/PROC/WEB/0] OUT     at SMTPConnection._responseActions.push.str (/home/vcap/deps/0/node_modules/nodemailer/lib/smtp-connection/index.js:1298:18)

   2019-10-07T15:49:59.05+0530 [APP/PROC/WEB/0] OUT     at SMTPConnection._processResponse (/home/vcap/deps/0/node_modules/nodemailer/lib/smtp-connection/index.js:764:20)

   2019-10-07T15:49:59.05+0530 [APP/PROC/WEB/0] OUT     at SMTPConnection._onData (/home/vcap/deps/0/node_modules/nodemailer/lib/smtp-connection/index.js:570:14)

   2019-10-07T15:49:59.05+0530 [APP/PROC/WEB/0] OUT     at TLSSocket._socket.on.chunk (/home/vcap/deps/0/node_modules/nodemailer/lib/smtp-connection/index.js:710:55)

   2019-10-07T15:49:59.05+0530 [APP/PROC/WEB/0] OUT     at emitOne (events.js:96:13)

   2019-10-07T15:49:59.05+0530 [APP/PROC/WEB/0] OUT     at TLSSocket.emit (events.js:188:7)

   2019-10-07T15:49:59.05+0530 [APP/PROC/WEB/0] OUT     at readableAddChunk (_stream_readable.js:176:18)

   2019-10-07T15:49:59.05+0530 [APP/PROC/WEB/0] OUT     at TLSSocket.Readable.push (_stream_readable.js:134:10)

   2019-10-07T15:49:59.05+0530 [APP/PROC/WEB/0] OUT     at TLSWrap.onread (net.js:543:20)

   2019-10-07T15:49:59.05+0530 [APP/PROC/WEB/0] OUT   code: 'EAUTH',

   2019-10-07T15:49:59.05+0530 [APP/PROC/WEB/0] OUT   response: '535 5.7.3 Authentication unsuccessful [SN4PR0601CA0002.namprd06.prod.outlook.com]',

   2019-10-07T15:49:59.05+0530 [APP/PROC/WEB/0] OUT   responseCode: 535,

   2019-10-07T15:49:59.05+0530 [APP/PROC/WEB/0] OUT   command: 'AUTH LOGIN' }

**Here is the code (configuration) i am using to send the mail. Its a node js application and i am using the nodemailer module :**

               var payload   =	{
					auth: {
						user: smtpuser,
						pass: smtppass
					},
					to : toAddr,
					from  : emailfrom,
					cc : ccAddr,
					subject	: subject,
					html    : content,
                                        attachments: attachments
				};

                var transporter = nodemailer.createTransport({
                    host: payload.host || 'smtp.office365.com', // Office 365 server
                    port: payload.port || 587,     // secure SMTP
                    secure:payload.secure || false, // false for TLS - as a boolean not string - but the default is false so just remove this completely
                    auth: payload.auth,
                    debug: true,
                    tls: payload.tls || {ciphers: 'SSLv3'}
                });
                
                transporter.sendMail(payload, function (error, info) {
                    if (error) {
                        return console.log(error);
                    }
                    updateMessage(updatedMsg);
                });
**PS : This has been working for more than a year and suddenly stopped working. Please Help !!**

**Comment by yashdogra31** [comment]
I found out that our team has disabled office365 smtp basic auth .

Instead of smtp basic auth , smtp modern auth is required.

What i need to figure out now is what needs to be updated in the configuration(in my code) now 

var transporter = nodemailer.createTransport({
                    host: payload.host || 'smtp.office365.com', // Office 365 server
                    port: payload.port || 587,     // secure SMTP
                    secure:payload.secure || false, // false for TLS - as a boolean not string - but the default is false so just remove this completely
                    auth: payload.auth,
                    debug: true,
                    tls: payload.tls || {ciphers: 'SSLv3'}
                });
**Please reply if someone can help here.**

**Comment by andris9** [comment]
This so-called "modern" authentication is supported by the following email clients:

* Outlook 2013 or later
* Outlook 2016 for Mac or later
* Outlook for iOS and Android
* Mail for iOS 11.3.1 or later

As you can see, Nodemailer is not on that list and thus can not send emails through such accounts.

**Comment by yashdogra31** [comment]
Hi andris,
Thank you for your prompt reply.
Are you aware of any other way/module which can be used to send mails in node supporting "modern" authentication ?
it would be a huge help.

**Comment by bluepuma77** [comment]
Hi, what's the current situation with this topic? Outlook365 (part of Office365) is on the official list of ["well-known" and supported services](https://nodemailer.com/smtp/well-known/), but it doesn't seem work.

I created a Microsoft 365 Business Basic account, I can log in via web with the created username/password, but nodemailer can't authenticate. No warning regarding spam suspicion or any setting that seem relevant. (Which I have seen with Gmail.)

```
let transporter = nodemailer.createTransport({
    service: '"Outlook365"', 
    auth: {
        user: 'service@my.org',
        pass: 'ABCabc123+-='
    },
    debug: true,
    logger:true,
});
```

```
[2020-05-27 19:58:30] DEBUG Sending mail using SMTP/6.4.6[client:6.4.6]
[2020-05-27 19:58:30] DEBUG [WDu1NxQIIm0] Resolved smtp.office365.com as 40.101.61.130 [cache miss]
[2020-05-27 19:58:30] INFO  [WDu1NxQIIm0] Connection established to 40.101.61.130:587
[2020-05-27 19:58:30] DEBUG [WDu1NxQIIm0] S: 220 AM5PR0502CA0007.outlook.office365.com Microsoft ESMTP MAIL Service ready at Wed, 27 May 2020 19:58:30 +0000
[2020-05-27 19:58:30] DEBUG [WDu1NxQIIm0] C: EHLO myHome
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-AM5PR0502CA0007.outlook.office365.com Hello [77.13.123.123]
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-SIZE 157286400
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-PIPELINING
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-DSN
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-ENHANCEDSTATUSCODES
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-STARTTLS
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-8BITMIME
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-BINARYMIME
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-CHUNKING
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250 SMTPUTF8
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] C: STARTTLS
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 220 2.0.0 SMTP server ready
[2020-05-27 19:58:31] INFO  [WDu1NxQIIm0] Connection upgraded with STARTTLS
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] C: EHLO myHome
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-AM5PR0502CA0007.outlook.office365.com Hello [77.13.123.123]
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-SIZE 157286400
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-PIPELINING
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-DSN
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-ENHANCEDSTATUSCODES
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-AUTH LOGIN XOAUTH2
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-8BITMIME
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-BINARYMIME
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250-CHUNKING
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 250 SMTPUTF8
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] SMTP handshake finished
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] C: AUTH LOGIN
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 334 VXNlcmABC123
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] C: c2VydmljZUBiZXN1Y2hzc3lzdGABC123
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] S: 334 UGFzc3ABC123
[2020-05-27 19:58:31] DEBUG [WDu1NxQIIm0] C: Z2g1RiszU3Ytejc9ABC123==
[2020-05-27 19:58:36] DEBUG [WDu1NxQIIm0] S: 535 5.7.3 Authentication unsuccessful [AM5PR0502CA0007.eurprd05.prod.outlook.com]
[2020-05-27 19:58:37] INFO  [WDu1NxQIIm0] User "service@my.org" failed to authenticate
[2020-05-27 19:58:37] DEBUG [WDu1NxQIIm0] Closing connection to the server using "end"
[2020-05-27 19:58:37] ERROR Send Error: Invalid login: 535 5.7.3 Authentication unsuccessful [AM5PR0502CA0007.eurprd05.prod.outlook.com]
error Error: Invalid login: 535 5.7.3 Authentication unsuccessful [AM5PR0502CA0007.eurprd05.prod.outlook.com]
    at SMTPConnection._formatError (/Users/Develop/server/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._actionAUTHComplete (/Users/Develop/server/node_modules/nodemailer/lib/smtp-connection/index.js:1523:34)
    at SMTPConnection.<anonymous> (/Users/Develop/server/node_modules/nodemailer/lib/smtp-connection/index.js:1481:18)
    at SMTPConnection._processResponse (/Users/Develop/server/node_modules/nodemailer/lib/smtp-connection/index.js:942:20)
    at SMTPConnection._onData (/Users/Develop/server/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
    at TLSSocket.SMTPConnection._onSocketData (/Users/Develop/server/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
  code: 'EAUTH',
  response: '535 5.7.3 Authentication unsuccessful [AM5PR0502CA0007.eurprd05.prod.outlook.com]',
  responseCode: 535,
  command: 'AUTH LOGIN'
```

**Comment by andris9** [comment]
@bluepuma77 There can be several reasons why O365 (or any SMTP server) does not accept your credentials. Nodemailer takes whatever you give it, passes these to the server and if server does not accept the credentials then there is absolutely nothing to do on the Nodemailer side. 

Make sure that your domain admin has not disabled "basic" authentication. It is also usually safer to generate and use app passwords instead of using account passwords.

**Comment by bluepuma77** [comment]
Hi @andris9,

I think the question is: **does anyone have O365 (now "Microsoft 365") currently working with nodemailer?** I believe that nodemailer is a great piece of software, but maybe Microsoft has some quirky mechanisms that don't play well with the common standards.

Older "status-quo" doesn't really help as the email providers continuously increase security and restrictions. Maybe it doesn't work anymore and O365 has to be removed from the "supported" list.

An online forum would make life for nodemailer users a lot easier, with a section for "supported services" and an area for each service, so users can exchange best practice. Or inform others when it's not working anymore.

![Screenshot-Microsoft-Office-365-Email](https://user-images.githubusercontent.com/5221187/83107737-0fa6aa80-a0bf-11ea-87d6-cc221d63fcae.png)

**Comment by bluepuma77** [comment]
The Outlook365 settings are at least 1.5 yers old, maybe they are just not valid anymore.

```
    "Outlook365": {
        "host": "smtp.office365.com",
        "port": 587,
        "secure": false
    },
```

**Comment by andris9** [comment]
@bluepuma77 Here's my test script and logs for a successful delivery via O365 account: https://gist.github.com/andris9/3df2d3111b1de4e5a0a51dcbb345210f

Some notes to consider:
* You can not use any other address as `from` than your own account email address or message is not accepted (though if you can not log in at all then this point does not concern you)
* My password does not include any special characters. Only ascii letters (both upper and lowercase) and numbers.
* I was not able to send using `ORGANIZATION\username` format as the username, it had to be email address
* I am not the admin of that organization, I have no idea what kind of settings they have

**Comment by bluepuma77** [comment]
Hi @andris9,

I had to investigate further, drive my team in sane by changing passwords all the time. Still doesn't work. 

But I did find a difference in the logs: base64. Why is that? I am using node v12.16.1 and nodemailer 6.4.10.

Yours
```
[2020-05-28 07:14:25] DEBUG [P7xvpVEEM] C: AUTH LOGIN
[2020-05-28 07:14:25] DEBUG [P7xvpVEEM] S: 334 VXNlcm5hbWU6
[2020-05-28 07:14:25] DEBUG [P7xvpVEEM] C: <base64:areinman@org.domain>
[2020-05-28 07:14:25] DEBUG [P7xvpVEEM] S: 334 UGFzc3dvcmQ6
[2020-05-28 07:14:25] DEBUG [P7xvpVEEM] C: <base64:password>
[2020-05-28 07:14:25] DEBUG [P7xvpVEEM] S: 235 2.7.0 Authentication successful
[2020-05-28 07:14:25] INFO  [P7xvpVEEM] User "areinman@org.domain" authenticated
```

Mine
```
[2020-06-17 09:34:55] DEBUG [NNmbQi1SKHg] C: AUTH LOGIN
[2020-06-17 09:34:55] DEBUG [NNmbQi1SKHg] S: 334 VXNlcm5hbWU6
[2020-06-17 09:34:55] DEBUG [NNmbQi1SKHg] C: c2VydmljZUXxXxXxXxhzc3lzdGVtLmRl
[2020-06-17 09:34:55] DEBUG [NNmbQi1SKHg] S: 334 UGFzc3dvcmQ6
[2020-06-17 09:34:55] DEBUG [NNmbQi1SKHg] C: amY1VGgXxXxXxXxaam5kNA==
[2020-06-17 09:35:00] DEBUG [NNmbQi1SKHg] S: 535 5.7.3 Authentication unsuccessful [AM6P192CA0052.EURP192.PROD.OUTLOOK.COM]
[2020-06-17 09:35:00] INFO  [NNmbQi1SKHg] User "service@XxXxXxXxsystem.de" failed to authenticate
```

**Comment by bluepuma77** [comment]
Same with node v14.4.0, it is not showing "base64" on a Mac.

**Comment by bluepuma77** [comment]
Same with node v12.17.0, it is not showing "base64" on Linux Debian 10.

**Comment by bluepuma77** [comment]
I am the domain admin, I created all Office365 accounts. But I can't find an option to `disabled "basic" authentication` and for sure have nothing activated like that.

**Comment by andris9** [comment]
Whatever the reason actually is, the logs show that Nodemailer passes credentials to server correctly and there is absolutely nothing that could be done in Nodemailer side.

What you can do though is to:

1. Try to authenticate using another user.
2. Some servers are also picky about some special symbols in passwords, so check that your password would only contain ascii letters and numbers.
3. Also check that your account does not have 2-factor authentication enabled (and if is, then create an application specific password to use).
4. Check the docs for Exchange Online [authentication](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission)
5. Look for help from [Server Fault](https://serverfault.com/) forums

**Comment by bluepuma77** [comment]
Thanks for your response again. I tried different users with different passwords, even only alphanumeric characters. I can use username/password to login via webmail without a problem, no 2-factor required.

I have not used "Exchange Online PowerShell". I am really surprised that Microsoft does such nasty things with downloadable Windows tools when everything should be just configurable online.

I still don't understand why your logs shows "base64" and mine not. I assume the content is the same.

**Comment by bluepuma77** [comment]
Finally I found the solution. As an Office365 (now Microsoft365) customer I need to go to portal.azure.com, then "Manage", "Properties" and set "Manage Security defaults" to "no". I think this is messed up, but it works.

https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-security-defaults

@andris9 Thanks so much for your support, maybe you add that link to the docs.

**Comment by andris9** [comment]
@bluepuma77  Great to know, thanks!

**Comment by JulianTonti** [comment]
I have the same issue here and it seems to be related to 2-factor authentication (which is switched on). Unfortunately, I do not have permission to modify 2-factor settings at work so I cannot use this library with Office365.

**Comment by jiahengzhang66** [comment]
Same. Disabling security defaults for my Outlook Essentials account worked for me

**Comment by arnileibovits** [comment]
You need to make sure SMTP AUTH is enabled. Check these articles:
https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365
https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission

Opening up the **Manage email apps** setting helped me (even without saving).

**Comment by Seimodei** [comment]
For anyone facing this issue in 2024, I was able solve the issue by going into microsoft admin center, going to the settings page, clicking on the mail flow option, and on the side panel that opens up, I checked the "Turn on use of legacy TLS clients" option. Hope that helps someone.
