### ISSUE TITLE
Repeated "530 5.5.1 Authentication Required." error even when using Authentication Details

### ISSUE THREAD

**Issue by T0MGithub** [nodemailer/nodemailer#1082]
I sincerely hope this is a bug and not just me being stupid. I cannot explain the issue - I am getting repeated 530 5.5.1 errors while using Zoho. The error occurs when I try to send an email like the following. I have also tried on port 587, removing the ``type: 'login'`` and more. The login values ARE being passed to the transporter and using ``transporter.validate`` raises no issues.
```js
const transporter = nodemailer.createTransport({
    host: "smtp.zoho.eu",
    post: 465,
    secure: true,
    auth: {
      type: "login",
      user: process.env.NO_REPLY_EMAIL_ADDRESS,
      pass: process.env.NO_REPLY_EMAIL_PASSWORD
    }
  });

  let emailData = {
    from: process.env.NO_REPLY_EMAIL_ADDRESS,
    to: 'emailfortomg@gmail.com',
    subject: "Email verification code for your TGameKeys account",
    html: `<h1> Your TGameKeys Verification code </h1>\n<p> Code:  </p>`
  };
  transporter.sendMail(emailData, function(err, response) {
    console.log(err);
  });
```

However, I can send emails using smtper.net, with the same (correct details) and same configuration, as seen below, so I can only think this is a Nodemailer issue
![image](https://user-images.githubusercontent.com/47010185/70374669-0a755980-18ed-11ea-9b54-fa0052e866d3.png)

Full Error:
```
{ Error: Mail command failed: 530 5.5.1 Authentication Required.
    at SMTPConnection._formatError (C:\Users\Thomas\Desktop\Projects\Web Development\TGameKeys\code\node_modules\nodemailer\lib\smtp-connection\index.js:777:19)
    at SMTPConnection._actionMAIL (C:\Users\Thomas\Desktop\Projects\Web Development\TGameKeys\code\node_modules\nodemailer\lib\smtp-connection\index.js:1546:34)
    at SMTPConnection._responseActions.push.str (C:\Users\Thomas\Desktop\Projects\Web Development\TGameKeys\code\node_modules\nodemailer\lib\smtp-connection\index.js:1028:18)
    at SMTPConnection._processResponse (C:\Users\Thomas\Desktop\Projects\Web Development\TGameKeys\code\node_modules\nodemailer\lib\smtp-connection\index.js:935:20)
    at SMTPConnection._onData (C:\Users\Thomas\Desktop\Projects\Web Development\TGameKeys\code\node_modules\nodemailer\lib\smtp-connection\index.js:742:14)
    at TLSSocket.SMTPConnection._onSocketData.chunk (C:\Users\Thomas\Desktop\Projects\Web Development\TGameKeys\code\node_modules\nodemailer\lib\smtp-connection\index.js:195:44)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  code: 'EENVELOPE',
  response: '530 5.5.1 Authentication Required.',
  responseCode: 530,
  command: 'MAIL FROM' }
```
Log:
```
2019-12-07 12:29:00] DEBUG [v9bHY3Fgcbw] Resolved smtp.zoho.eu as 87.252.213.164 [cache miss]
[2019-12-07 12:29:00] INFO  [v9bHY3Fgcbw] Secure connection established to 87.252.213.164:465
[2019-12-07 12:29:00] DEBUG [v9bHY3Fgcbw] SMTP handshake finished
[2019-12-07 12:29:00] INFO  Sending message <REDACTED@tgamekeys.com> to <REDACTED@gmail.com>
[2019-12-07 12:29:00] DEBUG [v9bHY3Fgcbw] Closing connection to the server using "end"
[2019-12-07 12:29:00] ERROR Send error for <REDACTED@tgamekeys.com>: Mail command failed: 530 5.5.1 Authentication Required.
[2019-12-07 12:29:00] ERROR Send Error: Mail command failed: 530 5.5.1 Authentication Required.
{ Error: Mail command failed: 530 5.5.1 Authentication Required.
    at SMTPConnection._formatError (C:\Users\Thomas\Desktop\Projects\Web Development\TGameKeys\code\node_modules\nodemailer\lib\smtp-connection\index.js:777:19)
    at SMTPConnection._actionMAIL (C:\Users\Thomas\Desktop\Projects\Web Development\TGameKeys\code\node_modules\nodemailer\lib\smtp-connection\index.js:1546:34)
    at SMTPConnection._responseActions.push.str (C:\Users\Thomas\Desktop\Projects\Web Development\TGameKeys\code\node_modules\nodemailer\lib\smtp-connection\index.js:1028:18)
    at SMTPConnection._processResponse (C:\Users\Thomas\Desktop\Projects\Web Development\TGameKeys\code\node_modules\nodemailer\lib\smtp-connection\index.js:935:20)
    at SMTPConnection._onData (C:\Users\Thomas\Desktop\Projects\Web Development\TGameKeys\code\node_modules\nodemailer\lib\smtp-connection\index.js:742:14)
    at TLSSocket.SMTPConnection._onSocketData.chunk (C:\Users\Thomas\Desktop\Projects\Web Development\TGameKeys\code\node_modules\nodemailer\lib\smtp-connection\index.js:195:44)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  code: 'EENVELOPE',
  response: '530 5.5.1 Authentication Required.',
  responseCode: 530,
  command: 'MAIL FROM' }
[2019-12-07 12:29:00] INFO  [v9bHY3Fgcbw] Connection closed
```
Again, I hope this isn't some mis-configuration on my part, but being able to use SMTPer makes me believe this is a Nodemailer issue. Thanks for any help.

**Comment by T0MGithub** [comment]
I reverted to version 6.3.1 and the code now works, I believe this error is caused by [Commit 65e7997](https://github.com/nodemailer/nodemailer/commit/f419b09de7a8fe445439a99b450afa9aee1a8a5f), which meant Nodemailer wasn't using auth with the Zoho server. Could anyone advise me how to fix the code to be able to update the package to the latest version.

**Comment by andris9** [comment]
@T0MGithub could you try v6.4.1 if it fixes your issue?

**Comment by T0MGithub** [comment]
@andris9 Yep all good - I updated to v6.4.1 and everything still seems to be working. Thanks a lot.
