### ISSUE TITLE
v6.4.0 breaks emailing via Zoho 

### ISSUE THREAD

**Issue by kyrylkov** [nodemailer/nodemailer#1083]
```
const transporter = nodemailer.createTransport({
  service: 'zoho',
  auth: {
    user: '***',
    pass: '***',
  },
});
```

``` 
Error: Mail command failed: 530 5.5.1 Authentication Required.
    at SMTPConnection._formatError (/home/vcap/deps/0/node_modules/nodemailer/lib/smtp-connection/index.js:777:19)
    at SMTPConnection._actionMAIL (/home/vcap/deps/0/node_modules/nodemailer/lib/smtp-connection/index.js:1546:34)
    at SMTPConnection.<anonymous> (/home/vcap/deps/0/node_modules/nodemailer/lib/smtp-connection/index.js:1028:18)
    at SMTPConnection._processResponse (/home/vcap/deps/0/node_modules/nodemailer/lib/smtp-connection/index.js:935:20)
    at SMTPConnection._onData (/home/vcap/deps/0/node_modules/nodemailer/lib/smtp-connection/index.js:742:14)
    at TLSSocket.SMTPConnection._onSocketData (/home/vcap/deps/0/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
    at TLSSocket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:326:12)
    at readableAddChunk (_stream_readable.js:301:11)
    at TLSSocket.Readable.push (_stream_readable.js:235:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23)```

**Comment by andris9** [comment]
Upgrade to 6.4.1
