### ISSUE TITLE
Transport-related error outputs since upgrading from 6.3.1 to 6.4.1

### ISSUE THREAD

**Issue by valeriansaliou** [nodemailer/nodemailer#1086]
Hi there! Using nodemailer over at Crisp; we upgraded from 6.3.1 to 6.4.1 yesterday, and we're now seeing a recurring error being reported, that we never saw before:

```
TypeError: Cannot read property 'split' of undefined
    at SMTPConnection._onData (/private/path/eluded/to/project/node_modules/nodemailer/lib/smtp-connection/index.js:743:39)
    at Socket.SMTPConnection._onSocketData.chunk (/private/path/eluded/to/project/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

Any regression due to the latest minor updates?

**Comment by andris9** [comment]
Could you try v6.4.2?

**Comment by valeriansaliou** [comment]
Thanks, trying that. I'll re-open if this still happens on v6.4.2.
