### ISSUE TITLE
read ECONNRESET at TLSWrap.onStreamRead

### ISSUE THREAD

**Issue by snehil2112** [nodemailer/nodemailer#1088]
async sendMail(email: string) {
        let transporter = mailer.createTransport({
            host: "smtp-mail.outlook.com",
            secureConnection: false,
            port: 587,
            auth: {
                user: "username@company-domain.com",
                pass: "xxxxxx"
            },
            tls: {
                ciphers:'SSLv3',
                rejectUnauthorised: false
            },
            logger: true,
            debug: true
        });
    
        let info = await transporter.sendMail({
            from: '"User" <username@company-domain.com>',
            to: email,
            subject: "Email Testing",
            text: "Hello",
            html: "<b>Hello World</b>"
        });
    
        console.log("Message sent: %s", info.messageId);
        return "Mail Sent";
    }
}

I am using nodemailer to send mail using my company email id. My company uses outlook but has a domain with its own name. The application is getting connected to outlook but after that i get following error.

[2019-12-24 09:46:44] DEBUG Creating transport: nodemailer (6.4.2; +https://nodemailer.com/; SMTP/6.4.2[client:6.4.2])
[2019-12-24 09:46:44] DEBUG Sending mail using SMTP/6.4.2[client:6.4.2]
 [2019-12-24 09:46:44] DEBUG [Ho1tEXHDDP4] Resolved smtp-mail.outlook.com as 40.100.136.130 [cache miss]
[2019-12-24 09:46:44] INFO  [Ho1tEXHDDP4] Connection established to 40.100.136.130:587
 [2019-12-24 09:46:44] DEBUG [Ho1tEXHDDP4] S: 220 MAXPR0101CA0039.outlook.office365.com Microsoft ESMTP MAIL Service ready at Tue, 24 Dec 2019 09:46:43 +0000
 [2019-12-24 09:46:44] DEBUG [Ho1tEXHDDP4] C: EHLO [127.0.0.1]
[2019-12-24 09:46:44] DEBUG [Ho1tEXHDDP4] S: 250-MAXPR0101CA0039.outlook.office365.com Hello [115.110.155.29]
 [2019-12-24 09:46:44] DEBUG [Ho1tEXHDDP4] S: 250-SIZE 157286400
[2019-12-24 09:46:44] DEBUG [Ho1tEXHDDP4] S: 250-PIPELINING
 [2019-12-24 09:46:44] DEBUG [Ho1tEXHDDP4] S: 250-DSN
 [2019-12-24 09:46:44] DEBUG [Ho1tEXHDDP4] S: 250-ENHANCEDSTATUSCODES
 [2019-12-24 09:46:44] DEBUG [Ho1tEXHDDP4] S: 250-STARTTLS
 [2019-12-24 09:46:44] DEBUG [Ho1tEXHDDP4] S: 250-8BITMIME
 [2019-12-24 09:46:44] DEBUG [Ho1tEXHDDP4] S: 250-BINARYMIME
 [2019-12-24 09:46:44] DEBUG [Ho1tEXHDDP4] S: 250-CHUNKING
[2019-12-24 09:46:44] DEBUG [Ho1tEXHDDP4] S: 250 SMTPUTF8
 [2019-12-24 09:46:44] DEBUG [Ho1tEXHDDP4] C: STARTTLS
[2019-12-24 09:46:44] DEBUG [Ho1tEXHDDP4] S: 220 2.0.0 SMTP server ready
 [2019-12-24 09:47:03] ERROR [Ho1tEXHDDP4] read ECONNRESET
 [2019-12-24 09:47:03] DEBUG [Ho1tEXHDDP4] Closing connection to the server using "end"
 [2019-12-24 09:47:03] ERROR Send Error: read ECONNRESET
 (node:74564) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
     at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
 [2019-12-24 09:47:03] INFO  [Ho1tEXHDDP4] Connection closed
 (node:74564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
 (node:74564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 [2019-12-24 09:47:03] INFO  [Ho1tEXHDDP4] Connection closed

**Comment by snehil2112** [comment]
any progress on this?

**Comment by andris9** [comment]
TLS handshake fails. Probably some incompatibility with your SMTP server and your Node version. Make sure bot sides can use the same TLS version and ciphers.

**Comment by akshayrathod-92** [comment]
Hello @andris9 ,

I am getting the same error with similar configuration for createTransport().
And when I try to send email using openssl from linux terminal where my application is installed, the email gets sent but the email sending fails from the application.

Here is the openssl command which works,
openssl s_client -crlf -quiet -starttls smtp -connect email-smtp.eu-west-1.amazonaws.com:587 < mail-input.txt

And here is the error when application tries to send email,

DEBUG [rirUyJIsdaQ] Resolved email-smtp.eu-west-1.amazonaws.com as ##.###.###.## [cache miss]
ERROR [rirUyJIsdaQ] read ECONNRESET
DEBUG [rirUyJIsdaQ] Closing connection to the server using "destroy"
transporter.verify error:  Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: 'ECONNRESET',
  code: 'ESOCKET',
  syscall: 'read',
  command: 'CONN'
}

**Comment by snells92** [comment]
Hello  @andris9 ,

I am getting the same error with similar configuration for createTransport().
And when I try to send email using openssl from linux terminal where my application is installed, the email gets sent but the email sending fails from the application.

Here is the openssl command which works,
openssl s_client -crlf -quiet -starttls smtp -connect email-smtp.eu-west-1.amazonaws.com:587 < mail-input.txt

And here is the error when application tries to send email,

DEBUG [rirUyJIsdaQ] Resolved email-smtp.eu-west-1.amazonaws.com as ##.###.###.## [cache miss]
ERROR [rirUyJIsdaQ] read ECONNRESET
DEBUG [rirUyJIsdaQ] Closing connection to the server using "destroy"
transporter.verify error: Error: read ECONNRESET
at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
errno: 'ECONNRESET',
code: 'ESOCKET',
syscall: 'read',
command: 'CONN'
}
