### ISSUE TITLE
Greeting never received when connection is established on 52.98.89.34:587

### ISSUE THREAD

**Issue by SarathkumarRajendran** [nodemailer/nodemailer#1099]
Sometime the connection is established with socket starting with 40.xxx.xxx.xx:587 and able to send email successfully. 

But sometime the connection is established on 52.98.89.34:587 and getting below error message:

Can you please look into this and help me to get it resolved.

Please suggest me a way if always establish connection on specific socket , say 40.101.146.98:587.

**Error message received:**
2020-01-28 07:00:48] DEBUG [rbPhiu81f6c] Resolved smtp-mail.outlook.com as 52.98.89.34 [cache miss]
[2020-01-28 07:00:48] INFO  [rbPhiu81f6c] Connection established to 52.98.89.34:587
[2020-01-28 07:01:18] ERROR [rbPhiu81f6c] Greeting never received
[2020-01-28 07:01:18] DEBUG [rbPhiu81f6c] Closing connection to the server using "end"
[2020-01-28 07:01:18] ERROR Send Error: Greeting never received
Error: Greeting never received
    at SMTPConnection._formatError (/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._onError (/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
    at Timeout.<anonymous> (/node_modules/nodemailer/lib/smtp-connection/index.js:704:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  code: 'ETIMEDOUT',
  command: 'CONN'
}

**Scripts**:

let transporter = nodemailer.createTransport({
      host: "smtp-mail.outlook.com",
       port: 587,
      secureConnection: false,
      tls: {
          ciphers: 'SSLv3'
      },
    auth: {
      user: 'userid',
      pass: 'password' 
    },
    logger: true,
  });

NOTE: The issue exists only when the connection is established on 52.XX.XX.XX:587. Whereas it's working when the connection is established on 40.xxx.xxx.xx:587

**Comment by MarcelloMorra** [comment]
I have the same error: Greeting never received. Never seen before on 2 years of Nodemailer.

**Comment by SarathkumarRajendran** [comment]
Can anyone please help me how to make a SMTP connection always to IP address starting with 40.xxx.xxx.xx:587. It would be really helpful as it's a blocker for me now.

**Comment by andris9** [comment]
Nodemailer uses available network stack. If you are firewalled or behind a very slow network then there's nothing to do on the Nodemailer side.
