### ISSUE TITLE
Not able to install nodemailer (npm)

### ISSUE THREAD

**Issue by ym222bs** [nodemailer/nodemailer#1109]
End of err log:

```bash
....
352 silly saveTree | +-- stealthy-require@1.1.1
352 silly saveTree | `-- tough-cookie@2.4.3
352 silly saveTree |   `-- punycode@1.4.1
352 silly saveTree `-- request@2.88.2
353 verbose stack Error: EINVAL: invalid argument, read
353 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\rm.js:245:7
353 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\node_modules\iferr\index.js:13:50
353 verbose stack     at callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:295:20)
353 verbose stack     at FSReqWrap.oncomplete (fs.js:155:5)
354 verbose cwd D:\Skola\testing_github_auth
355 verbose Windows_NT 6.1.7601
356 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "nodemailer" "--save"
357 verbose node v10.15.0
358 verbose npm  v6.13.4
359 error code EINVAL
360 error EINVAL: invalid argument, read
361 verbose exit [ 1, true ]
```

From bash:
![image](https://user-images.githubusercontent.com/31442414/75481246-095f4000-59a3-11ea-9195-82f2cd32ff25.png)

I also tried `npm cache clean --force`  before with no luck. 

node version: `v10.15.0`

npm version `6.13.4`

**Comment by ym222bs** [comment]
Don't know what caused it, 
but removing `node_modules` and doing a clean `npm install` solved it !
