### ISSUE TITLE
TypeError: done is not a function

### ISSUE THREAD

**Issue by helderdb** [nodemailer/nodemailer#1114]
Hi,

I'm getting an error trying to send mail over SMTP:
```
TypeError: done is not a function
    at callback (node_modules/nodemailer/lib/smtp-connection/index.js:607:13)
    at node_modules/nodemailer/lib/smtp-connection/index.js:617:24
    at SMTPConnection._setEnvelope (node_modules/nodemailer/lib/smtp-connection/index.js:995:20)
    at SMTPConnection.send (node_modules/nodemailer/lib/smtp-connection/index.js:615:14)
    at node_modules/nodemailer/lib/mailer/index.js:214:34
    at Mail._processPlugins (node_modules/nodemailer/lib/mailer/index.js:262:20)
    at node_modules/nodemailer/lib/mailer/index.js:184:18
    at processPlugins (node_modules/nodemailer/lib/mailer/index.js:275:28)
    at node_modules/nodemailer/lib/mailer/index.js:283:17
    at Mail._convertDataImages (node_modules/nodemailer/lib/mailer/index.js:387:20)
    at Mail._defaultPlugins.compile (node_modules/nodemailer/lib/mailer/index.js:31:41)
    at processPlugins (node_modules/nodemailer/lib/mailer/index.js:279:13)
    at Mail._processPlugins (node_modules/nodemailer/lib/mailer/index.js:287:9)
    at Mail.sendMail (node_modules/nodemailer/lib/mailer/index.js:164:14)
    at r.default (.next/server/static/development/pages/api/jobApplication.js:1:1690)
    at Object.apiResolver (node_modules/next/dist/next-server/server/api-utils.js:51:15)
```

Config:

```
const transporter = createTransport(new SMTPConnection({
      host: "smtp.office365.com",
      port: 587,
      secure: false,
      debug:true,
      logger: true,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS
      }
    }));
const result = await transporter.sendMail({
      from: process.env.FROM_EMAIL,
      to: process.env.TO_EMAIL,
      subject: "New job application",
      text: "New job application",
    });
```

Nodemailer version 6.4.4
node: 12.14.1

**Comment by helderdb** [comment]
Found the issue. If using typescript, don't use `new SMTPConnection(...)` in createTransport. It breaks things.
