### ISSUE TITLE
Nodemailer cannot use smtp.gmail.com to send email anymore  

### ISSUE THREAD

**Issue by rishat5081** [nodemailer/nodemailer#1116]
Hii !!! 
 i am using Node v10.16.0
 nodemailer 6.3.0

here is the code 

[var transport = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 465,
    secure: true, // use TLS
    auth: {
        user: "abc@gmail.com",
        pass: "password"
    },
    tls: {
        // do not fail on invalid certs
        rejectUnauthorized: false
    }
})

var option =
{
    from: '"Itz "<abc@gmail.com>',
    to: `Saad Sohail <rishat.5081@gmail.com>`,
    subject: 'Testing ',
    text: 'Hello',
}
  transport.sendMail(option, (error, info) => {

    if (error)
        console.log(error)
    else {
        console.log(info)
        transport.close()
    }
})
](url)

and here is the error i can't get rid of this error 

{ Error: Invalid login: 534-5.7.9 Application-specific password required. Learn more at
534 5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor o13sm2119833lfg.90 - gsmtp
    at SMTPConnection._formatError (D:\Saad Sohail\Projects\projects\Nodemailer HandlerBars\node_modules\nodemailer\lib\smtp-connection\index.js:781:19)
    at SMTPConnection._actionAUTHComplete (D:\Saad Sohail\Projects\projects\Nodemailer HandlerBars\node_modules\nodemailer\lib\smtp-connection\index.js:1516:34) 
    at SMTPConnection._responseActions.push.str (D:\Saad Sohail\Projects\projects\Nodemailer HandlerBars\node_modules\nodemailer\lib\smtp-connection\index.js:554:26)
    at SMTPConnection._processResponse (D:\Saad Sohail\Projects\projects\Nodemailer HandlerBars\node_modules\nodemailer\lib\smtp-connection\index.js:940:20)     
    at SMTPConnection._onData (D:\Saad Sohail\Projects\projects\Nodemailer HandlerBars\node_modules\nodemailer\lib\smtp-connection\index.js:746:14)
    at TLSSocket.SMTPConnection._onSocketData (D:\Saad Sohail\Projects\projects\Nodemailer HandlerBars\node_modules\nodemailer\lib\smtp-connection\index.js:189:46)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
  code: 'EAUTH',
  response:
   '534-5.7.9 Application-specific password required. Learn more at\n534 5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor o13sm2119833lfg.90 - gsmtp',
  responseCode: 534,
  command: 'AUTH PLAIN' }

**Comment by andris9** [comment]
Gmail is blocking your IP, nothing to do with Nodemailer.

**Comment by ralexrdz** [comment]
having same issue

**Comment by rishat5081** [comment]
@ralexrdz did you find the solution?

**Comment by haseeb1009** [comment]
I am also facing the similar issue
