### ISSUE TITLE
transporter.verify(callback) example doesn't output error message

### ISSUE THREAD

**Issue by ruihildt** [nodemailer/nodemailer#1179]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

Following the guide from Nodemailer [ SMTP Transport page](https://nodemailer.com/smtp/), I've tried to verify connection configuration.

If the configuration is correct, the message from the console is correctly shown.

**If the configuration is not correct, nothing is shown in the console**, and the app is stalled.

I tested with a simple node + nodemailer app, with the same result.

**Comment by andris9** [comment]
Can not confirm, failed authentication is handled as expected:

```
transporter.verify(function (error, success) {
    if (error) {
        console.error('Verification failed');
        console.error(error);
    } else {
        console.log('Server is ready to take our messages');
    }
});
```

```
Verification failed
Error: Invalid login: 535 Authentication failed
    at SMTPConnection._formatError (/Users/andrisreinman/Projects/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._actionAUTHComplete (/Users/andrisreinman/Projects/nodemailer/lib/smtp-connection/index.js:1523:34)
    at SMTPConnection.<anonymous> (/Users/andrisreinman/Projects/nodemailer/lib/smtp-connection/index.js:550:26)
    at SMTPConnection._processResponse (/Users/andrisreinman/Projects/nodemailer/lib/smtp-connection/index.js:942:20)
    at SMTPConnection._onData (/Users/andrisreinman/Projects/nodemailer/lib/smtp-connection/index.js:749:14)
    at TLSSocket.SMTPConnection._onSocketData (/Users/andrisreinman/Projects/nodemailer/lib/smtp-connection/index.js:195:44)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:304:12)
    at readableAddChunk (_stream_readable.js:280:9)
    at TLSSocket.Readable.push (_stream_readable.js:219:10) {
  code: 'EAUTH',
  response: '535 Authentication failed',
  responseCode: 535,
  command: 'AUTH PLAIN'
}
```
