### ISSUE TITLE
Error: Missing credentials for "PLAIN"

### ISSUE THREAD

**Issue by MathiasDrapier** [nodemailer/nodemailer#1255]
Hello, I saw that a lot of people are facing this problem but no solution has been proposed.

Here is whose error I am encountering:

`Error: Missing credentials for "PLAIN"
		at SMTPConnection._formatError (/home/debian/smarthome-frontend/docker-rd/node_modules/nodemailer/lib/smtp-connection/index.js:774:19)
		at SMTPConnection.login (/home/debian/smarthome-frontend/docker-rd/node_modules/nodemailer/lib/smtp-connection/index.js:438:38)
		at /home/debian/smarthome-frontend/docker-rd/node_modules/nodemailer/lib/smtp-transport/index.js:271:32
		at SMTPConnection.<anonymous> (/home/debian/smarthome-frontend/docker-rd/node_modules/nodemailer/lib/smtp-connection/index.js:209:17)
		at Object.onceWrapper (node:events:484:28)
		at SMTPConnection.emit (node:events:378:20)
		at SMTPConnection._actionEHLO (/home/debian/smarthome-frontend/docker-rd/node_modules/nodemailer/lib/smtp-connection/index.js:1303:14)
		at SMTPConnection._processResponse (/home/debian/smarthome-frontend/docker-rd/node_modules/nodemailer/lib/smtp-connection/index.js:932:20)
		at SMTPConnection._onData (/home/debian/smarthome-frontend/docker-rd/node_modules/nodemailer/lib/smtp-connection/index.js:739:14)
		at TLSSocket.SMTPConnection._onSocketData (/home/debian/smarthome-frontend/docker-rd/node_modules/nodemailer/lib/smtp-connection/index.js:189:44) {
	code: 'EAUTH',
	command: 'API'
}`

And here my code:

`var transporter = nodemailer.createTransport({
        service: "gmail",
        auth: {user: 'xxx@gmail.com', pass: *****'}
});`

**Comment by andris9** [comment]
This error usually happens when you either
* have a typo somewhere in the config
* you are not using a hardcoded password but use something like an environment variable that does not actually exist

The error is triggered when `auth.pass` is empty or not set

**Comment by MathiasDrapier** [comment]
Thank you for your answer, yet my password is hard-coded ....

**Comment by andris9** [comment]
Could you try running the example from the Nodemailer homepage [here](https://nodemailer.com/about/#example) (no modifications needed, copy-paste and run) and see if it succeeds or not?

**Comment by MathiasDrapier** [comment]
It works well I don't know where my error is I will continue to search

**Comment by ijiwole** [comment]
were you able to find solution to it??

**Comment by FathZulfaAli** [comment]
+1 face the same issue, this error slap me in production
