### ISSUE TITLE
554 Local Policy Violation

### ISSUE THREAD

**Issue by nitin41** [nodemailer/nodemailer#1257]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
I'm getting following error.
smtp config is {
host: 'example.interpublic.com',
port: 25,
secure: false
}
Error: Invalid greeting. response=554 Local Policy Violation: 554 Local Policy Violation
    at SMTPConnection._actionGreeting (D:\rapport-backend\node_modules\nodemailer\lib\smtp-connection\index.js:1189:27)
    at SMTPConnection._processResponse (D:\rapport-backend\node_modules\nodemailer\lib\smtp-connection\index.js:932:20)
    at SMTPConnection._onData (D:\rapport-backend\node_modules\nodemailer\lib\smtp-connection\index.js:739:14)
    at Socket.SMTPConnection._onSocketData (D:\rapport-backend\node_modules\nodemailer\lib\smtp-connection\index.js:189:44)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: 'EPROTOCOL',
  response: '554 Local Policy Violation',
  responseCode: 554,
  command: 'CONN'
}

**Comment by andris9** [comment]
Your IP is not allowed
