### ISSUE TITLE
Error: Unexpected socket close

### ISSUE THREAD

**Issue by shellac85** [nodemailer/nodemailer#1261]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [ ] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ x] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [ x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:

I  am using Node and Graphql with Nodemailer. I am getting the below error constantly. It means that Nodemailer hardly ever works. Is there a solution or a workaround? Tks

Code:
```
import nodemailer from "nodemailer";

// async..await is not allowed in global scope, must use a wrapper
export async function sendEmail(email: string, url: string) {
  // Generate test SMTP service account from ethereal.email
  // Only needed if you don't have a real mail account for testing
  const testAccount = await nodemailer.createTestAccount();

  // create reusable transporter object using the default SMTP transport
  const transporter = nodemailer.createTransport({
    host: "smtp.ethereal.email",
    port: 587,
    secure: false, // true for 465, false for other ports
    auth: {
      user: testAccount.user, // generated ethereal user
      pass: testAccount.pass, // generated ethereal password
    },
  });

  // send mail with defined transport object
  const info = await transporter.sendMail({
    from: '"Fred Foo 👻" <foo@example.com>', // sender address
    to: email, // list of receivers
    subject: "Hello ✔", // Subject line
    text: "Hello world?", // plain text body
    html: `<a href="${url}">${url}</a>`, // html body
  });

  console.log("Message sent: %s", info.messageId);
  // Message sent: <b658f8ca-6296-ccf4-8306-87d57a0b4321@example.com>

  // Preview only available when sending through an Ethereal account
  console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));
  // Preview URL: https://ethereal.email/message/WaQKMgKddxQDoou...
}


```

Error:
```
 "Error: Unexpected socket close",
            "    at Timeout._onTimeout (/Users/ericgrehan/Documents/MyCode/cakes/c-backend/node_modules/nodemailer/lib/smtp-transport/index.js:189:31)",
            "    at listOnTimeout (internal/timers.js:554:17)",
            "    at processTimers (internal/timers.js:497:7)"
```

**Comment by antoine-souesme-needone** [comment]
I'm facing the same error today.

**Comment by andris9** [comment]
Test site is down. Once it is up then the test script should work again

**Comment by shellac85** [comment]
Thanks. Any idea when that might be?
