### ISSUE TITLE
transport.verify() causes the process to crash due to error thrown from _upgradeConnection method

### ISSUE THREAD

**Issue by MottyMilshtein** [nodemailer/nodemailer#1298]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?
- [x] A bug in Nodemailer
- [ ] A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ] Feature request
- [ ] Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?
- [ ] Yes. Sponsors get priority support
- [x] No. Unless it is a bug in Nodemailer you might find support from public forums like [StackOverflow](https://stackoverflow.com/search?q=nodemailer).

3. State your problem here:
A certain setup of TLS ciphers used to create transport causes the transport verify method to crash the process due to an uncaught error in SMTPConnection -> _upgradeConnection -> tls.connect

`Error: error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match
    at Object.createSecureContext (_tls_common.js:217:13)
    at Object.connect (_tls_wrap.js:1580:48)
    at SMTPConnection._upgradeConnection (C:\repos\node-monorepo\node_modules\nodemailer\lib\smtp-connection\index.js:876:28)
    at SMTPConnection._actionSTARTTLS (C:\repos\node-monorepo\node_modules\nodemailer\lib\smtp-connection\index.js:1346:14)
    at SMTPConnection._processResponse (C:\repos\node-monorepo\node_modules\nodemailer\lib\smtp-connection\index.js:932:20)
    at SMTPConnection._onData (C:\repos\node-monorepo\node_modules\nodemailer\lib\smtp-connection\index.js:739:14)
    at Socket.SMTPConnection._onSocketData (C:\repos\node-monorepo\node_modules\nodemailer\lib\smtp-connection\index.js:189:44)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:131:14)`

**Comment by MottyMilshtein** [comment]
linked pull request: https://github.com/nodemailer/nodemailer/pull/1297
