### ISSUE TITLE
Authentication working on Windows (Local), failing on Ubuntu (VPS)

### ISSUE THREAD

**Issue by DanielBallaSZTE** [nodemailer/nodemailer#1323]
Please fill the following questionnaire about your issue:

1. What kind of issue are you reporting?

- [x]  A bug in Nodemailer
- [ ]  A bug in a plugin of Nodemailer (eg. issues with nodemailer-sendgrid)
- [ ]  Feature request
- [ ]  Looking for help to resolve some kind of problem with Nodemailer

2. Are you listed as a sponsor of Nodemailer project (see Sponsors button above)?

- [ ]  Yes. Sponsors get priority support
- [x]  No. Unless it is a bug in Nodemailer you might find support from public forums like StackOverflow.

State your problem here:

Hello,

Recently I've created a script which sends a mail to a user through an SMTP server. The script works just fine on my machine (Windows 10), however, I get an error on Ubuntu 20.04:
```
Error: Invalid login: 535 5.7.8 Error: authentication failed:
    at SMTPConnection._formatError (/root/BookingSystem/backend/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._actionAUTHComplete (/root/BookingSystem/backend/node_modules/nodemailer/lib/smtp-connection/index.js:1536:34)
    at SMTPConnection.<anonymous> (/root/BookingSystem/backend/node_modules/nodemailer/lib/smtp-connection/index.js:540:26)
    at SMTPConnection._processResponse (/root/BookingSystem/backend/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
    at SMTPConnection._onData (/root/BookingSystem/backend/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
    at TLSSocket.SMTPConnection._onSocketData (/root/BookingSystem/backend/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10) {
  code: 'EAUTH',
  response: '535 5.7.8 Error: authentication failed: ',
  responseCode: 535,
  command: 'AUTH PLAIN'
  ```

The script is the exact same, with the exact same login data. I also found two threads on StackOverflow regarding this issue, however none of them got answered. Also seen an issue on this repository having a similar problem, got no answer.
For the records, my script is:

```
const transporter = nodemailer.createTransport({
    host: 'smtp.websupport.sk',
    port: 465,
    secure: true,
    auth: {
        user: 'mylogindata',
        pass: 'mypassword',
    }
});


transporter.verify(function (error, success) {
    if (error) {
      console.log(error);
    } else {
      console.log("Server is ready to take our messages");
    }
});
```

**Comment by andris9** [comment]
If you can log in from one location but not from another then most usually your smtp provider block suspicious logins. Tou’d have to contact your provider and ask for details or whitelisting your server IP
