### ISSUE TITLE
TypeError: Object.values(...).flat is not a function

### ISSUE THREAD

**Issue by seblau** [nodemailer/nodemailer#1330]
Version 6.6.4 leads to the following stack trace

```
/root/workspace/Slide generator/node_modules/nodemailer/lib/shared/index.js:17
        flat().
        ^

TypeError: Object.values(...).flat is not a function
    at resolver (/root/workspace/Slide generator/node_modules/nodemailer/lib/shared/index.js:17:9)
    at Object.module.exports.resolveHostname (/root/workspace/Slide generator/node_modules/nodemailer/lib/shared/index.js:69:5)
    at SMTPConnection.connect (/root/workspace/Slide generator/node_modules/nodemailer/lib/smtp-connection/index.js:293:27)
    at getSocket (/root/workspace/Slide generator/node_modules/nodemailer/lib/smtp-transport/index.js:263:24)
    at Immediate.setImmediate (/root/workspace/Slide generator/node_modules/nodemailer/lib/smtp-transport/index.js:70:35)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by andris9** [comment]
Could you try v6.6.5? The latest changes introduced methods that are not available in Node.js versions 10 or older. These versions of Node are not even maintained anymore but Nodemailer should support every Node version starting from v6 so I used a polyfill function to replace these newer methods in v6.6.5.
