### ISSUE TITLE
500 error when creating transport with test account 

### ISSUE THREAD

**Issue by stephenstuder** [nodemailer/nodemailer#1333]
Very similar issue to the one reported here https://github.com/nodemailer/nodemailer/issues/1140, which looked to be resolved by increasing memory. 

Error: Invalid status code 500
    at ClientRequest.<anonymous> (/Users/sstuder/Development/node-auth/api/node_modules/nodemailer/lib/fetch/index.js:213:23)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:640:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:307:12)
    at readableAddChunk (_stream_readable.js:282:9)
    at TLSSocket.Readable.push (_stream_readable.js:221:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
  type: 'FETCH',
  sourceUrl: 'https://api.nodemailer.com/user'
}

Isolated it in my codebase to the code below, it is unchanged from what was working yesterday. 

```
export async function mailInit() {
  let testAccount = await nodemailer.createTestAccount();

  mail = nodemailer.createTransport({
    host: "smtp.ethereal.email",
    port: 587,
    secure: false,
    auth: {
      user: testAccount.user,
      pass: testAccount.pass,
    },
  });
}

```

**Comment by judsonjuniorr** [comment]
+1

**Comment by vish250491** [comment]
+1

**Comment by Jozwiaczek** [comment]
I think that this time it might be related to ethereal which is currently down. 
I saw in code that `nodemailer.createTestAccount()` under the table uses from default ethereal.

If You enter on [https://ethereal.email/](https://ethereal.email/) and try to create a new account you will get a more specific error message.

![Screenshot 2021-10-02 at 20 07 03](https://user-images.githubusercontent.com/29049653/135727483-cc121712-96ed-43a5-b703-867509887928.png)

**Comment by andris9** [comment]
Well, yeah, happens from time to time. Ethereal.email usage has been going up recently and in the same time my Github sponsorship revenue, that I've used to fund it, has gone down as several higher tier sponsors have ended their pledges, so I haven't been able to upgrade Ethereal servers. Got it working again, so for now it should work though.
