### ISSUE TITLE
Getting Unexpected socket close when using Ethereal

### ISSUE THREAD

**Issue by leungkinghin** [nodemailer/nodemailer#1386]
It started to happen on 4-March and it has not been yet resumed after three days.
Here is a code snippet for the health check.
```
const nodemailer = require("nodemailer");

// async..await is not allowed in global scope, must use a wrapper
async function main() {
    // Generate test SMTP service account from ethereal.email
    // Only needed if you don't have a real mail account for testing
    let testAccount = await nodemailer.createTestAccount();

    // create reusable transporter object using the default SMTP transport
    let transporter = nodemailer.createTransport({
        host: "smtp.ethereal.email",
        port: 587,
        secure: false, // true for 465, false for other ports
        auth: {
            user: <username>, // generated ethereal user
            pass: <password>, // generated ethereal password
        },
    });

    // send mail with defined transport object
    let info = await transporter.sendMail({
        from: '"Fred Foo 👻" <foo@example.com>', // sender address
        to: "kinghin.leung@commercetools.com", // list of receivers
        subject: "Hello ✔", // Subject line
        text: "Hello world?", // plain text body
        html: "<b>Hello world?</b>", // html body
    });

    console.log("Message sent: %s", info.messageId);

    console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));

}

main().catch(console.error);
```

And here is the error message we get
```
Error: Unexpected socket close
    at Timeout._onTimeout (/Users/leungkinghin/Projects/smtp-health-checker/node_modules/nodemailer/lib/smtp-transport/index.js:189:31)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```
May I know when it would be fixed? Thank you.

**Comment by mustafa-shaikh** [comment]
I am also facing the same issue since 5th march 2022.
Is there any solution to this problem?

**Comment by gabrielrsp** [comment]
I'm facing the problem too, and already investigated the problem but still didn't find answers

**Comment by sonipranjal** [comment]
Getting same error :(
```
Error: Unexpected socket close
    at Timeout._onTimeout
    node_modules/nodemailer/lib/smtp-transport/index.js:189:31)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```
I am using AWS SES; it was working 4/5 days ago but suddenly, what happened 🤔

**Comment by sonipranjal** [comment]
Changing my connection to mobile it works, not working on my college wifi.
