### ISSUE TITLE
[bug] A system error occurred: uv_os_gethostname returned ENOSYS

### ISSUE THREAD

**Issue by Bellisario** [nodemailer/nodemailer#1410]
I had this issue while trying to send a mail with a test account (not using a real one for now), I don't know why it occurs but seems (as error logs) `os.hostname()` is not defined and throws an error.

```
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_gethostname returned ENOSYS (function not implemented)
    at SMTPConnection._getHostname (C:\Users\Giorgio\NodeDEV\mail-tracker\node_modules\nodemailer\lib\smtp-connection\index.js:1758:34)
    at new SMTPConnection (C:\Users\Giorgio\NodeDEV\mail-tracker\node_modules\nodemailer\lib\smtp-connection\index.js:64:47)
    at new SMTPTransport (C:\Users\Giorgio\NodeDEV\mail-tracker\node_modules\nodemailer\lib\smtp-transport\index.js:51:26)
    at Object.module.exports.createTransport (C:\Users\Giorgio\NodeDEV\mail-tracker\node_modules\nodemailer\lib\nodemailer.js:49:27)
    at newTestAccount (C:\Users\Giorgio\NodeDEV\mail-tracker\mail.js:83:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: -4054,
    code: 'ENOSYS',
    message: 'function not implemented',
    syscall: 'uv_os_gethostname'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}
```

To solve this issue, I just needed to add a try statement and replace [this line](https://github.com/nodemailer/nodemailer/blob/38e5773826ddc0ab2355557bcd2db38b9e8aac09/lib/smtp-connection/index.js#L1758) with my code:

```js
var defaultHostname = '';
try {
    defaultHostname = os.hostname() || '';
} catch (e) { };
```

**Comment by andris9** [comment]
What platform do you use? What is the version of Node.js and what is the version of Windows and what is the processor type (arm or intel)?

**Comment by andris9** [comment]
If `os.hostname()` is not working at all for you, you can override it, by loading it before you load Nodemailer and then replace the `hostname` method. Something like this:

```js
const os = require('os');
os.hostname = () => 'localhost';

const nodemailer = require('nodemailer');
```

This way, the original `os.hostname()` is never called.

**Comment by Bellisario** [comment]
Thanks for your solution, @andris9.
I've just created and published a patch, so anyone can use it: https://github.com/Bellisario/hostname-patcher

It's explicity made to keep the true hostname if patch is not needed, instead faking it if `os.hostname()` throws an error, so it's safe to use also for who doesn't need it.

To use with Nodemailer:
```js
require('hostname-patcher');

const nodemailer = require('nodemailer');
```

@Noorzafir, this should solve your problem...

**Comment by ChahatL** [comment]
**A system error occurred: uv_os_gethostname returned ENOSYS (function not implemented) - sanity**

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_gethostname returned ENOSYS (function not implemented)
at e.default (C:/node32/node_modules/@sanity/cli/bin/sanity-cli.js:1908:2252)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async C:/node32/node_modules/@sanity/cli/bin/sanity-cli.js:4890:2440
at async e.default (C:/node32/node_modules/@sanity/cli/bin/sanity-cli.js:4890:2315)

_When i try logging into the sanity through vs code terminal, this error shows up.
please tell me how to fix this thing? i'm also using windows 7 platform
can i login through site and connect it with my project manually?_

**Comment by ChahatL** [comment]
> Thanks for your solution, @andris9. I've just created and published a patch, so anyone can use it: https://github.com/Bellisario/hostname-patcher
> 
> It's explicity made to keep the true hostname if patch is not needed, instead faking it if `os.hostname()` throws an error, so it's safe to use also for who doesn't need it.
> 
> To use with Nodemailer:
> 
> ```js
> require('hostname-patcher');
> 
> const nodemailer = require('nodemailer');
> ```
> 
> @Noorzafir, this should solve your problem...

can i use this for sanity?
i have a problem logging in through terminal.

**Comment by Bellisario** [comment]
@ChahatL I don't know "sanity" what it is, but I can clearly say that if you have same problem with it, you just need to install `hostname-patcher` in the package folder and "put" its require upside any other (in the same file there is the problem, obviously). If the problem is `os.hostname()`, you're done...

If you need more help, don't hesitate to create a new Q&A [here](https://github.com/Bellisario/hostname-patcher/discussions/categories/q-a)!

**Comment by tttony** [comment]
> 



> If `os.hostname()` is not working at all for you, you can override it, by loading it before you load Nodemailer and then replace the `hostname` method. Something like this:
> 
> ```js
> const os = require('os');
> os.hostname = () => 'localhost';
> 
> const nodemailer = require('nodemailer');
> ```
> 
> This way, the original `os.hostname()` is never called.



> If `os.hostname()` is not working at all for you, you can override it, by loading it before you load Nodemailer and then replace the `hostname` method. Something like this:
> 
> ```js
> const os = require('os');
> os.hostname = () => 'localhost';
> 
> const nodemailer = require('nodemailer');
> ```
> 
> This way, the original `os.hostname()` is never called.

Thanks! This worked on Window 7 and Node v16.15.1

**Comment by Elendiar** [comment]
Hi, have an issue with this, exploring sources i solved this with manually added name for transport. This is from my code:
```
const transporter = nodemailer.createTransport({
  host,
  port,
  secure: false, // true for 465, false for other ports
  name: getHostname(), // required usage to prevent nodemailer internal call _getHostname() that leads to exception [A system error occurred: uv_os_gethostname returned ENOSYS (function not implemented)] on win7 with electron=^19
});
```
Now you must implement your own getHostname() to return string with hostname value.
Something like:
```
const getHostname = () => {
  const versionMajor = release().split(".")[0];

  if (versionMajor >= 10) return hostname();
 // implement for win7...
  return "hostname";
};
```

**Comment by Bellisario** [comment]
@VivekSalesForce there isn't a real option because this is a problem only of "unsupported" Node.js versions (v.14 and above) in Windows 7. For this Nodemailer team [won't solve this issue](https://github.com/nodemailer/nodemailer/issues/1410#issuecomment-1124005921) and there isn't a real option into the module itself.

To prevent this you can only pass a manual name while creating a transport ([see here](https://github.com/nodemailer/nodemailer/issues/1410#issuecomment-1158803435)) or fix yourself adding the patch code you replied or using my [hostname-patcher](https://github.com/Bellisario/hostname-patcher) (does the same as manual patch, but patches only if needed, better if the code will run not only in your machine).

**Comment by Elendiar** [comment]
> > Если `os.hostname()`у вас вообще не работает, вы можете переопределить его, загрузив его перед загрузкой Nodemailer, а затем заменив `hostname`метод. Что-то вроде этого:
> > ```js
> > const os = require('os');
> > os.hostname = () => 'localhost';
> > 
> > const nodemailer = require('nodemailer');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Таким образом, оригинал `os.hostname()`никогда не вызывается.
> 
> Can you please tell me where to put this code?

This overrides default `os.hostname` call, so you can put it before your main code, that call hostname initialized. But better and more convinient implement your own method, as described in https://github.com/nodemailer/nodemailer/issues/1410#issuecomment-1158803435 and reference him.

**Comment by Both-Eritons** [comment]
> Thanks for your solution, @andris9. I've just created and published a patch, so anyone can use it: https://github.com/Bellisario/hostname-patcher
> 
> It's explicity made to keep the true hostname if patch is not needed, instead faking it if `os.hostname()` throws an error, so it's safe to use also for who doesn't need it.
> 
> To use with Nodemailer:
> 
> ```js
> require('hostname-patcher');
> 
> const nodemailer = require('nodemailer');
> ```
> 
> @Noorzafir, this should solve your problem...

thks, its work!

**Comment by Both-Eritons** [comment]
> If `os.hostname()` is not working at all for you, you can override it, by loading it before you load Nodemailer and then replace the `hostname` method. Something like this:
> 
> ```js
> const os = require('os');
> os.hostname = () => 'localhost';
> 
> const nodemailer = require('nodemailer');
> ```
> 
> This way, the original `os.hostname()` is never called.

thks, its work!

**Comment by andris9** [comment]
The latest versions of Nodemailer already wraps the `hostname()` method in `try..catch` so these fixes are no longer needed.

**Comment by Both-Eritons** [comment]
> As versões mais recentes do Nodemailer já envolvem o `hostname()`método, `try..catch`portanto, essas correções não são mais necessárias.

My problem it's not exactly on nodemailer, I'm also having this problem on: "baileys, expo"

**Comment by Psychosynthesis** [comment]
@Bellisario Hi! I have same problem (Win 7, Node v.16), but with npm (i think so). I got next message:
```
npm notice Log in on https://registry.npmjs.org/
npm ERR! code ERR_SYSTEM_ERROR
npm ERR! syscall uv_os_gethostname
npm ERR! errno -4054
```
When try `npm login`. Is it possible use your hostname-patcher to avoid this? If yes, where i must put `os.hostname = () => 'localhost';`?

**Comment by Bellisario** [comment]
Hello @Psychosynthesis!

I'm not currently on Windows 7 so I can't try if this really works, but I would do this way:

- find where you installed Node.js
- open the `lib` folder, then `node_modules`
- find `npm` folder and open a new terminal window there
- install `hostname-pather` with `npm install hostname-patcher`
- open the `cli.js` file inside the `lib` folder with any code editor
- add the following line at the top of the file `require('hostname-patcher')`

> **Warning**\
> I took all these steps from my Mac Node.js folder and even if the folder/file structure should be the same (excluding the executable which in Windows ends with `.exe` and minor things), all the steps could not match perfectly your installation.\
You should be aware of what you're doing and that editing Node.js files in this way could potentially broke something.

**Comment by alex-sfry** [comment]
If anyone is trying to use vue-cli on windows 7 and getting this error:

1. go to <your_path_to_nodejs>\nodejs\node_global\node_modules\@vue\cli\node_modules\@achrinza\node-ipc\entities\Defaults.js

2. add this: 
const os = require('os');
os.hostname=()=>"localhost";

If you have 1st line already in a file, just add 2nd line.

That's it - error i gone. 
Credits go to some Chinese blogger (https://www.cnblogs.com/leonlipfsj/p/18203145)
