### ISSUE TITLE
Cant read property name

### ISSUE THREAD

**Issue by apeengggg** [nodemailer/nodemailer#1416]
I want to attach file from url using node mailer, 

i try like this : 
```
mailDetails = {
      from: 'info@attachment.com',
      to : req.body.email,
      subject: 'Subject',
      html: content,
      attachments: [{   // utf-8 string as an attachment
        filename: `dhb8n.png`,
        path: 'https://i.stack.imgur.com/dhb8n.png'
      }]
    }
  }

  try {
    await mailTransporter.sendMail(mailDetails, (err, res) => {
      if (err) {
        console.log('errNodeMailer', err)
        res.status(400).send({
          'status': 400,
          'msg': 'Error',
          'error': err
        })
      }
    })

    res.status(200).send({
      'status': 200,
      'msg': 'Email Send Successfully'
    })
  } catch (err) {
    console.log('errSendEmail', err)
    res.status(500).send({
      'status': 500,
      'msg': 'Internal Server Error',
      'error': err
    })
  }
```

and i got error like this: 
```
errNodeMailer TypeError: Cannot read property 'name' of undefined
    at FormData._getContentType (E:\_BSP\_BSPProj\_BIOFARMA-SYMPTOMCHECKER\BE\symptom-checker\sc_sendEmail\node_modules\nodemailer-mailgun-transport\node_modules\form-data\lib\form_data.js:250:29)
    at FormData._multiPartHeader (E:\_BSP\_BSPProj\_BIOFARMA-SYMPTOMCHECKER\BE\symptom-checker\sc_sendEmail\node_modules\nodemailer-mailgun-transport\node_modules\form-data\lib\form_data.js:179:26)
    at FormData.append (E:\_BSP\_BSPProj\_BIOFARMA-SYMPTOMCHECKER\BE\symptom-checker\sc_sendEmail\node_modules\nodemailer-mailgun-transport\node_modules\form-data\lib\form_data.js:71:21)
    at t (E:\_BSP\_BSPProj\_BIOFARMA-SYMPTOMCHECKER\BE\symptom-checker\sc_sendEmail\node_modules\mailgun.js\dist\mailgun.node.js:2:16988)
    at E:\_BSP\_BSPProj\_BIOFARMA-SYMPTOMCHECKER\BE\symptom-checker\sc_sendEmail\node_modules\mailgun.js\dist\mailgun.node.js:2:17175
    at Array.forEach (<anonymous>)
    at E:\_BSP\_BSPProj\_BIOFARMA-SYMPTOMCHECKER\BE\symptom-checker\sc_sendEmail\node_modules\mailgun.js\dist\mailgun.node.js:2:17154
    at Array.reduce (<anonymous>)
    at e.createFormData (E:\_BSP\_BSPProj\_BIOFARMA-SYMPTOMCHECKER\BE\symptom-checker\sc_sendEmail\node_modules\mailgun.js\dist\mailgun.node.js:2:17060)
    at e.postWithFD (E:\_BSP\_BSPProj\_BIOFARMA-SYMPTOMCHECKER\BE\symptom-checker\sc_sendEmail\node_modules\mailgun.js\dist\mailgun.node.js:2:16428)
    at e.create (E:\_BSP\_BSPProj\_BIOFARMA-SYMPTOMCHECKER\BE\symptom-checker\sc_sendEmail\node_modules\mailgun.js\dist\mailgun.node.js:2:12145)
    at mailgunSend (E:\_BSP\_BSPProj\_BIOFARMA-SYMPTOMCHECKER\BE\symptom-checker\sc_sendEmail\node_modules\nodemailer-mailgun-transport\src\index.js:149:40)
    at Object.send (E:\_BSP\_BSPProj\_BIOFARMA-SYMPTOMCHECKER\BE\symptom-checker\sc_sendEmail\node_modules\nodemailer-mailgun-transport\src\index.js:127:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

i dont know how to solve the property name

**Comment by andris9** [comment]
This error seems to be coming from nodemailer-mailgun-transport, not from Nodemailer
