### ISSUE TITLE
Test fails with Node.js >= 18

### ISSUE THREAD

**Issue by guimard** [nodemailer/nodemailer#1436]
Hi,

when trying to rebuild nodemailer with Node.js >= 18, test fails. [Full log available here](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1013994;filename=node-nodemailer_6.7.5%2B~6.4.4-1_amd64-2022-06-28T15%3A07%3A58Z.build;msg=5). Abstract:
```
267 passing (7m)
  24 failing

  1) HTTP Proxy Client Tests
       should connect to a socket through proxy:
     Uncaught TypeError: Cannot set property closed of #<Writable> which has only a getter
      at new SMTPStream (debian/tests/test_modules/smtp-server/lib/smtp-stream.js:34:21)
      at new SMTPConnection (debian/tests/test_modules/smtp-server/lib/smtp-connection.js:55:24)
      at SMTPServer.connect (debian/tests/test_modules/smtp-server/lib/smtp-server.js:112:26)
      at /<<PKGBUILDDIR>>/debian/tests/test_modules/smtp-server/lib/smtp-server.js:100:26
      at Immediate.<anonymous> (debian/tests/test_modules/smtp-server/lib/smtp-server.js:359:39)
      at process.processImmediate (node:internal/timers:471:21)

  2) HTTP Proxy Client Tests
       should connect to a socket through proxy with auth:
     Uncaught Error: listen EADDRINUSE: address already in use :::3129
      at Server.setupListenHandle [as _listen2] (node:net:1416:16)
      at listenInCluster (node:net:1464:12)
      at Server.listen (node:net:1552:7)
      at SMTPServer.listen (debian/tests/test_modules/smtp-server/lib/smtp-server.js:123:28)
      at Context.<anonymous> (test/smtp-connection/http-proxy-client-test.js:46:20)
      at callFnAsync (/usr/share/nodejs/mocha/lib/runnable.js:394:21)
      at Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:338:7)
      at Runner.runTest (/usr/share/nodejs/mocha/lib/runner.js:666:10)
      at /usr/share/nodejs/mocha/lib/runner.js:789:12
      at next (/usr/share/nodejs/mocha/lib/runner.js:581:14)
      at /usr/share/nodejs/mocha/lib/runner.js:591:7
      at next (/usr/share/nodejs/mocha/lib/runner.js:474:14)
      at Immediate.<anonymous> (/usr/share/nodejs/mocha/lib/runner.js:559:5)
      at process.processImmediate (node:internal/timers:471:21)

  3) HTTP Proxy Client Tests
       should should fail auth:
     Uncaught Error: listen EADDRINUSE: address already in use :::3129
      at Server.setupListenHandle [as _listen2] (node:net:1416:16)
      at listenInCluster (node:net:1464:12)
      at Server.listen (node:net:1552:7)
      at SMTPServer.listen (debian/tests/test_modules/smtp-server/lib/smtp-server.js:123:28)
      at Context.<anonymous> (test/smtp-connection/http-proxy-client-test.js:72:20)
      at callFnAsync (/usr/share/nodejs/mocha/lib/runnable.js:394:21)
      at Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:338:7)
      at Runner.runTest (/usr/share/nodejs/mocha/lib/runner.js:666:10)
      at /usr/share/nodejs/mocha/lib/runner.js:789:12
      at next (/usr/share/nodejs/mocha/lib/runner.js:581:14)
      at /usr/share/nodejs/mocha/lib/runner.js:591:7
      at next (/usr/share/nodejs/mocha/lib/runner.js:474:14)
      at Immediate.<anonymous> (/usr/share/nodejs/mocha/lib/runner.js:559:5)
      at process.processImmediate (node:internal/timers:471:21)

  4) SMTP-Connection Tests
       Connection tests
         should connect to unsecure server:
     Uncaught TypeError: Cannot set property closed of #<Writable> which has only a getter
      at new SMTPStream (debian/tests/test_modules/smtp-server/lib/smtp-stream.js:34:21)
      at new SMTPConnection (debian/tests/test_modules/smtp-server/lib/smtp-connection.js:55:24)
      at SMTPServer.connect (debian/tests/test_modules/smtp-server/lib/smtp-server.js:112:26)
      at /<<PKGBUILDDIR>>/debian/tests/test_modules/smtp-server/lib/smtp-server.js:100:26
      at Immediate.<anonymous> (debian/tests/test_modules/smtp-server/lib/smtp-server.js:359:39)
      at process.processImmediate (node:internal/timers:471:21)

  5) SMTP-Connection Tests
       Connection tests
         "after each" hook for "should connect to unsecure server":
     Uncaught AssertionError: expected Error: Greeting never received { …(2) } to not exist
      at Assertion.assertExist (/usr/share/nodejs/chai/lib/chai/core/assertions.js:837:10)
      at Assertion.propertyGetter (/usr/share/nodejs/chai/lib/chai/utils/addProperty.js:62:29)
      at Reflect.get (<anonymous>)
      at Object.proxyGetter [as get] (/usr/share/nodejs/chai/lib/chai/utils/proxify.js:98:22)
      at SMTPConnection.<anonymous> (test/smtp-connection/smtp-connection-test.js:134:35)
      at SMTPConnection.emit (node:events:537:28)
      at SMTPConnection._onError (lib/smtp-connection/index.js:774:14)
      at Timeout.<anonymous> (lib/smtp-connection/index.js:704:22)
      at listOnTimeout (node:internal/timers:564:17)
      at process.processTimers (node:internal/timers:507:7)

  6) SMTP-Connection Tests
       Login tests
         "before each" hook for "should login":
     Uncaught TypeError: Cannot set property closed of #<Writable> which has only a getter
      at new SMTPStream (debian/tests/test_modules/smtp-server/lib/smtp-stream.js:34:21)
      at new SMTPConnection (debian/tests/test_modules/smtp-server/lib/smtp-connection.js:55:24)
      at SMTPServer.connect (debian/tests/test_modules/smtp-server/lib/smtp-server.js:112:26)
      at /<<PKGBUILDDIR>>/debian/tests/test_modules/smtp-server/lib/smtp-server.js:100:26
      at Immediate.<anonymous> (debian/tests/test_modules/smtp-server/lib/smtp-server.js:359:39)
      at process.processImmediate (node:internal/timers:471:21)

  7) SMTP Pool Tests
       should send mail:
     Uncaught TypeError: Cannot set property closed of #<Writable> which has only a getter
      at new SMTPStream (debian/tests/test_modules/smtp-server/lib/smtp-stream.js:34:21)
      at new SMTPConnection (debian/tests/test_modules/smtp-server/lib/smtp-connection.js:55:24)
      at SMTPServer.connect (debian/tests/test_modules/smtp-server/lib/smtp-server.js:112:26)
      at /<<PKGBUILDDIR>>/debian/tests/test_modules/smtp-server/lib/smtp-server.js:100:26
      at Immediate.<anonymous> (debian/tests/test_modules/smtp-server/lib/smtp-server.js:359:39)
      at process.processImmediate (node:internal/timers:471:21)

  8) SMTP Pool Tests
       should send multiple mails:
     Uncaught TypeError: Cannot set property closed of #<Writable> which has only a getter
      at new SMTPStream (debian/tests/test_modules/smtp-server/lib/smtp-stream.js:34:21)
      at new SMTPConnection (debian/tests/test_modules/smtp-server/lib/smtp-connection.js:55:24)
      at SMTPServer.connect (debian/tests/test_modules/smtp-server/lib/smtp-server.js:112:26)
      at /<<PKGBUILDDIR>>/debian/tests/test_modules/smtp-server/lib/smtp-server.js:100:26
      at Immediate.<anonymous> (debian/tests/test_modules/smtp-server/lib/smtp-server.js:359:39)
      at process.processImmediate (node:internal/timers:471:21)

  9) SMTP Pool Tests
       should tolerate connection errors:
     Uncaught TypeError: Cannot set property closed of #<Writable> which has only a getter
      at new SMTPStream (debian/tests/test_modules/smtp-server/lib/smtp-stream.js:34:21)
      at new SMTPConnection (debian/tests/test_modules/smtp-server/lib/smtp-connection.js:55:24)
      at SMTPServer.connect (debian/tests/test_modules/smtp-server/lib/smtp-server.js:112:26)
      at /<<PKGBUILDDIR>>/debian/tests/test_modules/smtp-server/lib/smtp-server.js:100:26
      at Immediate.<anonymous> (debian/tests/test_modules/smtp-server/lib/smtp-server.js:359:39)
      at process.processImmediate (node:internal/timers:471:21)

  10) SMTP Pool Tests
       should tolerate idle connections and re-assign messages to other connections:
     Uncaught TypeError: Cannot set property closed of #<Writable> which has only a getter
      at new SMTPStream (debian/tests/test_modules/smtp-server/lib/smtp-stream.js:34:21)
      at new SMTPConnection (debian/tests/test_modules/smtp-server/lib/smtp-connection.js:55:24)
      at SMTPServer.connect (debian/tests/test_modules/smtp-server/lib/smtp-server.js:112:26)
      at /<<PKGBUILDDIR>>/debian/tests/test_modules/smtp-server/lib/smtp-server.js:100:26
      at Immediate.<anonymous> (debian/tests/test_modules/smtp-server/lib/smtp-server.js:359:39)
      at process.processImmediate (node:internal/timers:471:21)

  11) SMTP Pool Tests
       should call back with connection errors to senders having messages in flight:
     Uncaught TypeError: Cannot set property closed of #<Writable> which has only a getter
      at new SMTPStream (debian/tests/test_modules/smtp-server/lib/smtp-stream.js:34:21)
      at new SMTPConnection (debian/tests/test_modules/smtp-server/lib/smtp-connection.js:55:24)
      at SMTPServer.connect (debian/tests/test_modules/smtp-server/lib/smtp-server.js:112:26)
      at /<<PKGBUILDDIR>>/debian/tests/test_modules/smtp-server/lib/smtp-server.js:100:26
      at Immediate.<anonymous> (debian/tests/test_modules/smtp-server/lib/smtp-server.js:359:39)
      at process.processImmediate (node:internal/timers:471:21)

  12) SMTP Pool Tests
       should not send more then allowed for one connection:
     Uncaught TypeError: Cannot set property closed of #<Writable> which has only a getter
      at new SMTPStream (debian/tests/test_modules/smtp-server/lib/smtp-stream.js:34:21)
      at new SMTPConnection (debian/tests/test_modules/smtp-server/lib/smtp-connection.js:55:24)
      at SMTPServer.connect (debian/tests/test_modules/smtp-server/lib/smtp-server.js:112:26)
      at /<<PKGBUILDDIR>>/debian/tests/test_modules/smtp-server/lib/smtp-server.js:100:26
      at Immediate.<anonymous> (debian/tests/test_modules/smtp-server/lib/smtp-server.js:359:39)
      at process.processImmediate (node:internal/timers:471:21)

  13) SMTP Pool Tests
       should call back with connection errors to senders having messages in flight:
     Error: done() called multiple times in test <SMTP Pool Tests should call back with connection errors to senders having messages in flight> of file /<<PKGBUILDDIR>>/test/smtp-pool/smtp-pool-test.js
      at createMultipleDoneError (/usr/share/nodejs/mocha/lib/errors.js:428:13)
      at multiple (/usr/share/nodejs/mocha/lib/runnable.js:290:24)
      at done (/usr/share/nodejs/mocha/lib/runnable.js:301:14)
      at /usr/share/nodejs/mocha/lib/runnable.js:414:7
      at Object.callback (test/smtp-pool/smtp-pool-test.js:408:17)
      at PoolResource.<anonymous> (lib/smtp-pool/index.js:358:43)
      at Object.onceWrapper (node:events:652:26)
      at PoolResource.emit (node:events:537:28)
      at SMTPConnection.<anonymous> (lib/smtp-pool/pool-resource.js:100:22)
      at Object.onceWrapper (node:events:652:26)
      at SMTPConnection.emit (node:events:537:28)
      at SMTPConnection._onError (lib/smtp-connection/index.js:774:14)
      at SMTPConnection._onSocketError (lib/smtp-connection/index.js:190:45)
      at Socket.emit (node:events:537:28)
      at emitErrorNT (node:internal/streams/destroy:151:8)
      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

  14) SMTP Pool Tests
       should send multiple mails with rate limit:
     Uncaught TypeError: Cannot set property closed of #<Writable> which has only a getter
      at new SMTPStream (debian/tests/test_modules/smtp-server/lib/smtp-stream.js:34:21)
      at new SMTPConnection (debian/tests/test_modules/smtp-server/lib/smtp-connection.js:55:24)
      at SMTPServer.connect (debian/tests/test_modules/smtp-server/lib/smtp-server.js:112:26)
      at /<<PKGBUILDDIR>>/debian/tests/test_modules/smtp-server/lib/smtp-server.js:100:26
      at Immediate.<anonymous> (debian/tests/test_modules/smtp-server/lib/smtp-server.js:359:39)
      at process.processImmediate (node:internal/timers:471:21)

  15) SMTP Pool Tests
       should emit idle for free slots in the pool:
     Uncaught TypeError: Cannot set property closed of #<Writable> which has only a getter
      at new SMTPStream (debian/tests/test_modules/smtp-server/lib/smtp-stream.js:34:21)
      at new SMTPConnection (debian/tests/test_modules/smtp-server/lib/smtp-connection.js:55:24)
      at SMTPServer.connect (debian/tests/test_modules/smtp-server/lib/smtp-server.js:112:26)
      at /<<PKGBUILDDIR>>/debian/tests/test_modules/smtp-server/lib/smtp-server.js:100:26
      at Immediate.<anonymous> (debian/tests/test_modules/smtp-server/lib/smtp-server.js:359:39)
      at process.processImmediate (node:internal/timers:471:21)

  16) SMTP Pool Tests
       Should login and send mail using proxied socket:
     Uncaught TypeError: Cannot set property closed of #<Writable> which has only a getter
      at new SMTPStream (debian/tests/test_modules/smtp-server/lib/smtp-stream.js:34:21)
      at new SMTPConnection (debian/tests/test_modules/smtp-server/lib/smtp-connection.js:55:24)
      at SMTPServer.connect (debian/tests/test_modules/smtp-server/lib/smtp-server.js:112:26)
      at /<<PKGBUILDDIR>>/debian/tests/test_modules/smtp-server/lib/smtp-server.js:100:26
      at Immediate.<anonymous> (debian/tests/test_modules/smtp-server/lib/smtp-server.js:359:39)
      at process.processImmediate (node:internal/timers:471:21)

  17) SMTP Pool Tests
       should emit idle for free slots in the pool:
     Error: done() called multiple times in test <SMTP Pool Tests should emit idle for free slots in the pool> of file /<<PKGBUILDDIR>>/test/smtp-pool/smtp-pool-test.js
      at createMultipleDoneError (/usr/share/nodejs/mocha/lib/errors.js:428:13)
      at multiple (/usr/share/nodejs/mocha/lib/runnable.js:290:24)
      at done (/usr/share/nodejs/mocha/lib/runnable.js:301:14)
      at /usr/share/nodejs/mocha/lib/runnable.js:414:7
      at Object.cb [as callback] (test/smtp-pool/smtp-pool-test.js:617:24)
      at PoolResource.<anonymous> (lib/smtp-pool/index.js:358:43)
      at Object.onceWrapper (node:events:652:26)
      at PoolResource.emit (node:events:537:28)
      at SMTPConnection.<anonymous> (lib/smtp-pool/pool-resource.js:100:22)
      at Object.onceWrapper (node:events:652:26)
      at SMTPConnection.emit (node:events:537:28)
      at SMTPConnection._onError (lib/smtp-connection/index.js:774:14)
      at SMTPConnection._onSocketError (lib/smtp-connection/index.js:190:45)
      at Socket.emit (node:events:537:28)
      at emitErrorNT (node:internal/streams/destroy:151:8)
      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

  18) SMTP Pool Tests
       Should verify connection with success:
     Uncaught TypeError: Cannot set property closed of #<Writable> which has only a getter
      at new SMTPStream (debian/tests/test_modules/smtp-server/lib/smtp-stream.js:34:21)
      at new SMTPConnection (debian/tests/test_modules/smtp-server/lib/smtp-connection.js:55:24)
      at SMTPServer.connect (debian/tests/test_modules/smtp-server/lib/smtp-server.js:112:26)
      at /<<PKGBUILDDIR>>/debian/tests/test_modules/smtp-server/lib/smtp-server.js:100:26
      at Immediate.<anonymous> (debian/tests/test_modules/smtp-server/lib/smtp-server.js:359:39)
      at process.processImmediate (node:internal/timers:471:21)

  19) SMTP Pool Tests
       "after each" hook for "Should verify connection with success":
     Uncaught AssertionError: expected Error: Greeting never received { …(2) } to not exist
      at Assertion.assertExist (/usr/share/nodejs/chai/lib/chai/core/assertions.js:837:10)
      at Assertion.propertyGetter (/usr/share/nodejs/chai/lib/chai/utils/addProperty.js:62:29)
      at Object.proxyGetter [as get] (/usr/share/nodejs/chai/lib/chai/utils/proxify.js:98:22)
      at /<<PKGBUILDDIR>>/test/smtp-pool/smtp-pool-test.js:699:31
      at SMTPConnection.<anonymous> (lib/smtp-pool/index.js:591:24)
      at Object.onceWrapper (node:events:652:26)
      at SMTPConnection.emit (node:events:537:28)
      at SMTPConnection._onError (lib/smtp-connection/index.js:774:14)
      at Timeout.<anonymous> (lib/smtp-connection/index.js:704:22)
      at listOnTimeout (node:internal/timers:564:17)
      at process.processTimers (node:internal/timers:507:7)

  20) SMTP Pool Tests
       "after each" hook for "Should verify connection with success":
     Error: done() called multiple times in hook <SMTP Pool Tests "after each" hook for "Should verify connection with success"> of file /<<PKGBUILDDIR>>/test/smtp-pool/smtp-pool-test.js
      at createMultipleDoneError (/usr/share/nodejs/mocha/lib/errors.js:428:13)
      at multiple (/usr/share/nodejs/mocha/lib/runnable.js:290:24)
      at done (/usr/share/nodejs/mocha/lib/runnable.js:301:14)
      at /usr/share/nodejs/mocha/lib/runnable.js:414:7
      at Server.<anonymous> (debian/tests/test_modules/smtp-server/lib/smtp-server.js:139:24)
      at Object.onceWrapper (node:events:651:28)
      at Server.emit (node:events:549:35)
      at emitCloseNT (node:net:1773:8)
      at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

  21) SMTP Transport Tests
       Anonymous sender tests
         Should fail envelope:
     Uncaught TypeError: Cannot set property closed of #<Writable> which has only a getter
      at new SMTPStream (debian/tests/test_modules/smtp-server/lib/smtp-stream.js:34:21)
      at new SMTPConnection (debian/tests/test_modules/smtp-server/lib/smtp-connection.js:55:24)
      at SMTPServer.connect (debian/tests/test_modules/smtp-server/lib/smtp-server.js:112:26)
      at /<<PKGBUILDDIR>>/debian/tests/test_modules/smtp-server/lib/smtp-server.js:100:26
      at Immediate.<anonymous> (debian/tests/test_modules/smtp-server/lib/smtp-server.js:359:39)
      at process.processImmediate (node:internal/timers:471:21)

  22) SMTP Transport Tests
       Anonymous sender tests
         "after each" hook for "Should fail envelope":
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/<<PKGBUILDDIR>>/test/smtp-transport/smtp-tranport-test.js)
      at createTimeoutError (/usr/share/nodejs/mocha/lib/errors.js:498:15)
      at Runnable._timeoutError (/usr/share/nodejs/mocha/lib/runnable.js:431:10)
      at Timeout.<anonymous> (/usr/share/nodejs/mocha/lib/runnable.js:246:24)
      at listOnTimeout (node:internal/timers:564:17)
      at process.processTimers (node:internal/timers:507:7)

  23) SMTP Transport Tests
       Authenticated sender tests
         Should login and send mail:
     Uncaught TypeError: Cannot set property closed of #<Writable> which has only a getter
      at new SMTPStream (debian/tests/test_modules/smtp-server/lib/smtp-stream.js:34:21)
      at new SMTPConnection (debian/tests/test_modules/smtp-server/lib/smtp-connection.js:55:24)
      at SMTPServer.connect (debian/tests/test_modules/smtp-server/lib/smtp-server.js:112:26)
      at /<<PKGBUILDDIR>>/debian/tests/test_modules/smtp-server/lib/smtp-server.js:100:26
      at Immediate.<anonymous> (debian/tests/test_modules/smtp-server/lib/smtp-server.js:359:39)
      at process.processImmediate (node:internal/timers:471:21)

  24) SMTP Transport Tests
       Authenticated sender tests
         "after each" hook for "Should login and send mail":
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/<<PKGBUILDDIR>>/test/smtp-transport/smtp-tranport-test.js)
      at createTimeoutError (/usr/share/nodejs/mocha/lib/errors.js:498:15)
      at Runnable._timeoutError (/usr/share/nodejs/mocha/lib/runnable.js:431:10)
      at Timeout.<anonymous> (/usr/share/nodejs/mocha/lib/runnable.js:246:24)
      at listOnTimeout (node:internal/timers:564:17)
      at process.processTimers (node:internal/timers:507:7)




/usr/share/nodejs/mocha/lib/runner.js:950
    throw err;
    ^
AssertionError: expected 'ETIMEDOUT' to equal 'EENVELOPE'
    at Proxy.assertEqual (/usr/share/nodejs/chai/lib/chai/core/assertions.js:1038:12)
    at Proxy.methodWrapper (/usr/share/nodejs/chai/lib/chai/utils/addMethod.js:57:25)
    at /<<PKGBUILDDIR>>/test/smtp-transport/smtp-tranport-test.js:149:41
    at SMTPConnection.<anonymous> (/<<PKGBUILDDIR>>/lib/smtp-transport/index.js:175:24)
    at Object.onceWrapper (node:events:652:26)
    at SMTPConnection.emit (node:events:537:28)
    at SMTPConnection._onError (/<<PKGBUILDDIR>>/lib/smtp-connection/index.js:774:14)
    at Timeout.<anonymous> (/<<PKGBUILDDIR>>/lib/smtp-connection/index.js:704:22)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7) {
  showDiff: true,
  actual: 'ETIMEDOUT',
  expected: 'EENVELOPE',
  operator: 'strictEqual'
}

Node.js v18.4.0
```

**Comment by guimard** [comment]
False positive, error on my side
