### ISSUE TITLE
Missing start boundary with ses transporter

### ISSUE THREAD

**Issue by cesco69** [nodemailer/nodemailer#1440]
```ts
        import * as SES from 'aws-sdk/clients/ses';
        import * as nodemailer from 'nodemailer';

        const transporter = nodemailer.createTransport({SES: new SES({
            accessKeyId: 'XXXX',
            secretAccessKey: 'XXXX',
            region: 'XXXX',
        })});
        transporter.sendMail({
            from: 'test-from@test.it',
            to: 'test-to@test.it',
            attachments: [{
                filename: 'attachment.zip',
                content: file // internal.Readable from busboy upload
            }],
            subject: 'test',
            html: 'test'
        });
```

error:

```
InvalidParameterValue: Missing start boundary
    at Request.extractError (/opt/backend/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/opt/backend/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/opt/backend/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/opt/backend/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/opt/backend/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/backend/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /opt/backend/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/opt/backend/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/opt/backend/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/opt/backend/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

libs

```json
{
  "nodemailer": "^6.7.6",
  "aws-sdk": "^2.1167.0"
}
```

**Comment by topbestcoder** [comment]
It looks like the emails have been all deleted... We can create a new one but I have not tested if the emails are received....
And the status page cannot be displayed because of an invalid certificate.
I sent an email to the admin but he still not replied...
