### ISSUE TITLE
Issue with Gmail using 3-legged OAuth2 authentication

### ISSUE THREAD

**Issue by olhapi** [nodemailer/nodemailer#1445]
I'm using OAuth2 with gmail and getting `Error: Invalid login: 535-5.7.8 Username and Password not accepted.` despite the fact that new access token was successfully generated, the scope was set correctly and everything was done like described here: https://nodemailer.com/smtp/oauth2/#oauth-3lo

I'd rather use another provider, but sending emails from behalf of the user is basically the whole point of the app 😁

Here's full debug log: 

```
[2022-07-19 19:02:00] DEBUG Sending mail using SMTP/6.7.7[client:6.7.7]
[2022-07-19 19:02:00] DEBUG [QKrWwm10XWQ] Resolved smtp.gmail.com as 108.177.126.109 [cache miss]
[2022-07-19 19:02:00] INFO  [QKrWwm10XWQ] Secure connection established to 108.177.126.109:465
[2022-07-19 19:02:00] DEBUG [QKrWwm10XWQ] SMTP handshake finished
[2022-07-19 19:02:00] DEBUG Requesting token using: {"client_id":"69644943908-ttt.apps.googleusercontent.com","client_secret":"GOCSPX...","refresh_token":"1//0c4...","grant_type":"refresh_token"}
[2022-07-19 19:02:00] DEBUG Response: {"access_token":"ya29.A...","expires_in":3599,"scope":"https://www.googleapis.com/auth/calendar.app.created https://www.googleapis.com/auth/gmail.labels openid https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/gmail.modify","token_type":"Bearer","id_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjA3NGI5MjhlZGY2NWE2ZjQ3MGM3MWIwYTI0N2JkMGY3YTRjOWNjYmMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXpwIjoiNjk2NDQ5NDM5MDgtdGhyOTI2YmFlaTJrNmFudWcwbjE0ZTFlMXR0OGY3Y2UuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI2OTY0NDk0MzkwOC10aHI5MjZiYWVpMms2YW51ZzBuMTRlMWUxdHQ4ZjdjZS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjEwODMzMTM3NjAxMzM3MzU1ODY5NyIsImVtYWlsIjoib2xlZy5vbGhhcGlAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF0X2hhc2giOiJiRGFoV1hvTlEzMlpUTDdnV1Q2UlhBIiwiaWF0IjoxNjU4MjU3MzE5LCJleHAiOjE2NTgyNjA5MTl9.g0AwRBew0q8_WmSFXxee8KnaKZlWIFNb8Ju36HH6VQN2m9H8EkiyBIQ7SemJMFg-kSoRuaKJczkrY-JU70tIAv14oE0t2munDQfUssURPvDOFZvhm0n-I3tHOUCCBw4e1_TgCoXBUxIX8f6JBsALBGnlBihS8Y78fNgexPPK-UGAi3goWd3pk94MrxzsyWp3cStuzTnDdkT-1CO1VOR5siEN9yvJnHcRHtCEEPtc2YDL89S7agnkV8WIH6nFdWp6QgJmAlPSkWI9xGxVBRzMhESHUliz4eiokmDy_0GhRCwJepm91fb9eX-Z5e9DI8FDcgYy8_EPEB-6Jc36ebNHkw"}
[2022-07-19 19:02:00] INFO  Generated new Access Token for olhapi@gmail.com
[2022-07-19 19:02:00] INFO  [QKrWwm10XWQ] User "olhapi@gmail.com" failed to authenticate
[2022-07-19 19:02:00] DEBUG [QKrWwm10XWQ] Closing connection to the server using "end"
[2022-07-19 19:02:00] ERROR Send Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
[2022-07-19 19:02:00] ERROR 535 5.7.8  https://support.google.com/mail/?p=BadCredentials k10-20020aa7d2ca000000b0043a6b86f024sm10934032edr.67 - gsmtp
[Nest] 24288  - 19.07.2022, 22:02:00   ERROR [SequencesService] Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials k10-20020aa7d2ca000000b0043a6b86f024sm10934032edr.67 - gsmtp
[Nest] 24288  - 19.07.2022, 22:02:00   ERROR [ExceptionsHandler] Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials k10-20020aa7d2ca000000b0043a6b86f024sm10934032edr.67 - gsmtp
Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials k10-20020aa7d2ca000000b0043a6b86f024sm10934032edr.67 - gsmtp
    at SMTPConnection._formatError (C:\Users\user\project\drip\backend\node_modules\nodemailer\lib\smtp-connection\index.js:787:19)
    at SMTPConnection._actionAUTHComplete (C:\Users\user\project\drip\backend\node_modules\nodemailer\lib\smtp-connection\index.js:1539:34)
    at SMTPConnection.<anonymous> (C:\Users\user\project\drip\backend\node_modules\nodemailer\lib\smtp-connection\index.js:1518:26)
    at SMTPConnection._processResponse (C:\Users\user\project\drip\backend\node_modules\nodemailer\lib\smtp-connection\index.js:950:20)
    at SMTPConnection._onData (C:\Users\user\project\drip\backend\node_modules\nodemailer\lib\smtp-connection\index.js:752:14)
    at TLSSocket.SMTPConnection._onSocketData (C:\Users\user\project\drip\backend\node_modules\nodemailer\lib\smtp-connection\index.js:191:44)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
[2022-07-19 19:02:00] INFO  [QKrWwm10XWQ] Connection closed
```

**Comment by andris9** [comment]
Nodemailer requires a single scope: `"https://mail.google.com/"`

**Comment by andris9** [comment]
I’ve written this tutorial for EmailEngine but it applies to Nodemailer as well: https://docs.emailengine.app/setting-up-gmail-oauth2-for-imap-api/amp/

**Comment by olhapi** [comment]
@andris9 thanks mate. I forgot to app the scope in both places (google cloud console and nodejs server) 😣

Have a nice day!
