### ISSUE TITLE
setImmediate is not defined

### ISSUE THREAD

**Issue by ViolaterZ** [nodemailer/nodemailer#1453]
Hi,

Recently i have been facing an issue with nodemailer. It always throws an error like this
`index.js:71 Uncaught ReferenceError: setImmediate is not defined
    at SMTPTransport.getSocket (index.js:71:9)
    at SMTPTransport.send (index.js:137:14)
    at index.js:218:34
    at Mail._processPlugins (index.js:266:20)
    at index.js:188:18
    at processPlugins (index.js:279:28)
    at index.js:287:17
    at Mail._convertDataImages (index.js:391:20)
    at Mail._defaultPlugins.compile (index.js:31:41)
    at processPlugins (index.js:283:13)`

I don't know what to do at this point. I have tried every single possible solution.
And I am using parcel.js as my compiler for node js (If that's the cause of the issue).
I hope you respond soon, thank you.

**Comment by AttractMore** [comment]
I am having exactly the same issue. I have also tried a variety of options but no luck. I am also using Parcel
