### ISSUE TITLE
Error Connecting to SMTP server

### ISSUE THREAD

**Issue by janheinvanasseldonk** [nodemailer/nodemailer#1547]
Hi, here's my code

```
"use strict";
const nodemailer = require("nodemailer");

// async..await is not allowed in global scope, must use a wrapper
async function main() {
  // Generate test SMTP service account from ethereal.email
  // Only needed if you don't have a real mail account for testing
  let testAccount = await nodemailer.createTestAccount();

  // create reusable transporter object using the default SMTP transport
  let transporter = nodemailer.createTransport({
    host: "smtp.ethereal.email",
    port: 587,
    secure: false, // true for 465, false for other ports
    auth: {
      user: testAccount.user, // generated ethereal user
      pass: testAccount.pass, // generated ethereal password
    },
  });

  // send mail with defined transport object
  let info = await transporter.sendMail({
    from: '"Fred Foo 👻" <foo@example.com>', // sender address
    to: "zullubalti@gmail.com", // list of receivers
    subject: "Hello ✔", // Subject line
    text: "Hello world?", // plain text body
    html: "<b>Hello world?</b>", // html body
  });

  console.log("Message sent: %s", info.messageId);
  // Message sent: <b658f8ca-6296-ccf4-8306-87d57a0b4321@example.com>

  // Preview only available when sending through an Ethereal account
  console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));
  // Preview URL: https://ethereal.email/message/WaQKMgKddxQDoou...
}

main().catch(console.error);
```

And here's the error that I'm getting
```
Error: Connection timeout 
    at SMTPConnection._formatError (/home/zullu/test/node_modules/nodemailer/lib/smtp-connection/index.js:790:19) 
    at SMTPConnection._onError (/home/zullu/test/node_modules/nodemailer/lib/smtp-connection/index.js:776:20) 
    at Timeout.<anonymous> (/home/zullu/test/node_modules/nodemailer/lib/smtp-connection/index.js:235:22) 
    at listOnTimeout (node:internal/timers:573:17) 
    at process.processTimers (node:internal/timers:514:7) { 
  code: 'ETIMEDOUT', 
  command: 'CONN' 
} 
```

I've tried different SMTP server but I'm getting the same error the only server that works is gmail. When I use gmail smtp it works fine

**Comment by janheinvanasseldonk** [comment]
The issue was I guess with my ISP as when I do it with a VPN it works now and also It's working in live version.
