### ISSUE TITLE
accessUrl error - google oauth2 v2

### ISSUE THREAD

**Issue by lien-dkseo** [nodemailer/nodemailer#1549]
Please file only reproducible bugs. Everything else will get ignored.

See the FAQ for existing known issues [here](https://github.com/nodemailer/nodemailer#having-an-issue) before you submit a new one.

```ts
createTransport({
      host: 'smtp.gmail.com',
      port: 465,
      secure: true,
      auth: {
        type: 'OAuth2',
...
...
        accessUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      },
    });
```

- set `accessUrl: 'https://accounts.google.com/o/oauth2/v2/auth',` error
```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at d:\dev\lien\2023-ncc-backend\node_modules\nodemailer\lib\xoauth2\index.js:226:29
    at PassThrough.<anonymous> (d:\dev\lien\2023-ncc-backend\node_modules\nodemailer\lib\xoauth2\index.js:341:20)
    at Object.onceWrapper (d:\dev\lien\2023-ncc-backend\lib\events.js:627:28)
    at PassThrough.emit (d:\dev\lien\2023-ncc-backend\lib\events.js:513:28)
    at endReadableNT (d:\dev\lien\2023-ncc-backend\lib\internal\streams\readable.js:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {code: 'EAUTH', command: 'AUTH XOAUTH2', stack: 'SyntaxError: Unexpected token < in JSON at po…ons (node:internal/process/task_queues:82:21)', message: 'Unexpected token < in JSON at position 0'}
```

**Comment by lien-dkseo** [comment]
to `accessUrl: 'https://oauth2.googleapis.com/token',`
