### ISSUE TITLE
Error: Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by shirish87** [nodemailer/nodemailer#158]
Just did an npm install and got v0.4.4. 

Now, I get the following exception with Node v0.10.7 while sending e-mails using a private SMTP server (secureConnection: false, port: 587, and auth.user and pass supplied).

```
Error: Hostname/IP doesn't match certificate's altnames,
    at SecurePair.<anonymous> (tls.js:1292:23),
    at SecurePair.EventEmitter.emit (events.js:92:17),
    at SecurePair.maybeInitFinished (tls.js:896:10),
    at CleartextStream.read [as _read] (tls.js:430:15),
    at CleartextStream.Readable.read (_stream_readable.js:320:10),
    at EncryptedStream.write [as _write] (tls.js:344:25),
    at doWrite (_stream_writable.js:219:10),
    at writeOrBuffer (_stream_writable.js:209:5),
    at EncryptedStream.Writable.write (_stream_writable.js:180:11),
    at Socket.ondata (stream.js:51:26)]
```

I was using Nodemailer v0.4.2, and that still works fine. :)

Thanks.

**Comment by bodycheetah** [comment]
Had same problem sending from an Express app until I added this to the app.js code  ...
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
