### ISSUE TITLE
500 Internal Server Error: TypeError

### ISSUE THREAD

**Issue by Salvatore-tech** [nodemailer/nodemailer#1598]
Hello there, 
In my Sveltekit project i'm trying to use nodemailer with the snippet from the example configuration to send a mail, however i got an internal server error that i attach below. 
Any clues?
Version: 
- "nodemailer": "^6.9.7",
- "@types/nodemailer": "^6.4.14",

TypeError: Class extends value undefined is not a constructor or null
    at node_modules/nodemailer/lib/base64/index.js (index.js:56:1)
    at __require (chunk-LXYNHJXE.js?v=9c08dd2b:10:50)
    at node_modules/nodemailer/lib/mime-funcs/index.js (index.js:5:16)
    at __require (chunk-LXYNHJXE.js?v=9c08dd2b:10:50)
    at node_modules/nodemailer/lib/mime-node/index.js (index.js:11:19)
    at __require (chunk-LXYNHJXE.js?v=9c08dd2b:10:50)
    at node_modules/nodemailer/lib/mail-composer/index.js (index.js:5:18)
    at __require (chunk-LXYNHJXE.js?v=9c08dd2b:10:50)
    at node_modules/nodemailer/lib/mailer/index.js (index.js:6:22)
    at __require (chunk-LXYNHJXE.js?v=9c08dd2b:10:50)

**Comment by Withorcool** [comment]
i have same issue

**Comment by Salvatore-tech** [comment]
@Withorcool i'm closing the issue since i found the solution. Basically, in Svelte the code can be executed both in the server and in the client. If you want to use nodemailer you need to be sure that you are on the server side. In my case i moved the logic inside an API endpoint in a +server.ts file and it works.
