### ISSUE TITLE
Error while send emailError: Connection closed unexpectedly with smtp

### ISSUE THREAD

**Issue by MiniKrishna** [nodemailer/nodemailer#1610]
Hi, I'm trying to send a letter using an smtp connection, my mail server uses IP authentication, so I wrote an authentication where nothing is happen and added my IP address to the name field, but an error occurs when sending a message after 5 minutes, I am attaching the code and log.

"nodemailer": "^6.9.7",
port - 25

```      
      const transporter = nodemailer.createTransport({
        host,
        port,
        secure: port === 465, 
        tls: {
          // do not fail on invalid certs
          rejectUnauthorized: false,
        },
        auth: {
          type: 'custom',
          method: 'MY-CUSTOM-METHOD', 
          user: 'custom',
          pass: 'custom',
        },
        customAuth: {
          'MY-CUSTOM-METHOD': ctx => {
            console.log('Custom auth');
          },
        },
        debug: true,
        logger: true,
        name: '******',
      });
      const info = await transporter.sendMail({
        from: senderAddress, // sender address
        to: email.address,
        subject: email.subject, // Subject line
        html: email.htmlText, // plain text body
      });
      return info;
```

```
 [2023-12-14 12:52:19] DEBUG Sending mail using SMTP/6.9.7[client:6.9.7]
 [2023-12-14 12:52:19] DEBUG [9A1nYKdAgxg] Resolved smtp-server as **** [cache miss]
 [2023-12-14 12:52:19] INFO  [9A1nYKdAgxg] Connection established to *****
 [2023-12-14 12:52:19] DEBUG [9A1nYKdAgxg] S: 220 smtp-server ESMTP CommuniGate Pro 6.3.18 is glad to see you!
 [2023-12-14 12:52:19] DEBUG [9A1nYKdAgxg] C: EHLO **my-ip**
 [2023-12-14 12:52:19] DEBUG [9A1nYKdAgxg] S: 250-smtp-server is pleased to meet you
 [2023-12-14 12:52:19] DEBUG [9A1nYKdAgxg] S: 250-DSN
 [2023-12-14 12:52:19] DEBUG [9A1nYKdAgxg] S: 250-SIZE
 [2023-12-14 12:52:19] DEBUG [9A1nYKdAgxg] S: 250-AUTH LOGIN PLAIN CRAM-MD5 DIGEST-MD5
 [2023-12-14 12:52:19] DEBUG [9A1nYKdAgxg] S: 250-ETRN
 [2023-12-14 12:52:19] DEBUG [9A1nYKdAgxg] S: 250-TURN
 [2023-12-14 12:52:19] DEBUG [9A1nYKdAgxg] S: 250-ATRN
 [2023-12-14 12:52:19] DEBUG [9A1nYKdAgxg] S: 250-NO-SOLICITING
 [2023-12-14 12:52:19] DEBUG [9A1nYKdAgxg] S: 250-HELP
 [2023-12-14 12:52:19] DEBUG [9A1nYKdAgxg] S: 250-PIPELINING
 [2023-12-14 12:52:19] DEBUG [9A1nYKdAgxg] S: 250-SMTPUTF8
 [2023-12-14 12:52:19] DEBUG [9A1nYKdAgxg] S: 250 EHLO
 [2023-12-14 12:52:19] DEBUG [9A1nYKdAgxg] SMTP handshake finished
 Custom auth
 [2023-12-14 12:57:19] INFO  [9A1nYKdAgxg] Connection closed
 [2023-12-14 12:57:19] ERROR [9A1nYKdAgxg] Connection closed unexpectedly
 [2023-12-14 12:57:19] DEBUG [9A1nYKdAgxg] Closing connection to the server using "end"
 [2023-12-14 12:57:19] ERROR Send Error: Connection closed unexpectedly
 Error while send emailError: Connection closed unexpectedly
 ERROR Error: Connection closed unexpectedly
 at SMTPConnection._onClose (/snapshot/rmr/node_modules/nodemailer/lib/smtp-connection/index.js:844:34)
 at Socket.SMTPConnection._onSocketClose (/snapshot/rmr/node_modules/nodemailer/lib/smtp-connection/index.js:195:42)
 at Object.onceWrapper (node:events:642:26)
 at Socket.emit (node:events:527:28)
 at TCP.<anonymous> (node:net:709:12) {
 code: 'ECONNECTION',
 command: 'CONN'
 }
```

Are there any suggestions why the error might occur?

**Comment by gusth-sa** [comment]
@MiniKrishna Have you found the cause or a possible fix?
I'm facing the same issue.

**Comment by MiniKrishna** [comment]
> @MiniKrishna Have you found the cause or a possible fix? I'm facing the same issue.


Yes, in my case, i don't need auth section at all, so i remove it from createTransport config.
