### ISSUE TITLE
Property "protoype" undefined

### ISSUE THREAD

**Issue by PetrDusek** [nodemailer/nodemailer#304]
Hello, im facing problem with nodemailer. All i do is just copy paste your example for sending emails.

var nodemailer = require('nodemailer');
var transporter = nodemailer.createTransport();
transporter.sendMail({
    from: 'sender@address',
    to: 'receiver@address',
    subject: 'hello',
    text: 'hello world!'
});

 And when i try to launch it using node command i got this error.

util.js:523
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:523:43)
    at Object.<anonymous> (C:\Users\Petr\Desktop\Prace\tasks\node_modules\nodema
iler\node_modules\libmime\node_modules\libbase64\lib\libbase64.js:82:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (C:\Users\Petr\Desktop\Prace\tasks\node_modules\nodema
iler\node_modules\libmime\src\libmime.js:4:17)
    at Module._compile (module.js:449:26)

Can someone give me a hint what is wrong? I am using Node.js version 0.8.0. Thanks for reply.

**Comment by euglv** [comment]
Hello, I get the same error, but I use io.js v3.3.0, npm  v2.13.3
