### ISSUE TITLE
Error: Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by jlentijo** [nodemailer/nodemailer#342]
Hi, 

When I try connect with this params...

```
mailer: {
    from: 'EMAIL@DOMAIN.com',
    options: {
        host: 'smtp.DOMAIN.com',
        auth: {
            user: 'USERNAME',
            pass: 'PWD'
        }
    }
}
```

I get this error...

```
Error: Hostname/IP doesn't match certificate's altnames
    at SecurePair.<anonymous> (tls.js:1376:23)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:979:10)
    at CleartextStream.read [as _read] (tls.js:471:13)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at EncryptedStream.write [as _write] (tls.js:368:25)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at EncryptedStream.Writable.write (_stream_writable.js:182:11)
    at Socket.ondata (stream.js:51:26)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
```

If I add `ignoreTLS: true` then I can send the mail correctly, i don't want ignore TLS, what can I do?

I was using Nodemailer v1.1.2 on node v.0.10.30.

Best regards,
Thanks.

**Comment by rarajks** [comment]
But setting `rejectUnauthorized:false` does not ensure that we are talking to the correct server, does it?

**Comment by behiyegok** [comment]
thanks andris9

**Comment by jorgemmsilva** [comment]
@rarajks Yeah, I think it does :/

Did you found a clean way to validate the server identity?

**Comment by shahidsm93** [comment]
Bump.. Need solution!

**Comment by jorgemmsilva** [comment]
@shahidsm93 haven't implemented it yet. But I think loading the correct CA should work:

https://stackoverflow.com/questions/31861109/tls-what-exactly-does-rejectunauthorized-mean-for-me
