### ISSUE TITLE
this.resolveContent is undefined?

### ISSUE THREAD

**Issue by Siyfion** [nodemailer/nodemailer#344]
I get the error below when attempting to send a fairly simple example with the most recent release of Nodemailer.

```
TypeError: Cannot call method 'bind' of undefined
    at Object.Nodemailer.sendMail (/Users/siyfion/Git/LabelLogicLive_Server/node_modules/nodemailer/src/nodemailer.js:81:45)
    at exports.apiErrors (/Users/siyfion/Git/LabelLogicLive_Server/server_dist/config/middleware/errorHandling.js:37:13)
    at Layer.handle_error (/Users/siyfion/Git/LabelLogicLive_Server/node_modules/express/lib/router/layer.js:52:5)
    at trim_prefix (/Users/siyfion/Git/LabelLogicLive_Server/node_modules/express/lib/router/index.js:268:13)
    at proto.handle.c (/Users/siyfion/Git/LabelLogicLive_Server/node_modules/express/lib/router/index.js:237:9)
    at Function.proto.process_params (/Users/siyfion/Git/LabelLogicLive_Server/node_modules/express/lib/router/index.js:312:12)
    at proto.handle.c (/Users/siyfion/Git/LabelLogicLive_Server/node_modules/express/lib/router/index.js:228:12)
    at Function.match_layer (/Users/siyfion/Git/LabelLogicLive_Server/node_modules/express/lib/router/index.js:295:3)
    at next (/Users/siyfion/Git/LabelLogicLive_Server/node_modules/express/lib/router/index.js:189:10)
    at exports.logErrors (/Users/siyfion/Git/LabelLogicLive_Server/server_dist/config/middleware/errorHandling.js:32:12)
```

**Comment by vrodic** [comment]
I use nodemailer with generators like this:

`	var mailerSend = thunkify(transport.sendMail);
         ....
        var return = yield mailerSend(preparedEmail);` 

How am I supposed to call it in the new version of nodeMailer?
