### ISSUE TITLE
Direct mode gives "Sending failed" error when sending to localhost

### ISSUE THREAD

**Issue by fresheneesz** [nodemailer/nodemailer#544]
I have this test setup:

```
var smtp = require('smtp-server')
var nodemailer = require('nodemailer')

var SMTPServer = smtp.SMTPServer
var port = 25

var server = new SMTPServer({
    disabledCommands: ['STARTTLS', 'AUTH'],

    onData: function(stream, session, callback){
        stream.pipe(process.stdout); // print message to console
        stream.on('end', callback);
    },
    onRcptTo: function(address, session, callback){
        console.log("RcptTo: "+address)
        return callback(); // Accept the address
    } ,
    onMailFrom: function(address, session, callback){
        console.log("MailFrom: "+address)
        return callback(); // Accept the address
    },
    onAuth: function(auth, session, callback){
        console.log("Auth: "+auth.method+' by '+auth.username)
        callback(null, {})
    }
})

server.on('error', function(err){
    console.log('Error %s', err.message);
});


var transporter = nodemailer.createTransport({direct:true})
var mailOptions = {
    from: 'Fred Foo 👥 <foo@whatever.whatever>',
    to: 'test@localhost',
    subject: 'Hello ✔',
    text: 'Hello world',
    html: '<b>Hello world</b>'
}

server.listen(port, function() {
    console.log("Listening for email on port "+port)

    transporter.sendMail(mailOptions, function(error, info){
        if(error){
            return console.log(error.stack)
        }

        console.log('Callback info: ')
        console.dir(info)

        server.close(function(){
            console.log("server closed")
        })
    })
});
```

I would expect that nodemailer would connect to localhost for this and send the email, but I don't see any response from either the server or client. My output is this:

```
[2016-01-14 02:14:49] INFO: SMTP Server listening on [::]:25
Listening for email on port 25
Error: Sending failed
    at DirectMailer.<anonymous> (D:\billysFile\code\tests\node.js\node_modules\nodemailer\node_modules\nodemailer-direct-transport\lib\direct-transport.js:141:41)
    at DirectMailer.<anonymous> (D:\billysFile\code\tests\node.js\node_modules\nodemailer\node_modules\nodemailer-direct-transport\lib\direct-transport.js:185:22)
    at D:\billysFile\code\tests\node.js\node_modules\nodemailer\node_modules\nodemailer-direct-transport\lib\direct-transport.js:412:24
    at QueryReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:210:10)
```

If I change the `createTransport` options to `{host:'localhost', port:25}`, sending works fine. Am I doing something wrong? 

Testing this on windows 8, node v5.1.0, smtp-server 1.7.1, and nodemailer v2.0.0

**Comment by andris9** [comment]
If you set `direct` to `true` then the message is sent to the host that is resolved by the DNS MX query. "localhost" does not have a MX query. If MX is missing, then A/AAAA is tried but "localhost" does not have these records either. I guess one option would be to use `lookup` instead of `resolve` as in this case it would also detect the "localhost" IP which it currently does not.

**Comment by fresheneesz** [comment]
Ah I see, that does make sense. I guess this is one of those few cases where localhost testing probably isn't the easiest way to do it.
