### ISSUE TITLE
Crash on sending an email with XOauth2

### ISSUE THREAD

**Issue by DerpgonCz** [nodemailer/nodemailer#554]
Using:
```
nodemailer@2.1.0-rc.1 (tested with 2.0.0 aswell)
nodejs@v5.4.1
```

The error:
```
/home/ubuntu/workspace/node_modules/smtp-connection/lib/smtp-connection.js:1019
        this._auth.xoauth2[isRetry ? 'generateToken' : 'getToken'](function (err, token) {
                                                                  ^

TypeError: this._auth.xoauth2[(intermediate value)(intermediate value)(intermediate value)] is not a function
    at SMTPConnection._handleXOauth2Token (/home/ubuntu/workspace/node_modules/smtp-connection/lib/smtp-connection.js:1019:67)
    at SMTPConnection.login (/home/ubuntu/workspace/node_modules/smtp-connection/lib/smtp-connection.js:246:18)
    at SMTPTransport.<anonymous> (/home/ubuntu/workspace/node_modules/nodemailer-smtp-transport/lib/smtp-transport.js:126:24)
    at SMTPConnection.<anonymous> (/home/ubuntu/workspace/node_modules/smtp-connection/lib/smtp-connection.js:150:13)
    at SMTPConnection.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at SMTPConnection.emit (events.js:166:7)
    at SMTPConnection._actionEHLO (/home/ubuntu/workspace/node_modules/smtp-connection/lib/smtp-connection.js:754:10)
    at SMTPConnection._processResponse (/home/ubuntu/workspace/node_modules/smtp-connection/lib/smtp-connection.js:559:16)
    at SMTPConnection._onData (/home/ubuntu/workspace/node_modules/smtp-connection/lib/smtp-connection.js:389:10)
```

The code:
```
var opts = {
    host: 'smtp.gmail.com',
    port: 465,
    secure: true,
    auth: {
        xoauth2: {
            user: "testacc@gmail.com",
            clientId: "{my client ID}",
            clientSecret: "{my client secret}",
            refreshToken: "{my refresh token}",
            timeout: 3600,
        },
    },
};
var trans = NM.createTransport(opts);

var mailopts = {
    from: 'testacc <testacc@gmail.com>',
    to: 'myacc@gmail.com',
    subject: 'Hello',
    text: 'World',
};
trans.sendMail(mailopts, function(error, info){
    console.log(error || info.response);
});
```

**Comment by andris9** [comment]
See [here](http://nodemailer.com/2-0-0-beta/using-oauth2/) how to set up XOAuth2 with Nodemailer
