### ISSUE TITLE
Bunyan Logger throws TypeError: Illegal invocation

### ISSUE THREAD

**Issue by binarykitchen** [nodemailer/nodemailer#567]
I am passing on my own Bunyan instance to nodemailer with the `logger` option and experience this TypeError when sending an email.

```
    TypeError: Illegal invocation
        at createWriteReq (net.js:707:21)
        at Socket._writeGeneric (net.js:671:11)
        at Socket._write (net.js:694:8)
        at doWrite (_stream_writable.js:292:12)
        at writeOrBuffer (_stream_writable.js:278:5)
        at Socket.Writable.write (_stream_writable.js:207:11)
        at Socket.write (net.js:618:40)
        at Logger._emit (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/bunyan/lib/bunyan.js:890:22)
        at Logger.info (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/bunyan/lib/bunyan.js:989:24)
        at Nodemailer.sendMail (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/nodemailer/lib/nodemailer.js:171:17)
        at async.series.sendMail (/home/michael-heuberger/binarykitchen/code/videomail.io/src/util/email.js:143:35)
        at /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/async/lib/async.js:718:13
        at iterate (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/async/lib/async.js:262:13)
        at /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/async/lib/async.js:274:29
        at /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/async/lib/async.js:44:16
        at /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/async/lib/async.js:723:17
        at /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/async/lib/async.js:167:37
        at /home/michael-heuberger/binarykitchen/code/videomail.io/src/util/email.js:132:21
        at tryCatcher (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/bluebird/js/main/promise.js:507:31)
        at Promise._settlePromiseAt (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/bluebird/js/main/promise.js:581:18)
        at Promise._settlePromises (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/bluebird/js/main/promise.js:697:14)
```

The code how I created the smtpTransporter is:

```js
bunyanLogger = bunyan.createLogger({})

...

var smtpTransport = nodemailer.createTransport({
    secure: false,
    logger: bunyanLogger,
    tls: {
        rejectUnauthorized: false
    }
})
```

Any clues? A bug or am I doing something wrong?

**Comment by andris9** [comment]
Could you try using the latest beta and see if the error is present there as well?

    npm install nodemailer@beta

What kind of data are you passing to `bunyan.createLogger`? Does it take an empty object or do you have some properties for it as well, eg `name`?

**Comment by binarykitchen** [comment]
@andris9 i am creating the bunyan logger like that

```js
    var logger = bunyan.createLogger({
        'name':  'videomail.io',
        'level': 'debug'
    })
```

yay, with your beta branch it works fine now!

**Comment by andris9** [comment]
Ok, great, if it works then it doesn't make a difference what arguments do you use. I'll publish the beta in the coming days as stable so everyone should get the fix.

**Comment by binarykitchen** [comment]
yeah, npm-publish that soon. thx for your good work!
