### ISSUE TITLE
Error: No default engine was specified and no extension was provided

### ISSUE THREAD

**Issue by azat-io** [nodemailer/nodemailer#587]
Hello! I have a problem with Nodemailer and Express. Could you help me please to tell what's wrong here.

Part of `package.json`:

```json
  "dependencies": {
    "express": "^4.13.3",
    "nodemailer": "^2.3.0",
    "react": "^0.14.3",
    "react-dom": "^0.14.3"
  },
```

Here is my form which data from I want to send to my email:

```jsx
import React from 'react'
import styles from './index.css'

export default class Form extends React.Component {
  render() {
    return (
      <form action='/contact' method='post'>
        <h2>Contact me</h2>
        <input name='name' type='text' placeholder='Name' required />
        <input name='location' type='text' placeholder='Location' required />
        <input name='email' type='email' placeholder='Email' required />
        <textarea name='message' />
        <button type='submit'>Send</button>
      </form>
    );
  }
```

And this is a part of `server.js` *Express* file

```javascript
const express = require('express');
const nodemailer = require('nodemailer');

  app.use(middleware);
  app.use(webpackHotMiddleware(compiler));
  app.get('/', function response(req, res) {
    res.write(middleware.fileSystem.readFileSync(path.join(__dirname, '../dist/index.html')));
    res.end();
  });

  // Nodemailer:

  app.post('/contact', function (req, res) {
    var mailOpts, smtpTrans;
    smtpTrans = nodemailer.createTransport('SMTP', {
      service: 'Gmail',
      auth: {
        user: "some-my-email@gmail.com",
        pass: "password-of-this-email" // Can it works without it?!
      }
    });
    mailOpts = {
      from: 'noreply@gmail.com>',
      to: 'my-email@gmail.com',
      subject: 'Website contact form',
      text: req.body.message
    };
    smtpTrans.sendMail(mailOpts, function (error, response) {
      if (error) {
        res.render('contact', {
          err: true, page: 'contact'
        })
      }
      else {
        res.render('contact', {
          err: false, page: 'contact'
        })
      }
    });
  });
```

SO.

There are two errors. If `text` of mailOpts is "req.body.message" there is this error:

```bash
TypeError: Cannot read property 'message' of undefined
   at /home/azat/git/azat-io/scripts/server.js:50:21
   at Layer.handle [as handle_request] (/home/azat/git/azat-io/node_modules/express/lib/router/layer.js:95:5)
   at next (/home/azat/git/azat-io/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/home/azat/git/azat-io/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/home/azat/git/azat-io/node_modules/express/lib/router/layer.js:95:5)
   at /home/azat/git/azat-io/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/home/azat/git/azat-io/node_modules/express/lib/router/index.js:330:12)
   at next (/home/azat/git/azat-io/node_modules/express/lib/router/index.js:271:10)
   at middleware (/home/azat/git/azat-io/node_modules/webpack-hot-middleware/middleware.js:39:48)
   at Layer.handle [as handle_request] (/home/azat/git/azat-io/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/azat/git/azat-io/node_modules/express/lib/router/index.js:312:13)
   at /home/azat/git/azat-io/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/home/azat/git/azat-io/node_modules/express/lib/router/index.js:330:12)
   at next (/home/azat/git/azat-io/node_modules/express/lib/router/index.js:271:10)
   at processRequest (/home/azat/git/azat-io/node_modules/webpack-dev-middleware/middleware.js:176:12)
   at ready (/home/azat/git/azat-io/node_modules/webpack-dev-middleware/middleware.js:96:20)
```

If `text` of mailOpts is just string "Hello!" there is this error:

```bash
Error: No default engine was specified and no extension was provided.
   at new View (/home/azat/git/azat-io/node_modules/express/lib/view.js:62:11)
   at EventEmitter.render (/home/azat/git/azat-io/node_modules/express/lib/application.js:569:12)
   at ServerResponse.render (/home/azat/git/azat-io/node_modules/express/lib/response.js:961:7)
   at /home/azat/git/azat-io/scripts/server.js:54:13
   at Nodemailer.sendMail (/home/azat/git/azat-io/node_modules/nodemailer/lib/nodemailer.js:265:16)
   at /home/azat/git/azat-io/scripts/server.js:52:15
   at Layer.handle [as handle_request] (/home/azat/git/azat-io/node_modules/express/lib/router/layer.js:95:5)
   at next (/home/azat/git/azat-io/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/home/azat/git/azat-io/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/home/azat/git/azat-io/node_modules/express/lib/router/layer.js:95:5)
   at /home/azat/git/azat-io/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/home/azat/git/azat-io/node_modules/express/lib/router/index.js:330:12)
   at next (/home/azat/git/azat-io/node_modules/express/lib/router/index.js:271:10)
   at middleware (/home/azat/git/azat-io/node_modules/webpack-hot-middleware/middleware.js:39:48)
   at Layer.handle [as handle_request] (/home/azat/git/azat-io/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/azat/git/azat-io/node_modules/express/lib/router/index.js:312:13)
```

Help me please, what is wrong here?

**Comment by andris9** [comment]
This probably means that you have something wrong in your express code. The first error indicates that `req.body` is not available for whatever reason (maybe it's a GET call, maybe `req` was overwritten somewhere?). The second error indicates that express.js view engine is not properly set up (or `res` is overwritten somewhere?).

I don't think neither of these errors are related to Nodemailer.

**Comment by azat-io** [comment]
@andris9 Sounds bad. All works except form sending
