### ISSUE TITLE
replyTo does not seem to support different address formats

### ISSUE THREAD

**Issue by Martinsos** [nodemailer/nodemailer#610]
First of all, thank you for this great library :)!

Information:
Nodemailer version: 1.11.0
Node version: 6.0.0
Operating system: ArchLinux, 4.5.2-1-ck

Problem:
When I try to set both name and address to `replyTo` by using an object, like this:
```
replyTo: {
          name: 'Test Mail',
          address: 'test@mail.com'
        }
```
I get an error:
```
node_modules/nodemailer-sendgrid-transport/src/sendgrid-transport.js:28
    if (a.indexOf('<') >= 0 && a.indexOf('>') > 0) {
          ^

TypeError: a.indexOf is not a function
    at trimReplyTo (.../node_modules/nodemailer-sendgrid-transport/src/sendgrid-transport.js:28:11)
    at SendGridTransport.send (.../node_modules/nodemailer-sendgrid-transport/src/sendgrid-transport.js:39:21)
    at Nodemailer.<anonymous> (.../node_modules/nodemailer/src/nodemailer.js:148:30)
    at Nodemailer._processPlugins (.../node_modules/nodemailer/src/nodemailer.js:295:16)
    at Nodemailer.<anonymous> (.../node_modules/nodemailer/src/nodemailer.js:144:14)
    at Nodemailer.<anonymous> (.../node_modules/nodemailer/src/nodemailer.js:302:20)
    at .../node_modules/nodemailer/src/nodemailer.js:309:13
    at HTMLToText.<anonymous> (.../node_modules/nodemailer-html-to-text/src/nodemailer-html-to-text.js:38:9)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

Note: This same object works for `from` field, so I am pretty sure nothing is wrong with it.

Next, I tried providing string of following format: `'"Test Mail" <test@mail.com>'` and then there was no error, however when email is sent only address is included in replyTo field (I check original of message in gmail, and replyTo header has only address, no name).

Thank you for any help!

**Comment by andris9** [comment]
This seems to be an issue with the SendGrid transport module.
