### ISSUE TITLE
nodemailer-fetch non catchable errors

### ISSUE THREAD

**Issue by simllll** [nodemailer/nodemailer#615]
Sending an email with an attachment (http url with a 404 return code), creates an uncatchable exception:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Invalid status code 404
    at ClientRequest.<anonymous> (d:\users\stretter\workspaceNodejs\hokify-server\node_modules\nodemailer\node_modules\nodemailer-fetch\lib\fetch.js:146:36)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

a try / catch block or anything else I've tried does not catch this error.

tested with latest Nodemailer 2.4.0.
Running Node JS 4.4.x
happening on OS Windows & Linux

Simple test code:

```
var nodemailer = require('nodemailer');
var mailTransport = require(...); // set up a mail transporter
var nodemailerTransport = nodemailer.createTransport(mailTransport(... config for mailtransporter ...));

var mailOptions = {};
mailOptions.attachments = [{
    filename: "deadlink",
    path: "http://google.com/deadlink"
}];

mailOptions.text = "test maiL";
mailOptions.to = "someone@whereisthererror.com";
mailOptions.subject = "mail subject";

try {
    nodemailerTransport.sendMail(mailOptions, function (err) {
        console.log("ERROR", err);
    });
}catch(err) {
    console.log("ERROR", err);
};
```

Anyone an idea what is happening here?

**Comment by simllll** [comment]
Opened a bug report at nodemailer-fetch
https://github.com/nodemailer/nodemailer-fetch/issues/1

**Comment by jafar-rezaei** [comment]
We still having this error at nodemailer version : 4.6.8
How we should solve this error ?

**Comment by Floriferous** [comment]
This is still an issue, please reopen this.

**Comment by Floriferous** [comment]
Still relevant

**Comment by andris9** [comment]
Does not seem as relevant anymore. I used the following as an attachment with latest nodemailer and the error was catched, did not kill node process:

```
attachments: [
        {
            filename: 'deadlink',
            path: 'http://google.com/deadlink',
        },
    ]
```
and logs as expected
```
[2020-05-28 07:36:44] DEBUG [DFUKle0H4o] ----_NmP-64548b174e5f3e3d-Part_1
[2020-05-28 07:36:44] DEBUG [DFUKle0H4o] Content-Type: application/octet-stream; name=deadlink
[2020-05-28 07:36:44] DEBUG [DFUKle0H4o] Content-Transfer-Encoding: base64
[2020-05-28 07:36:44] DEBUG [DFUKle0H4o] Content-Disposition: attachment; filename=deadlink
[2020-05-28 07:36:44] DEBUG [DFUKle0H4o]
[2020-05-28 07:36:44] DEBUG [DFUKle0H4o] Closing connection to the server using "end"
[2020-05-28 07:36:44] ERROR Send error for <77849a98-9e2a-9096-de86-3b18bb0114e0@itcollege.ee>: Invalid status code 404
[2020-05-28 07:36:44] ERROR Send Error: Invalid status code 404
```

**Comment by NathanBrews** [comment]
this is really frustrating 
MERN/VITE email activation = http://localhost:5173/activation/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYnJ3cyIsImVtYWlsIjoiYnJld3MyNDJAcHJvdG9uLm1lIiwicGFzc3dvcmQiOiJicndzMjQyIiwiYXZhdGFyIjoiSU1HXzIwMjIxMjI1XzE4NDE1OC0xNjg1NDk0MTQwMjAwLTM5MjA4NTMucG5nIiwiaWF0IjoxNjg1NDk0MTQwLCJleHAiOjE2ODU0OTQ0NDB9.w7JZW4yA4lmZI4Niog0eojM3UBw7ykVODMtJJJJaJVA
HTTP ERROR 404

**Comment by simllll** [comment]
What you can do is to use the "domain" as workaround to catch errors.

e.g.
```ts
import { create as createDomain } from 'node:domain';

await new Promise<void>((resolve, reject) => {
		const d = createDomain();
		// Domain emits 'error' when it's given an unhandled error
		d.on('error', err => {
			reject(err);
		});
		d.run(async () => {
			try {
				await this.nodemailerTransport.sendMail(newMailOptions);
				resolve();
			} catch (err) {
				reject(err);
			}
		});
	});
```

**Comment by simllll** [comment]
I just checked today again, this error is still present. Can someone reopen this ticket maybe? @andris9
