### ISSUE TITLE
ntlm bug

### ISSUE THREAD

**Issue by OferE** [nodemailer/nodemailer#632]
Relevant to nodemailer 2.4.1 and 2.4.2 where ntlm authentication is presented.
using node 4.2.6
ubuntu 14.04

I'm having issue with ntlm authentication.
i enabled debugging and this is the output:
[2016-06-27 14:30:19] INFO: Sending mail using SMTP/2.5.0[client:2.5.0]
[2016-06-27 14:30:19] INFO: [piLbBOwqxkk] Connection established to 10.1.10.35:587
[2016-06-27 14:30:19] INFO: [piLbBOwqxkk] Connection upgraded with STARTTLS
[2016-06-27 14:30:19] DEBUG: [piLbBOwqxkk] SMTP handshake finished
[2016-06-27 14:30:19] INFO: [piLbBOwqxkk] User "alerts@company.com" authenticated
[2016-06-27 14:30:19] INFO: Sending message <1467037819195-328084f6-d61245fc-f5a0bf5d@alerts.company.com> to <someone@company.com>
[2016-06-27 14:30:19] DEBUG: [piLbBOwqxkk] Closing connection to the server using "end"
[2016-06-27 14:30:19] ERROR: Send Error: Mail command failed: 501 5.1.7 Invalid address
[2016-06-27 14:30:19] INFO: [piLbBOwqxkk] Connection closed

This is the call stack:
```
 Uncaught AssertionError: expected Error {
  code: 'EENVELOPE',
  response: '501 5.1.7 Invalid address',
  responseCode: 501,
  message: 'Mail command failed: 501 5.1.7 Invalid address'
} to not exist
      at tests/mailer.js:15:21
      at lib/mailer.js:51:13
      at Nodemailer.<anonymous> (node_modules/nodemailer/lib/nodemailer.js:320:26)
      at node_modules/nodemailer/node_modules/nodemailer-smtp-transport/lib/smtp-transport.js:134:28
      at callback (node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:346:14)
      at SMTPConnection.<anonymous> (node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:357:20)
      at SMTPConnection._actionMAIL (node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:1084:16)
      at SMTPConnection.<anonymous> (node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:703:14)
      at SMTPConnection._processResponse (node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:622:16)
      at SMTPConnection._onData (node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:449:10)
      at readableAddChunk (_stream_readable.js:146:16)
      at TLSSocket.Readable.push (_stream_readable.js:110:10)
      at TLSWrap.onread (net.js:523:20)
```

these are the options i used for sending the mail:
```javascript
{
   "from": "alerts <alerts.company.com>",
   "to": " someone <someone@company.com> ",
   "subject": "test mail from alert test",
   "text": "hello world"
}
```
these are the options i authenictated with:
```javascript
   options = {                                                                                                     
      host: 'mailsrv.company.com',                                                                                
      port: 587,                                                                                                   
      authMethod: 'ntlm',
      logger: true,                                                                                                
      auth: {                                                                                                      
         user: 'alerts@company.com',                                                                           
         pass: 'somepassword'                                                                                          
     }                                                                                                             
   };       
```
The real users and password and company name were changed for obvious reason.

Thanks

**Comment by andris9** [comment]
Doesn't seem to be NTLM issue as envelope errors occur after authentication. Is the from addres really like alerts.company.com as it is not a valid address?

**Comment by OferE** [comment]
you are right - i missed it.
I spent hours on this one.
thank you very much.
closing it.

**Comment by seanburman** [comment]
I'm late to the party but this made my day! Thank you :)
