### ISSUE TITLE
Error: Greeting never received

### ISSUE THREAD

**Issue by alseambusher** [nodemailer/nodemailer#638]
I am trying to connect to outlook.office365.com through this
```js
var transporter = nodemailer.createTransport({
    host : "outlook.office365.com",
    port: 443,
    secure: true, // use SSL
    debug: true,
    auth : {
        user : "username",
        pass : "password"
    }
});
```
I get this error
```
{ Error: Greeting never received
    at SMTPConnection._formatError (/Users/alse/code/adobe/checker/node_modules/smtp-connection/lib/smtp-connection.js:493:15)
    at SMTPConnection._onError (/Users/alse/code/adobe/checker/node_modules/smtp-connection/lib/smtp-connection.js:479:16)
    at SMTPConnection.<anonymous> (/Users/alse/code/adobe/checker/node_modules/smtp-connection/lib/smtp-connection.js:420:18)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5) code: 'ETIMEDOUT', command: 'CONN' }
```
I also tried to see if I am able to connect to 443 

```bash
nc -vz outlook.office365.com 443
```

```
found 0 associations
found 1 connections:
     1:	flags=82<CONNECTED,PREFERRED>
	outif en0
	src 10.58.18.101 port 62196
	dst 132.245.36.18 port 443
	rank info not available
	TCP aux info available

Connection to outlook.office365.com port 443 [tcp/https] succeeded!
```

**Comment by andris9** [comment]
443 is for HTTPS not SMTP. Check the actual config

**Comment by alseambusher** [comment]
Thanks for replying :) I have the same configuration setup on the my phone and it works. I guess our SMTP works through 443
![sketch-1469211808149](https://cloud.githubusercontent.com/assets/1242542/17067116/22d1530e-4fff-11e6-8a55-6a19311ed5de.png)

**Comment by nstuyvesant** [comment]
var transporter = nodemailer.createTransport({
	host: 'smtp.office365.com', // Office 365 server
	port: 587, // secure SMTP
	secureConnection: 'false', // false for TLS
	auth: {
		user: 'useremail@foo.com',
		pass: 'mysecret'
	},
	tls: {
		ciphers: 'SSLv3'
	}
});
