### ISSUE TITLE
Nodemailer - not working throws a bunch of errors

### ISSUE THREAD

**Issue by srinivaasang1** [nodemailer/nodemailer#662]
Include the following information with your issue:

1) Nodemailer version 2.6.0
2) Node.js version you are using (run `node -v` to see it, eg v5.5.0)
3) mac os
whenever i try adding this line " import nodemailer from 'nodemailer';" the server throws me all the below erros. as soon as i comment the above line ,all the below errors vanishes.

ERROR in ./~/nodemailer/package.json
Module parse failed: /Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/nodemailer/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp$4.raise (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
 @ ./~/nodemailer/lib/nodemailer.js 11:18-44

ERROR in ./~/nodemailer/lib/http-proxy.js
Module not found: Error: Cannot resolve module 'net' in /Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/nodemailer/lib
 @ ./~/nodemailer/lib/http-proxy.js 7:10-24

ERROR in ./~/nodemailer/lib/http-proxy.js
Module not found: Error: Cannot resolve module 'tls' in /Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/nodemailer/lib
 @ ./~/nodemailer/lib/http-proxy.js 8:10-24

ERROR in ./~/nodemailer-direct-transport/lib/direct-transport.js
Module not found: Error: Cannot resolve module 'net' in /Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/nodemailer-direct-transport/lib
 @ ./~/nodemailer-direct-transport/lib/direct-transport.js 6:10-24

ERROR in ./~/nodemailer-direct-transport/lib/direct-transport.js
Module not found: Error: Cannot resolve module 'dns' in /Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/nodemailer-direct-transport/lib
 @ ./~/nodemailer-direct-transport/lib/direct-transport.js 5:10-24

ERROR in ./~/nodemailer-shared/lib/shared.js
Module not found: Error: Cannot resolve module 'fs' in /Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/nodemailer-shared/lib
 @ ./~/nodemailer-shared/lib/shared.js 5:9-22

ERROR in ./~/nodemailer-direct-transport/package.json
Module parse failed: /Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/nodemailer-direct-transport/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp$4.raise (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
 @ ./~/nodemailer-direct-transport/lib/direct-transport.js 9:18-44

ERROR in ./~/nodemailer-smtp-pool/package.json
Module parse failed: /Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/nodemailer-smtp-pool/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp$4.raise (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
 @ ./~/nodemailer-smtp-pool/lib/smtp-pool.js 4:18-44

ERROR in ./~/nodemailer-smtp-transport/package.json
Module parse failed: /Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/nodemailer-smtp-transport/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp$4.raise (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
 @ ./~/nodemailer-smtp-transport/lib/smtp-transport.js 4:18-44

ERROR in ./~/socks/lib/socks-agent.js
Module not found: Error: Cannot resolve module 'tls' in /Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/socks/lib
 @ ./~/socks/lib/socks-agent.js 1:10-24

ERROR in ./~/socks/lib/socks-client.js
Module not found: Error: Cannot resolve module 'net' in /Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/socks/lib
 @ ./~/socks/lib/socks-client.js 1:10-24

ERROR in ./~/smtp-connection/lib/smtp-connection.js
Module not found: Error: Cannot resolve module 'net' in /Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/smtp-connection/lib
 @ ./~/smtp-connection/lib/smtp-connection.js 6:10-24

ERROR in ./~/smtp-connection/lib/smtp-connection.js
Module not found: Error: Cannot resolve module 'tls' in /Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/smtp-connection/lib
 @ ./~/smtp-connection/lib/smtp-connection.js 7:10-24

ERROR in ./~/buildmail/lib/buildmail.js
Module not found: Error: Cannot resolve module 'fs' in /Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/buildmail/lib
 @ ./~/buildmail/lib/buildmail.js 10:9-22

ERROR in ./~/smtp-connection/package.json
Module parse failed: /Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/smtp-connection/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp$4.raise (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
 @ ./~/smtp-connection/lib/smtp-connection.js 3:18-44

ERROR in ./~/nodemailer-wellknown/services.json
Module parse failed: /Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/nodemailer-wellknown/services.json Unexpected token (2:11)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:11)
    at Parser.pp$4.raise (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
 @ ./~/nodemailer-wellknown/index.js 3:15-41

ERROR in ./~/iconv-lite/encodings/tables/gb18030-ranges.json
Module parse failed: /Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/iconv-lite/encodings/tables/gb18030-ranges.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:9)
    at Parser.pp$4.raise (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Applications/MAMP/htdocs/TamilMoviesMelbourne/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
 @ ./~/iconv-lite/encodings/dbcs-data.js 99:37-76

**Comment by andris9** [comment]
It seems like you are trying to use nodemailer through webpack or in front-end. Nodemailer is for back end node.js only. The correct way to laoad it is the following:

```javascript
// script.js
var nodemailer = require('nodemailer');
```

and then run

```
node script.js
```
