### ISSUE TITLE
Unable to send email using nodemailer gmail smtp on server

### ISSUE THREAD

**Issue by yash-sharma9091** [nodemailer/nodemailer#678]
Hi, please help with following problems, i am using nodemailer to send email from staging server on my company, and getting following errors, however on my local machine there is no such error and i can easily send emails using gmail smtp

```
mail:{
    poolConfig : {
        pool: true,
        host: 'smtp.gmail.com', // Gmail as mail client
        port: 587,
        secure: false, // use SSL
        auth: {
            user: 'xxxxxx.nodejs@gmail.com',
            pass: 'xxxxxx@123'
        }
    },
from: '"xxxxxx Tech " <xxxxxx.nodejs@gmail.com>'
}
```

with above configs following error is shown
2016-10-14T12:14:53.237Z - info:  Error: self signed certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
# 

As mentioned here [https://github.com/nodemailer/nodemailer/issues/406]

```
poolConfig : {
    pool: true,
    host: 'smtp.gmail.com', // Gmail as mail client
    port: 587,
    secure: false, // use SSL
    auth: {
        user: 'xxxxxx.nodejs@gmail.com',
        pass: 'xxxxxx@123'
    },
    ignoreTLS: true,
    tls: {
        rejectUnauthorized: false
    }
},
```

i tweaks the configs accordingly, then following errors shown
2016-10-14T12:26:55.288Z - info:  Error: Invalid login: 535 Incorrect authentication data
    at SMTPConnection._formatError (/home/cherrydev/public_html/node_modules/smtp-connection/lib/smtp-connection.js:528:15)
    at SMTPConnection._actionAUTHComplete (/home/cherrydev/public_html/node_modules/smtp-connection/lib/smtp-connection.js:1231:30)
    at SMTPConnection.<anonymous> (/home/cherrydev/public_html/node_modules/smtp-connection/lib/smtp-connection.js:319:22)
    at SMTPConnection._processResponse (/home/cherrydev/public_html/node_modules/smtp-connection/lib/smtp-connection.js:669:16)
    at SMTPConnection._onData (/home/cherrydev/public_html/node_modules/smtp-connection/lib/smtp-connection.js:493:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
# 

My local configs

```
poolConfig : {
    pool: true,
    host: 'smtp.gmail.com', // Gmail as mail client
    port: 465,
    secure: true, // use SSL
    auth: {
        user: 'xxxxxx.php@gmail.com',
        pass: 'xxxxxx@123'
    }
}
```

No errors, mails sent easily

**Comment by ibankcoin** [comment]
I have the same issue, please help

**Comment by sureshkoduri** [comment]
I have the same issue, please help

**Comment by mgautam98** [comment]
I have the same issue, please help
