### ISSUE TITLE
Godaddy issue SMTP issue

### ISSUE THREAD

**Issue by karthikeyana** [nodemailer/nodemailer#696]
Include the following information with your issue:

configuration : 
```
 var transporter = nodemailer.createTransport({
    host: 'smtpout.secureserver.net',
    port: 465,
    secure: false, // use SSL
    debug: true,
      auth: {
        user: 'xyz@godaddy.com',
        pass: 'asdfasSDFJKH'
      }
  });
```

error:

```
Failed in sending mail
{ success: false, existing: false, sendError: true }
{ Error: Connection timeout
    at SMTPConnection._formatError (/home/amtex/Documents/projects/test_case/sendmail/node_modules/smtp-connection/src/smtp-connection.js:384:15)
    at SMTPConnection._onError (/home/amtex/Documents/projects/test_case/sendmail/node_modules/smtp-connection/src/smtp-connection.js:374:29)
    at SMTPConnection.<anonymous> (/home/amtex/Documents/projects/test_case/sendmail/node_modules/smtp-connection/src/smtp-connection.js:163:14)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5) code: 'ETIMEDOUT' }
```

1) Nodemailer version you are having problems with  +-- nodemailer@1.11.0
2) Node.js version you are using v6.9.0
3) Your operating system Ubuntu 16.04.
4) If possible, include a minimal test case that can be used to verify your issue (link to a gist would be great!)

If you are having problems with Godaddy, then make sure you have
read this post before filing your issue: http://nodemailer.com/using-gmail/

**Comment by andris9** [comment]
Set `secure: true` as port 465 uses TLS

**Comment by karthikeyana** [comment]
thanks its working fine
