### ISSUE TITLE
how to install nodemailer

### ISSUE THREAD

**Issue by qinlinxin2080** [nodemailer/nodemailer#698]
1、npm install --save @types/nodemailer 
error: Installing @types/nodemailer@1.3.2Error: @types/nodemailer@1.3.2 not found
 at getMatchPackageFromAll (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:148:17)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
2、mynode versionis v6.9.1

**Comment by qinlinxin2080** [comment]
how ton include nodemailer for typescript.

**Comment by qinlinxin2080** [comment]
notarget No compatible version found: @types/nodemailer@1.3.2
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.3.32, 1.3.31, 1.3.30, 1.3.29, 1.3.28, 1.3.27-alpha, 1.3.26-alpha, 1.3.25-alpha, 1.3.24-alpha, 1.3.23-alpha, 1.3.22-alpha, 1.3.21-alpha, 1.3.16-alpha, 1.3.15-alpha

**Comment by andris9** [comment]
npm install --save nodemailer
