### ISSUE TITLE
TypeError: Cannot read property 'disableFileAccess' of undefined

### ISSUE THREAD

**Issue by EvgenyOrekhov** [nodemailer/nodemailer#723]
```
TypeError: Cannot read property 'disableFileAccess' of undefined
at MailMessage.forEach.key (/app/node_modules/nodemailer/lib/mailer/mail-message.js:38:41)
at Array.forEach (native)
at new MailMessage (/app/node_modules/nodemailer/lib/mailer/mail-message.js:36:51)
at Mail.sendMail (/app/node_modules/nodemailer/lib/mailer/index.js:132:20)
```

1. Nodemailer version: 3.0.0
2. Node.js version: 7.5.0
3. Your operating system: Alpine Linux 3.4
4. Nodemailer configuration settings:

```json
{
    "pool": true,
    "port": 25,
    "host": "localhost",
    "maxConnections": 5,
    "maxMessages": 100,
    "rateLimit": false,
    "disableFileAccess": true,
    "disableUrlAccess": true,
    "logger": true
}
```

**Comment by andris9** [comment]
Oh dang :( Fixed it and released as v3.0.1
