### ISSUE TITLE
Problem to send a signed mail with DKIM

### ISSUE THREAD

**Issue by georgesben** [nodemailer/nodemailer#732]
Hi everybody !

I have a little problem with nodemailer. I'm trying to send signed email. Unfortunately, I have an error but I don't understand why. Can someone help me, please ? :)

1. Nodemailer version you are having problems with (eg. v1.3.7): 3.0.2
2. Node.js version you are using (run `node -v` to see it, eg v5.5.0): 7.5.0
3. Your operating system (eg. Windows 10, Ubuntu 14.04 etc.): Windows 7 and Debian 8 (tested on these 2 OS)
4 and 5. Nodemailer configuration settings:
```javascript
const nodemailer = require("nodemailer");
const fs = require('fs');
let key = fs.readFileSync("./config/keys/dkim.private.key", "utf8");
let transporter = nodemailer.createTransport({
                logger: true,
                debug: true,
                sendmail: true,
                dkim: {
                    domaineName: "alexandrie.ovh",
                    keySelector: "default",
                    privateKey: key
                }
            });
            transporter.sendMail({
                from: 'noreply@alexandrie.ovh',
                to: destinataire,
                subject: 'Validation de votre inscription',
                text: `HELLO WORLD ! =D`
```
6. error logs:
```
punycode.js:73
        const parts = string.split('@');
                            ^

TypeError: Cannot read property 'split' of undefined
    at mapDomain (punycode.js:73:22)
    at Object.toASCII (punycode.js:406:9)
    at generateDKIMHeader (E:\Cours année 2015 - 2017\Mémoire\mookup\node_modules\nodemailer\lib\dkim\sign.js:57:25)
    at module.exports (E:\Cours année 2015 - 2017\Mémoire\mookup\node_modules\nodemailer\lib\dkim\sign.js:33:22)
    at signNextKey (E:\Cours année 2015 - 2017\Mémoire\mookup\node_modules\nodemailer\lib\dkim\index.js:114:29)
    at DKIMSigner.sendSignedOutput (E:\Cours année 2015 - 2017\Mémoire\mookup\node_modules\nodemailer\lib\dkim\index.js:128:20)
    at RelaxedBody.relaxedBody.on (E:\Cours année 2015 - 2017\Mémoire\mookup\node_modules\nodemailer\lib\dkim\index.js:190:18)
    at emitNone (events.js:91:20)
    at RelaxedBody.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by andris9** [comment]
`domaineName` is invalid

**Comment by georgesben** [comment]
Thanks for the explanation :) But I don't understand why it's invalid. I have checked the DNS propagation so normally, it should be good, isn't it ?
