### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by kire73** [nodemailer/nodemailer#736]
Updating to nodemailer 3.1.4
Node.js 4.6.1
npm 4.3.0

Updated npm packages and node. No issues until I updated nodemailer to 3.1.4. Error when running script @ require('nodemailer')

            compile: [(...args) => this._convertDataImages(...args)],
                       ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/nodemailer/lib/nodemailer.js:3:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/app.js:27:18) // var nodemailer = require('nodemailer')

Reverting to 2.7.0 works great

**Comment by andris9** [comment]
V3+ requires nodejs 6+
