### ISSUE TITLE
Nodemailer with Exchange's SMTP server.

### ISSUE THREAD

**Issue by Nepoxx** [nodemailer/nodemailer#742]
Include the following information with your issue:

1. Nodemailer version you are having problems with (eg. v1.3.7)
v3.1.4
2. Node.js version you are using (run `node -v` to see it, eg v5.5.0)
v6.9.1
3. Your operating system (eg. Windows 10, Ubuntu 14.04 etc.)
Tested on Arch and Windows 10
4. Nodemailer configuration settings
```javascript
const mailTransport = mailer.createTransport({
  debug: true,
  host: 'mail.mydomain.com',
  secureConnection: false, //also tried secure: false
  port: 587,
  tls: {cipher:'SSLv3'},
  auth: {
        user: 'ourdomain\\noreply',
        password: 'the password' //triple checked, even tried changing it to something very simple (without any special characters)
  }
})
```

This is the error I get:

```
{ Error: Invalid login: 535 5.7.3 Authentication unsuccessful
    at SMTPConnection._formatError (/home/user/nodejs/node_modules/nodemailer/lib/smtp-connection/index.js:555:19)
    at SMTPConnection._actionAUTHComplete (/home/user/nodejs/node_modules/nodemailer/lib/smtp-connection/index.js:1244:34)
    at SMTPConnection._responseActions.push.str (/home/user/nodejs/node_modules/nodemailer/lib/smtp-connection/index.js:1206:18)
    at SMTPConnection._processResponse (/home/user/nodejs/node_modules/nodemailer/lib/smtp-connection/index.js:702:20)
    at SMTPConnection._onData (/home/user/nodejs/node_modules/nodemailer/lib/smtp-connection/index.js:507:14)
    at TLSSocket._socket.on.chunk (/home/user/nodejs/node_modules/nodemailer/lib/smtp-connection/index.js:653:51)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
  code: 'EAUTH',
  response: '535 5.7.3 Authentication unsuccessful',
  responseCode: 535,
  command: 'AUTH LOGIN' }
```

I can use outlook's web access with the same user/password combination without any issue. Has anyone had success using NodeMailer with an MS Exchange SMTP mail server? Do you need any special configuration on the server?

Cheers

**Comment by andris9** [comment]
The auth property should be 'pass' not 'password'

**Comment by Nepoxx** [comment]
Yikes! So sorry about that! Thank you very much.

**Comment by kiknag** [comment]
Have you resolved the problem?

**Comment by AppHero2** [comment]
```
const transporter = nodemailer.createTransport({
        service: 'Gmail',
        auth: {
            user: 'xxxx@gmail.com', // generated ethereal user
            pass: 'xxxxxx' // generated ethereal password
        }
    });

    // setup email data with unicode symbols
    const mailOptions = {
        from: 'xxxx@gmail.com', // sender address
        to: 'apphero.software@gmail.com', // list of receivers
        subject: 'Hello ✔', // Subject line
        text: 'Hello world?', // plain text body
        html: '<b>Hello world?</b>' // html body
    };

    // send mail with defined transport object
    transporter.sendMail(mailOptions, (error, info) => {
        if (error) {
            return console.log(error);
        }
        console.log('Message sent: %s', info.messageId);
        // Preview only available when sending through an Ethereal account
        console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info));

    });    
```

{ Error: Invalid login: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbtg
534-5.7.14 FpgEpV7c_AZy6RbwIJ9AcDhWbaBxN_GngDwCqtZOHsJfoB5-MdIYh5H789LxOPTqToR6C4
534-5.7.14 3iJFq7XAO_lSbMuwMylHa5Xfwe2D_CTP5hA_1U3v9yhSBs9tUilL2A4h7J9DiH_cHtpUts
534-5.7.14 hCrfvQoTRDt3HSrD3YvqFEqtmWt7Adcq4T30obQ_yI9rVZ9uDh2VskhGczqCIJxs1LR9om
534-5.7.14 rCUjVo3mHZ3gKd9AoNPBPlyKFrkpaauaz6A08uDHdLMaBaGkm-> Please log in via
534-5.7.14 your web browser and then try again.
534-5.7.14  Learn more at
534 5.7.14  https://support.google.com/mail/answer/78754 i6-v6sm9985306pfo.107 - gsmtp
    at SMTPConnection._formatError (F:\WebApps\acua-cloud\node_modules\nodemailer\lib\smtp-connection\index.js:606:19)
    at SMTPConnection._actionAUTHComplete (F:\WebApps\acua-cloud\node_modules\nodemailer\lib\smtp-connection\index.js:1335:34)
    at SMTPConnection._responseActions.push.str (F:\WebApps\acua-cloud\node_modules\nodemailer\lib\smtp-connection\index.js:366:26)
    at SMTPConnection._processResponse (F:\WebApps\acua-cloud\node_modules\nodemailer\lib\smtp-connection\index.js:762:20)
    at SMTPConnection._onData (F:\WebApps\acua-cloud\node_modules\nodemailer\lib\smtp-connection\index.js:558:14)
    at TLSSocket._socket.on.chunk (F:\WebApps\acua-cloud\node_modules\nodemailer\lib\smtp-connection\index.js:510:47)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:597:20)
  code: 'EAUTH',
  response: '534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbtg\n534-5.7.14 FpgEpV7c_AZy6RbwIJ9AcDhWbaBxN_GngDwCqtZOHsJfoB5-MdIYh5H789LxOPTqToR6C4\n534-5.7.14 3iJFq7XAO_lSbMuwMylHa5Xfwe2D_CTP5hA_1U3v9yhSBs9tUilL2A4h7J9DiH_cHtpUts\n534-5.7.14 hCrfvQoTRDt3HSrD3YvqFEqtmWt7Adcq4T30obQ_yI9rVZ9uDh2VskhGczqCIJxs1LR9om\n534-5.7.14 rCUjVo3mHZ3gKd9AoNPBPlyKFrkpaauaz6A08uDHdLMaBaGkm-> Please log in via\n534-5.7.14 your web browser and then try again.\n534-5.7.14  Learn more at\n534 5.7.14  https://support.google.com/mail/answer/78754 i6-v6sm9985306pfo.107 - gsmtp',
  responseCode: 534,
  command: 'AUTH PLAIN' }

**Comment by AppHero2** [comment]
![image](https://user-images.githubusercontent.com/5608510/43358915-fb67d434-92cb-11e8-8e84-d645399e08fe.png)

**Comment by brianmak3** [comment]
You need to allow sign in from small app sources in your MS, check your email you will get a mail asking you to allow that.
