### ISSUE TITLE
Latest version breaks gmail with xoauth2 works with 2.7.2 ( using loopback framework )

### ISSUE THREAD

**Issue by cse-tushar** [nodemailer/nodemailer#743]
1. Nodemailer version 3.1.5 ( breaks ) and with 2.7.2 ( works great )
2. Node.js version v6.9.4
3. Your operating system Ubuntu 16.04
4. Nodemailer configuration settings

```
const nodemailer = require('nodemailer');
const xoauth2 = require('xoauth2');
const transport = {
    service: 'gmail',
    auth: {
      xoauth2: xoauth2.createXOAuth2Generator({
         "user": "johndoe@***.com",
         "clientId": "*******************************",
          "clientSecret": "*******************************",
          "refreshToken": "*******************************"
     }),
    },
};
const = email = nodemailer.createTransport(transport);
email.sendMail ( .... );
```
5.Using loopback framework
6. Error
```
{ Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 78sm14696732pfm.122 - gsmtp
    at SMTPConnection._formatError (/project/node_modules/nodemailer/lib/smtp-connection/index.js:555:19)
    at SMTPConnection._actionAUTHComplete (/project/node_modules/nodemailer/lib/smtp-connection/index.js:1244:34)
    at SMTPConnection._responseActions.push.str (/project/node_modules/nodemailer/lib/smtp-connection/index.js:338:26)
    at SMTPConnection._processResponse (/project/node_modules/nodemailer/lib/smtp-connection/index.js:702:20)
    at SMTPConnection._onData (/project/node_modules/nodemailer/lib/smtp-connection/index.js:507:14)
    at TLSSocket._socket.on.chunk (/project/node_modules/nodemailer/lib/smtp-connection/index.js:459:47)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:548:20)
  code: 'EAUTH',
  response: '535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials 78sm14696732pfm.122 - gsmtp',
  responseCode: 535,
  command: 'AUTH PLAIN' }
```
7. Have tried all the steps mentioned in the google support link didn't work.

**Comment by andris9** [comment]
Nodemailer v3 has some breaking changes regarding OAuth2. See the updated docs [here](https://nodemailer.com/smtp/oauth2/). There is no need for the external module anymore but that also changed the syntax

**Comment by mxgit1090** [comment]
So is the following usage of XOAuth2 now deprecated?
```js
var xoauth2 = require('xoauth2');
var auth = {
      xoauth2: xoauth2.createXOAuth2Generator({
         "user": "johndoe@***.com",
         "clientId": "*******************************",
          "clientSecret": "*******************************",
          "refreshToken": "*******************************"
     })
}
```

**Comment by andris9** [comment]
Yes. https://nodemailer.com/about/migrate/
