### ISSUE TITLE
ECONNREFUSED when bumping from 2.7.2 to 3.1.5

### ISSUE THREAD

**Issue by binarykitchen** [nodemailer/nodemailer#745]
When I ran my app on nodemailer's 2.7.2 version all went well, but when I bumped to 3.1.5, I am seeing this new ECONNREFUSED error

```
[2017-03-11 23:05:43] DEBUG Creating transport: nodemailer (3.1.5; +https://nodemailer.com/; SMTP/3.1.5[client:3.1.5])
12:05:43.129 DEBUG videomail.io@local.videomail.io: Initiate SMTP transport ...
[2017-03-11 23:05:43] DEBUG Sending mail using SMTP/3.1.5[client:3.1.5]
[2017-03-11 23:05:43] DEBUG Using 1 plugins for compile
[2017-03-11 23:05:43] ERROR [MrOpuAkKQQs] connect ECONNREFUSED 127.0.0.1:587
[2017-03-11 23:05:43] DEBUG [MrOpuAkKQQs] Closing connection to the server using "destroy"
[2017-03-11 23:05:43] ERROR Send Error: connect ECONNREFUSED 127.0.0.1:587
12:05:43.142 ERROR videomail.io@local.videomail.io: connect ECONNREFUSED 127.0.0.1:587 (err.code=ECONNECTION)
    Error: connect ECONNREFUSED 127.0.0.1:587
        at Object.exports._errnoException (util.js:1033:11)
        at exports._exceptionWithHostPort (util.js:1056:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1105:14)
```

Rest assured I studied the changelog and found no code changes were needed. But here are the relevant code lines:

```
    const smtpTransport = nodemailer.createTransport({
        secure: false,
        tls: {
            rejectUnauthorized: false
        }
    })

    smtpTransport.use('compile', htmlToText())

    smtpTransport.sendMail(options, function(err, info) { 
        ...
    }
```

Btw, running on Ubuntu 16.10 and nodejs 7.7.2

Any clues what this could be?

**Comment by andris9** [comment]
You need to provide the port option. The newer version defaults to 587, older one to 25

**Comment by binarykitchen** [comment]
ah, that explains - thanks!
