### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by topada** [nodemailer/nodemailer#754]
nodemailer 3.1.8
npm 3.10.8
node v7.0.0
Linux CentOS release 6.8 (Final) (uberspace.de)

---
I'm trying to run nodemailer but I had an error crashing node, I'm struggling to understand why

```
 /home/topada/nd-kk/node_modules/nodemailer/lib/mailer/index.js:31
             compile: [(...args) => this._convertDataImages(...args)],
                        ^^^

 SyntaxError: Unexpected token ...
     at exports.runInThisContext (vm.js:53:16)
     at Module._compile (module.js:373:25)
     at Object.Module._extensions..js (module.js:416:10)
     at Module.load (module.js:343:32)
     at Function.Module._load (module.js:300:12)
     at Module.require (module.js:353:17)
     at require (internal/module.js:12:17)
     at Object.<anonymous> (/home/topada/nd-kk/node_modules/nodemailer/lib/nodemailer.js:3:16)
     at Module._compile (module.js:409:26)
     at Object.Module._extensions..js (module.js:416:10)
     at Module.load (module.js:343:32)
     at Function.Module._load (module.js:300:12)
     at Module.require (module.js:353:17)
     at require (internal/module.js:12:17)
     at Object.<anonymous> (/home/topada/nd-kk/routes/mailing.js:2:19)
     at Module._compile (module.js:409:26)
```

I already checked http://node.green/ node 7.0.0 seems to be capable of the spread operator. 
Running this locally works just fine. 

nodemailer 3.1.8
npm 4.0.5
node v7.4.0
Mac OS El Capitan 10.11.6

– I already downgraded node from 7.5.0 to 7.0.0 on the remote system.
– I removed node_modules, cleaned the npm cache and reinstalled with npm install.

Help is much appreciated!

**Comment by andris9** [comment]
Whats the output for this:

    console.log(process.versions)

**Comment by andris9** [comment]
Be sure to run the check the same way you run the script that errors. Sometimes there are multiple node versions installed and which one is used depends on the context

**Comment by topada** [comment]
@andris9 thanks for the quick response!

```
{ http_parser: '2.7.0',
node: '4.7.3',
v8: '4.5.103.43',
 uv: '1.9.1',
zlib: '1.2.8',
ares: '1.10.1-DEV',
modules: '46',
openssl: '1.0.2k' }
```

**node: '4.7.3'** Why? I also have the "right" node version im my package json:
```
...
  "engines": {
    "node": "7.0.0",
    "npm": "3.10.8"
  }
```

talking about contexts, what am I missing? :)

**Comment by topada** [comment]
@andris9 thank you for pointing me in the right direction! the daemon running node on the server was in the wrong node context. Back to **7.5.0**! Everything is working.
