### ISSUE TITLE
Cannot read property 'getSocket' of undefined

### ISSUE THREAD

**Issue by keith24** [nodemailer/nodemailer#759]
I'm running into trouble, and have no idea why.  

### Versions
nodemailer v3.1.8
node v6.10.2
Ubuntu 16.04

## Error
```
SMTP ready...
/path/to/project/node_modules/nodemailer/lib/mailer/index.js:127
        if (typeof this.getSocket === 'function') {
                       ^
TypeError: Cannot read property 'getSocket' of undefined
    at sendMail (/path/to/project/node_modules/nodemailer/lib/mailer/index.js:127:24)    at /path/to/project/main.js:3:0
```

## Simplified code

**mail.js**
```javascript
'use strict';

const nodemailer = require('nodemailer');

let transporter = nodemailer.createTransport({
  host: 'REDACTED',
  port: 587,
  secure: false,
  requireTLS: true,
  auth: {
    user: 'REDACTED',
    pass: 'REDACTED'
  },
});

transporter.verify(function(err, success) {
  if (err){ console.error(`SMTP Error: ${err}`); }
  if (success){
    console.log("SMTP ready...");
  } else {
    console.error("SMTP not ready!");
  }
});

module.exports = transporter.sendMail;
```

**main.js**
```javascript
const mail = require('./mail.js');

mail({
  to: 'REDACTED',
  from: 'REDACTED',
  subject: 'REDACTED',
  text: 'REDACTED',
  html: 'REDACTED'
}).then(function(){
  console.log('success!');
}).catch(function(err){
  next(err);
});
```

**Comment by andris9** [comment]
Your code looses the `this` context when exporting. Change the last line in mail.js to this

    module.exports = transporter.sendMail.bind(transporter);

And read some tutorials how objects in Javascript work, for example [this article](https://www.smashingmagazine.com/2014/01/understanding-javascript-function-prototype-bind/) about bind.
