### ISSUE TITLE
Core bug in SMTP connection (binds infinite error handlers)

### ISSUE THREAD

**Issue by niftylettuce** [nodemailer/nodemailer#804]
I noticed this issue while writing tests:

```sh
Error: too many listeners of type "error" added to EventEmitter. Max is 10 and we've added 45.
    at LeWindows.newAddListener (/Users/niftylettuce/Public/email-tests/node_modules/throw-max-listeners-error/index.js:12:17)
    at LeWindows.Readable.on (_stream_readable.js:761:35)
    at SMTPConnection.send (/Users/niftylettuce/Public/email-tests/node_modules/nodemailer/lib/smtp-connection/index.js:405:21)
    at connection.connect (/Users/niftylettuce/Public/email-tests/test/test.js:125:24)
    at SMTPConnection.once (/Users/niftylettuce/Public/email-tests/node_modules/nodemailer/lib/smtp-connection/index.js:185:17)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at SMTPConnection.emit (events.js:207:7)
    at SMTPConnection._actionEHLO (/Users/niftylettuce/Public/email-tests/node_modules/nodemailer/lib/smtp-connection/index.js:1099:14)
    at SMTPConnection._processResponse (/Users/niftylettuce/Public/email-tests/node_modules/nodemailer/lib/smtp-connection/index.js:733:20)
    at SMTPConnection._onData (/Users/niftylettuce/Public/email-tests/node_modules/nodemailer/lib/smtp-connection/index.js:529:14)
    at TLSSocket._socket.on.chunk (/Users/niftylettuce/Public/email-tests/node_modules/nodemailer/lib/smtp-connection/index.js:680:51)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at TLSSocket.Readable.push (_stream_readable.js:197:10)
    at TLSWrap.onread (net.js:589:20)
Uncaught Exception: test/test.js
  Error: too many listeners of type "error" added to EventEmitter. Max is 10 and we've added 34.
    LeWindows.newAddListener (node_modules/throw-max-listeners-error/index.js:12:17)
    SMTPConnection.send (node_modules/nodemailer/lib/smtp-connection/index.js:405:21)
    connection.connect (test/test.js:125:24)
    SMTPConnection.once (node_modules/nodemailer/lib/smtp-connection/index.js:185:17)
    SMTPConnection._actionEHLO (node_modules/nodemailer/lib/smtp-connection/index.js:1099:14)
    SMTPConnection._processResponse (node_modules/nodemailer/lib/smtp-connection/index.js:733:20)
    SMTPConnection._onData (node_modules/nodemailer/lib/smtp-connection/index.js:529:14)
    TLSSocket._socket.on.chunk (node_modules/nodemailer/lib/smtp-connection/index.js:680:51)
```

I determined it to be this block of code:

<https://github.com/nodemailer/nodemailer/blob/master/lib/smtp-connection/index.js#L404-L406>

Shouldn't we check if this listener already exists before binding it?  Or re-create it and unbind the old event?

Not sure if this exists elsewhere too in the codebase, haven't checked yet.

My usage for this test was that I was composing a message and sending it through a new SMTP connection:

```js
  const info = await transporter.sendMail({
    from: 'foo@foo.net',
    to: 'baz@baz.net',
    subject: 'test',
    text: 'test text',
    html: '<strong>test html</strong>'
  });

  let failed = 0;

  await Promise.all(
    Array.from(Array(200).keys()).map(() => {
      return new Promise(async (resolve, reject) => {
        try {
          const connection = new Client({ port, tls });
          connection.on('end', resolve);
          connection.connect(() => {
            connection.send(info.envelope, info.message, err => {
              if (err && err.responseCode === 451) failed++;
              connection.quit();
            });
          });
        } catch (err) {
          reject(err);
        }
      });
    })
  );
```

The error occurred because `info.message` has a function bound to it of `on`.

**Comment by niftylettuce** [comment]
The `on` function is inherited through `sendMail` which inherits from `stream`.

```js
const stream = require('stream');
const Transform = stream.Transform;
```

**Comment by niftylettuce** [comment]
I noticed that I'm not defining the new message inside the loop, which is why I get this error. 😆 

As soon as I put this block inside the loop, it works fine.

```js
const info = await transporter.sendMail({
    from: 'foo@foo.net',
    to: 'baz@baz.net',
    subject: 'test',
    text: 'test text',
    html: '<strong>test html</strong>'
  });
```

Duh 🤣
