### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Parser-Error** [nodemailer/nodemailer#855]
hi, i have this configuration : 
const transporter = nodemailer.createTransport({
  host: 'domaine.tld',
  port: 25,
  secure: false,
  secureConnection: false,
  auth: {
    user: 'name@domaine.tls',
    pass: 'password'
  },
  tls: {
    rejectUnauthorized: false
  }
})

-------------------------------------------
My error : 
-------------------------------------------
{ Error: Invalid greeting from server:
421 Cannot connect to SMTP server MY-IP-NUMBER (MY-IP-NUMBER:25), connect error 10060: 421 Cannot connect to SMTP server MY-IP-NUMBER (MY-IP-NUMBER:25), connect error 10060
    at SMTPConnection._actionGreeting (C:\Users\Parser.Error\Documents\Programmation\Logiciel facturation\server\node_modules\nodemailer\lib\smtp-connection\index.js:1004:27)
    at SMTPConnection._processResponse (C:\Users\Parser.Error\Documents\Programmation\Logiciel facturation\server\node_modules\nodemailer\lib\smtp-connection\index.js:747:20)
    at SMTPConnection._onData (C:\Users\Parser.Error\Documents\Programmation\Logiciel facturation\server\node_modules\nodemailer\lib\smtp-connection\index.js:543:14)
    at Socket._socket.on.chunk (C:\Users\Parser.Error\Documents\Programmation\Logiciel facturation\server\node_modules\nodemailer\lib\smtp-connection\index.js:495:47)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:599:20)
  code: 'EPROTOCOL',
  response: '421 Cannot connect to SMTP server MY-IP-NUMBER (MY-IP-NUMBER:25), connect error 10060',
  responseCode: 421,
  command: 'CONN' }
-------------------------------------------------
Why this error ?
-------------------------------------------------

**Comment by andris9** [comment]
This is most probably a firewall issue. Check that your machine can open port 25 to your server.
