### ISSUE TITLE
NodeMailer mailgun service - Getting greetings never received error

### ISSUE THREAD

**Issue by thesukhpreetsingh** [nodemailer/nodemailer#867]
var nodemailer      = require('nodemailer');

var transporter     = nodemailer.createTransport({
.....service: 'Mailgun',
.....auth: {
.....,.....user : 'postmaster@website.com', //Mailgun Username
.....,.....pass : 'thePasswordForMailgunUserName'  // Mailgun Password
.....}
});

Sometimes it works beautifully without any errors. **But Sometimes I get lots of errors of** 

**{ Error: Greeting never received**
    at SMTPConnection._formatError (/home/myprojectfolder/project/node_modules/nodemailer/lib/smtp-connection/index.js:557:19)
    at SMTPConnection._onError (/home/myprojectfolder/project/node_modules/nodemailer/lib/smtp-connection/index.js:530:20)
    at Timeout._greetingTimeout.setTimeout (/home/myprojectfolder/project/node_modules/nodemailer/lib/smtp-connection/index.js:471:22)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5) code: 'ETIMEDOUT', command: 'CONN' }

How to get over this. What improvements can I make to the given code. 
Please Help.

**Comment by andris9** [comment]
Try to not send too many emails at once. Also check your network throughput.

**Comment by thesukhpreetsingh** [comment]
Network works absolutely  fine though.... And I send around 25k emails at a time

**Comment by andris9** [comment]
Send the emails in slower pace or use SMTP [pooling option](https://nodemailer.com/smtp/pooled/)

**Comment by thesukhpreetsingh** [comment]
Ok. Thankyou Andris9. :smile: 
Can you please recommend some settings for optimum performance (by using poling options) and high reliability to send emails without any such errors? it would be really helpful of you.

**Comment by andris9** [comment]
You have to test. Start with defaults and modify if it is too slow (increase valies) or still gives errors (decrease values)
