### ISSUE TITLE
Ethereal Integration Issue: `Error: Greeting never received`

### ISSUE THREAD

**Issue by derekhubbard** [nodemailer/nodemailer#881]
When trying to create a transport and send email to an Ethereal test account, the call to `sendMail` is raising the error `Greeting never received`. 

I have tried using both a "callback approach" and also an "async/await" approach, but the same error is thrown in both scenarios. Both examples are pretty much straight from the working examples in the Nodemailer documentation. Maybe I'm missing something simple? :)

Here is the "callback approach" code that is producing the error:  
```
    it('can send email with a dynamic test account', done => {
        nodemailer.createTestAccount((err, account) => {
            const transporter = nodemailer.createTransport({
                host: 'smtp.ethereal.email',
                port: 587,
                auth: {
                    user: account.user, // generated ethereal user
                    pass: account.pass // generated ethereal password
                }
            });

            const mailOptions = {
                from: '"Fred Foo 👻" <foo@example.com>', // sender address
                to: 'bar@example.com, baz@example.com', // list of receivers
                subject: 'Hello ✔', // Subject line
                text: 'Hello world?', // plain text body
                html: '<b>Hello world?</b>' // html body
            };

            // send mail with defined transport object
            transporter.sendMail(mailOptions, (error, info) => {
                if (error) {
                    return console.log(error);
                }
                console.log('Message sent: %s', info.messageId);
                console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info));
                // Message sent: <b658f8ca-6296-ccf4-8306-87d57a0b4321@example.com>
                // Preview URL: https://ethereal.email/message/WaQKMgKddxQDoou...

                done();
            });
        });
    }).timeout(10000);
```

And here is the stacktrace of the error:
```
{ Error: Greeting never received
    at SMTPConnection._formatError (/Users/<username>/projects/personal/learning-tests/javascript/nodemailer/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
    at SMTPConnection._onError (/Users/<username>/projects/personal/learning-tests/javascript/nodemailer/node_modules/nodemailer/lib/smtp-connection/index.js:579:20)
    at Timeout._greetingTimeout.setTimeout (/Users/<username>/projects/personal/learning-tests/javascript/nodemailer/node_modules/nodemailer/lib/smtp-connection/index.js:520:22)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) code: 'ETIMEDOUT', command: 'CONN' }
```

And some additional info: 
node version: `8.11.2`
nodemailer version: `4.6.4`
operating system: `OSX version 10.12.6`

**Comment by phagunbaya** [comment]
+1

**Comment by andris9** [comment]
Sometimes ethereal.email is just down, I don't have the means to keep it up 100%

**Comment by boudhayan-dev** [comment]
Hi,
Facing the same issue. Any way to confirm if the service is up ?

**Comment by fybwid** [comment]
> Hi,
> Facing the same issue. Any way to confirm if the service is up ?

[To check the Ethereal service status](https://status.ethereal.email/)
