### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Invalid login: 534-5.7.14

### ISSUE THREAD

**Issue by StarNeit** [nodemailer/nodemailer#895]
Hello. I am getting this error, and it is common issue which was fixed before.
But, I am not sure how to solve this for several hours.
Localhost works, but it doesn't work on server(ubuntu).
Any idea?

(node:14878) UnhandledPromiseRejectionWarning: Error: Invalid login: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbuS
[0] 534-5.7.14 ERjTDKGthdfTZ9nKMdRiULTnI_hiLr-10lno1RM2c62mu2y1JMF9FJz1idod5ONhJXimap
[0] 534-5.7.14 FrB0ZIsiD-Pb-g3KrpwomtKLddzGWkWa4Z0M1RARZyiGiEl6vxKpcEELpST0CXK_0oULnm
[0] 534-5.7.14 SMuos1iqpk2WqPz-h6V4fcxpBWhF9u1-1etTqlNBgo83On8RW4OU6NZZHtsvOOdx75UzD5
[0] 534-5.7.14 lxvo83ACwPG5kHSPLte5c1zmvA3Sk> Please log in via your web browser and
[0] 534-5.7.14 then try again.
[0] 534-5.7.14  Learn more at
[0] 534 5.7.14  https://support.google.com/mail/answer/78754 p12-v6sm14154254pfi.175 - gsmtp
[0]     at SMTPConnection._formatError (/var/www/cabcoin/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
[0]     at SMTPConnection._actionAUTHComplete (/var/www/cabcoin/node_modules/nodemailer/lib/smtp-connection/index.js:1335:34)
[0]     at SMTPConnection._responseActions.push.str (/var/www/cabcoin/node_modules/nodemailer/lib/smtp-connection/index.js:366:26)
[0]     at SMTPConnection._processResponse (/var/www/cabcoin/node_modules/nodemailer/lib/smtp-connection/index.js:762:20)
[0]     at SMTPConnection._onData (/var/www/cabcoin/node_modules/nodemailer/lib/smtp-connection/index.js:558:14)
[0]     at TLSSocket._socket.on.chunk (/var/www/cabcoin/node_modules/nodemailer/lib/smtp-connection/index.js:709:51)
[0]     at emitOne (events.js:116:13)
[0]     at TLSSocket.emit (events.js:211:7)
[0]     at addChunk (_stream_readable.js:263:12)
[0]     at readableAddChunk (_stream_readable.js:250:11)
[0]     at TLSSocket.Readable.push (_stream_readable.js:208:10)
[0]     at TLSWrap.onread (net.js:597:20)
[0] (node:14878) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[0] (node:14878) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Thank you.

**Comment by StarNeit** [comment]
I am using gmail account for SMTP.

https://myaccount.google.com/lesssecureapps

Already tried this one, but no luck yet.

**Comment by andris9** [comment]
Thats just how Gmail works, there's nothing to change or fix in Nodemailer

**Comment by antzshrek** [comment]
You might wanna check this [solution](https://stackoverflow.com/a/53085002/7905714) out. It should help.
