### ISSUE TITLE
Not able to send mail via outlook client

### ISSUE THREAD

**Issue by shubham-srivastava-goku** [nodemailer/nodemailer#900]
Not able to send mail through outlook client. I tried with gmail and was able to send the mail using it. Now I am trying to support outlook too but getting below error

Config:

	{
		"host": "smtp-mail.outlook.com",
		"secureConnection": false,
		"port": 587,
		"tls": {
			"ciphers": "SSLv3"
		},
		"auth": {
			"user": "myusername@outlook.com",
			"pass": "mypass"
		}
	}

Mail Option:

	let mailOptions = {
		from: "myusername@outlook.com",
		to: "myotheremail@gmail.com",
		subject: "Yolo",
		html: "<h3>Outlook mail.</h3>",
	};

Code:

	const transport = nodemailer.createTransport(config);

	transport.sendMail(mailOptions, (error, info) => {
		if (error) {
			return console.log("error : ", error);
		}

		console.log('Message sent: ', info);
	});

Error: 

	{ 
		Error: read ECONNRESET
			at _errnoException (util.js:1022:11)
			at TCP.onread (net.js:628:25)
		code: 'ECONNECTION',
		errno: 'ECONNRESET',
		syscall: 'read',
		command: 'CONN' 
	}

**Comment by andris9** [comment]
Remove the `tls` and `secureConnection` properties from config. Also make sure your firewall allows connections from your machine to port 587.

**Comment by shubham-srivastava-goku** [comment]
I've removed tls and scecureConnection properties and made sure my firewall allows the connections and I assure you the username and password is also correct.
But still I am getting below error:

error :  { Error: Invalid login: 535 5.7.3 Authentication unsuccessful [PN1PR0101CA0025.INDPRD01.PROD.OUTLOOK.COM]
      at SMTPConnection._formatError (/Users/sdk/Desktop/Shubham/Node_Apps/EmailClient/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
      at SMTPConnection._actionAUTHComplete (/Users/sdk/Desktop/Shubham/Node_Apps/EmailClient/node_modules/nodemailer/lib/smtp-connection/index.js:1335:34)
      at SMTPConnection._responseActions.push.str (/Users/sdk/Desktop/Shubham/Node_Apps/EmailClient/node_modules/nodemailer/lib/smtp-connection/index.js:1293:18)
      at SMTPConnection._processResponse (/Users/sdk/Desktop/Shubham/Node_Apps/EmailClient/node_modules/nodemailer/lib/smtp-connection/index.js:762:20)
      at SMTPConnection._onData (/Users/sdk/Desktop/Shubham/Node_Apps/EmailClient/node_modules/nodemailer/lib/smtp-connection/index.js:558:14)
      at TLSSocket._socket.on.chunk (/Users/sdk/Desktop/Shubham/Node_Apps/EmailClient/node_modules/nodemailer/lib/smtp-connection/index.js:709:51)
      at TLSSocket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:283:12)
      at readableAddChunk (_stream_readable.js:264:11)
      at TLSSocket.Readable.push (_stream_readable.js:219:10)
    code: 'EAUTH',
    response:
     '535 5.7.3 Authentication unsuccessful [PN1PR0101CA0025.INDPRD01.PROD.OUTLOOK.COM]',
    responseCode: 535,
    command: 'AUTH LOGIN' }

Please help me, if anyone have a solution for this
