### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by nir-jas** [nodemailer/nodemailer#915]
{ Error: Connection timeout
at SMTPConnection._formatError (/var/www/html/project/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
at SMTPConnection._onError (/var/www/html/project/node_modules/nodemailer/lib/smtp-connection/index.js:579:20)
at Timeout._connectionTimeout.setTimeout at ontimeout (timers.js:482:11)
at tryOnTimeout (timers.js:317:5)
at Timer.listOnTimeout (timers.js:277:5) code: 'ETIMEDOUT', command: 'CONN' }

**Comment by andris9** [comment]
Probably an issue with your firewall
