### ISSUE TITLE
Error: connect ETIMEDOUT 221.176.9.170:587

### ISSUE THREAD

**Issue by aunhappy** [nodemailer/nodemailer#918]
It does work when host is smtp.139.com.
here is the error message:
{ Error: connect ETIMEDOUT 221.176.9.170:587
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ECONNECTION',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '221.176.9.170',
  port: 587,
  command: 'CONN' }

**Comment by andris9** [comment]
Timeout usually means firewall issues
