### ISSUE TITLE
Error : Greeting never received

### ISSUE THREAD

**Issue by kdthanvi** [nodemailer/nodemailer#928]
I tried to use nodemailer for sending emails to gmail (& ethereal), but no luck.
Then I just copied the sample code give at [nodemailer.com](https://nodemailer.com/about/) (below is the transporter) : 
```nodemailer.createTestAccount((err, account) => {
    // create reusable transporter object using the default SMTP transport
    let transporter = nodemailer.createTransport({
        host: 'smtp.ethereal.email',
        port: 587,
        secure: false, // true for 465, false for other ports
        auth: {
            user: account.user, // generated ethereal user
            pass: account.pass // generated ethereal password
        }
    });
```
But I am getting the `Error : Greeting never received` as below :

```
my-mac:2 karan.thanvi$ node index.js 
{ Error: Greeting never received
    at SMTPConnection._formatError (/Users/karan.thanvi/Desktop/testtest/2/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
    at SMTPConnection._onError (/Users/karan.thanvi/Desktop/testtest/2/node_modules/nodemailer/lib/smtp-connection/index.js:579:20)
    at Timeout._greetingTimeout.setTimeout (/Users/karan.thanvi/Desktop/testtest/2/node_modules/nodemailer/lib/smtp-connection/index.js:520:22)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5) code: 'ETIMEDOUT', command: 'CONN' }
^C
my-mac:2 karan.thanvi$
```
Below are the exact steps I followed :
1. `npm init`      // used all default;
2. `npm install nodemailer --save`
3. Copied sample code given at nodemailer.com to index.js
4. `node index.js`

Below is version details :
1. OS : `macOS Sierra Version10.12.6 (16G1510)`
2. node : `v8.10.0`
3. nodemailer : `4.6.8`

PS : I checked many other issues for this but didn't find any working solution.

Could you please help me here?
Thanks!

**Comment by andris9** [comment]
ethereal.email server is sometimes just down.

**Comment by pathansalman805** [comment]
is there any alternative server to ethereal.email server
