### ISSUE TITLE
accessToken expiring?

### ISSUE THREAD

**Issue by colouredFunk** [nodemailer/nodemailer#941]
Following the steps outlined here - Nodemailer/Gmail - What exactly is a refresh token and how do I get one? all works as expected, however it seems the accessToken keeps expiring. I get the following error.

```
{ Error: Invalid status code 400
    at ClientRequest.req.on.res (/node_modules/nodemailer/lib/fetch/index.js:221:23)
    at emitOne (events.js:116:13)
```

Code snippet
```

    let transporter = nodeMailer.createTransport({
        host: 'smtp.gmail.com',
        port: 465,
        secure: true,
        auth: {
            type: 'OAuth2',
            user: '123@gmail.com',
            clientId: '123.apps.googleusercontent.com',
            clientSecret: '123',
            refreshToken: '123',
            accessToken: 'abc'
        }
    });

 let mailOptions = {
        from: 'from@gmail.com', // sender address
        to: 'send@gmail.com', // list of receivers
        subject: 'contact form', // Subject line
        text: '222', // plain text body
        html: '<p>Name:'+ req.body.name + '</p><p>Company: '+ req.body.company + '</p><p>Email: '+ req.body.email + '</p><p>Message: '+ req.body.message + '</p>'
    };

transporter.sendMail(mailOptions, (error, info) => {
        if (error) {
            res.status(400).json({
                status: "error",
                details: error
            })
        }
        res.status(200).json({
            status: "success"
        })
    });

```
If I generate a new accessToken everything works again as expected... What am I doing wrong? It's not exactly an ideal solution.

**Comment by andris9** [comment]
Oauth2 accessToken from Gmail is valid for an hour after what you need to generate a new one using a valid refreshToken
