### ISSUE TITLE
cannot login to google

### ISSUE THREAD

**Issue by Paul52Games** [nodemailer/nodemailer#946]
I try to login to google to send a mail. this is my code: 
```js
var nodemailer = require('nodemailer');
var transporter = nodemailer.createTransport({
  host: 'smtp.gmail.com',
  port: 465,
  secure: false,
  auth: {
    user: 'MAIL1',
    pass: 'PASSWORD1'
  }
});
var mailOptions = {
  from: 'MAIL1',
  to: 'MAIL2',
  subject: 'Sending Email using Node.js',
  text: 'That was easy!'
};
transporter.sendMail(mailOptions, function(error, info){
  if (error) {
    console.log(error);
  } else {
    console.log('Email sent: ' + info.response);
  }
});
```
I get this error: 
```js
{ Error: Greeting never received
    at SMTPConnection._formatError (C:\Users\Paul\Desktop\Paul\websites\website-leren\node_modules\nodemailer\lib\smtp-connection\index.js:606:19)
    at SMTPConnection._onError (C:\Users\Paul\Desktop\Paul\websites\website-leren\node_modules\nodemailer\lib\smtp-connection\index.js:579:20)
    at Timeout._greetingTimeout.setTimeout (C:\Users\Paul\Desktop\Paul\websites\website-leren\node_modules\nodemailer\lib\smtp-connection\index.js:520:22)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10) code: 'ETIMEDOUT', command: 'CONN' }
```

When i use port **587**, i get this error: 
```js
{ Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:635:8) code: 'ESOCKET', command: 'CONN' }
```
When i was searching on the internet, i saw the same error at someone else. The fix for that was to set rejectUnauthorized to false. So i added that at the **createTransport**: 
```js
  tls: {
    rejectUnauthorized: false
  }
```
But then i'm getting an error from google: 
```js
{ Error: Invalid login: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbs0
534-5.7.14 IQx_sIuAJCA03pZjX9FunDCkcIuhFyyQptDPjiPZOvzZPKTHuBNirlDfj1ByK4WLLBrQBH
534-5.7.14 BFNlIK0Rr0GIeBgp3lzgoAqLbeLtTTjiVf_qn8sJi6fY4u0ln2O2zsJsIOTZOWF3ZETZMU
534-5.7.14 9KwCOHvLhrVERfxwkzBbDg06TtTORlHtCFGJl5HipDIK8TefuXgp92iFkH8PLP0lrJuMFA
534-5.7.14 KTqCfXpO6ii5TumS5rb8co91Z0V6TTRcbpIq1HZsP36JlBeTGE> Please log in via
534-5.7.14 your web browser and then try again.
534-5.7.14  Learn more at
534 5.7.14  https://support.google.com/mail/answer/78754 b139-v6sm3917202wmd.36 - gsmtp
    at SMTPConnection._formatError (C:\Users\Paul\Desktop\Paul\websites\website-leren\node_modules\nodemailer\lib\smtp-connection\index.js:606:19)
    at SMTPConnection._actionAUTHComplete (C:\Users\Paul\Desktop\Paul\websites\website-leren\node_modules\nodemailer\lib\smtp-connection\index.js:1335:34)
    at SMTPConnection._responseActions.push.str (C:\Users\Paul\Desktop\Paul\websites\website-leren\node_modules\nodemailer\lib\smtp-connection\index.js:366:26)
    at SMTPConnection._processResponse (C:\Users\Paul\Desktop\Paul\websites\website-leren\node_modules\nodemailer\lib\smtp-connection\index.js:762:20)
    at SMTPConnection._onData (C:\Users\Paul\Desktop\Paul\websites\website-leren\node_modules\nodemailer\lib\smtp-connection\index.js:558:14)
    at TLSSocket._socket.on.chunk (C:\Users\Paul\Desktop\Paul\websites\website-leren\node_modules\nodemailer\lib\smtp-connection\index.js:709:51)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:219:10)
  code: 'EAUTH',
  response:
   '534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbs0\n534-5.7.14 IQx_sIuAJCA03pZjX9FunDCkcIuhFyyQptDPjiPZOvzZPKTHuBNirlDfj1ByK4WLLBrQBH\n534-5.7.14 BFNlIK0Rr0GIeBgp3lzgoAqLbeLtTTjiVf_qn8sJi6fY4u0ln2O2zsJsIOTZOWF3ZETZMU\n534-5.7.14 9KwCOHvLhrVERfxwkzBbDg06TtTORlHtCFGJl5HipDIK8TefuXgp92iFkH8PLP0lrJuMFA\n534-5.7.14 KTqCfXpO6ii5TumS5rb8co91Z0V6TTRcbpIq1HZsP36JlBeTGE> Please log in via\n534-5.7.14 your web browser and then try again.\n534-5.7.14  Learn more at\n534 5.7.14  https://support.google.com/mail/answer/78754 b139-v6sm3917202wmd.36 - gsmtp',
  responseCode: 534,
  command: 'AUTH PLAIN' }
```
So i went to https://support.google.com/mail/answer/78754 and did everything, but the error stays. 

I was searching, and then i saw that you can use `service: "gmail"`. But then i get the error `self signed certificate in certificate chain`. If i set the rejectUnauthorized to false, i get the error above.

I have viewd more that 100 pages for help, but i can't find a fixt for this. So maby it's a bug?

System information:
```
NodeJS version: v10.3.0
Nodemailer version: 4.6.8
Windows 10 home, 10.0.17134 Build 17134 - Lenovo
Processor: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz, 2701 MHz, 2 core('s) (64 bit)
Ram: 8GB (7.90)
```

**Comment by abtx** [comment]
Same issue here, and `IMAP access` is enabled on my Google account.

**Comment by abtx** [comment]
Ok, I found what the issue is about. Long story short, gmail is designed for the basic login to be used by humans, not apps. That's why it's blocking access. You can turn on `Less secure`, but you'd be better off using another client or using different auth method. Read this for more details: https://community.nodemailer.com/using-gmail/

**Comment by dimitrisal** [comment]
I had the same issue as you did.
There is a new thing in google, if you have enabled a two-face authentication you need to create a unique password for the app. Follow this guide and may help you https://support.google.com/accounts/answer/185833?p=InvalidSecondFactor&visit_id=636970561757473916-2582083923&rd=1

**Comment by EmmanuelSkapple** [comment]
I have had several times the same, sometimes it is simply necessary to loggearte from the browser, and then you can send the email.

  var smtpConfig = {
  host: 'smtp.gmail.com',
  port: 465,
  secure: true, // use SSL
  auth: {
       user:'my-email',
       pass:'my-password'
        }
  };
this is my config obj, you can put the secure in : true.
