### ISSUE TITLE
nodemailer for office365 does not work with me!

### ISSUE THREAD

**Issue by Alex1233456** [nodemailer/nodemailer#949]
i am trying to send email of office365 through nodemailder. 
i already posted it in Stack.O.V but no answer!
i get this error, please help me: { Error: Invalid login: Mailbox cannot be accessed

code: 'EAUTH', response: Mailbox cannot be accessed [CWXP265CA0023.GBRP265.PROD.OUTLOOK.COM]', responseCode: 550, command: 'AUTH LOGIN' }

> ar nodemailer = require('nodemailer');
var transporter = nodemailer.createTransport({
    host: "smtp.office365.com", // hostname
    proxy:"Proxy of the company",
    secureConnection: false, 
    port: 587, 
    tls: {
       ciphers:'SSLv3'
    },
    auth: {
        user: 'MYEMAIL@COMPANYNAME.com',
        pass: 'MYPASS'
    }
});

// setup e-mail data, even with unicode symbols
var mailOptions = {
    from: 'MYEMAIL@COMPANYNAME.com', // sender address (who sends)
    to: 'MYEMAIL@COMPANYNAME.com', // list of receivers (who receives)
    subject: 'Hello ', // Subject line
    text: 'Hello world ', // plaintext body
    html: '<b>Hello world </b><br> This is the first email sent with Nodemailer in Node.js' // html body
};

// send mail with defined transport object
transporter.sendMail(mailOptions, function(error, info){
    if(error){
        return console.log(error);
    }

    console.log('Message sent: ' + info.response);
});'

**Comment by thinkMX** [comment]
same problem here

**Comment by kishoreaoe** [comment]
@thinkMX , I am trying to access the webmail smtp mail box, Even thought i am giving the correct credentials am getting Authentication Unsuccessful. Could you please help me out in this issue:

**Comment by kishoreaoe** [comment]
[2018-11-01 07:31:59] DEBUG Creating transport: nodemailer (4.6.8; +https://nodemailer.com/; SMTP/4.6.8[client:4.6.8])
[2018-11-01 07:31:59] DEBUG Sending mail using SMTP/4.6.8[client:4.6.8]
[2018-11-01 07:31:59] INFO  [w4B127kKzOs] Connection established to 10.129.150.17:25
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 220 <domailname> Microsoft ESMTP MAIL Service ready at Thu, 1 Nov 2018 10:31:58 +0300
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] C: EHLO [127.0.0.1]
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-<domainname> Hello [10.130.33.48]
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-SIZE 20971520
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-PIPELINING
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-DSN
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-ENHANCEDSTATUSCODES
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-STARTTLS
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-X-ANONYMOUSTLS
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-AUTH NTLM
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-X-EXPS GSSAPI NTLM
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-8BITMIME
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-BINARYMIME
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-CHUNKING
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250 XRDST
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] C: STARTTLS
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 220 2.0.0 SMTP server ready
[2018-11-01 07:31:59] INFO  [w4B127kKzOs] Connection upgraded with STARTTLS
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] C: EHLO [127.0.0.1]
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-<domainname> Hello [10.130.33.48]
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-SIZE 20971520
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-PIPELINING
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-DSN
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-ENHANCEDSTATUSCODES
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-AUTH NTLM LOGIN
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-X-EXPS GSSAPI NTLM
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-8BITMIME
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-BINARYMIME
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250-CHUNKING
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 250 XRDST
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] SMTP handshake finished
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] C: AUTH LOGIN
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 334 VXNlcm5hbWU6
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] C: UUlCVUFUCWVzdHVzZXIxMDA=
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] S: 334 UGFzc3dvcmQ6
[2018-11-01 07:31:59] DEBUG [w4B127kKzOs] C: UWliMTIzNDU=
[2018-11-01 07:32:04] DEBUG [w4B127kKzOs] S: 535 5.7.3 Authentication unsuccessful
[2018-11-01 07:32:04] INFO  [w4B127kKzOs] User "testuser100" failed to authenticate
[2018-11-01 07:32:04] DEBUG [w4B127kKzOs] Closing connection to the server using "end"
[2018-11-01 07:32:04] ERROR Send Error: Invalid login: 535 5.7.3 Authentication unsuccessful
{ Error: Invalid login: 535 5.7.3 Authentication unsuccessful
    at SMTPConnection._formatError (E:\project\node_modules\nodemailer\lib\smtp-connection\index.js:606:19)
    at SMTPConnection._actionAUTHComplete (E:\project\node_modules\nodemailer\lib\smtp-connection\index.js:1335:34)
    at SMTPConnection._responseActions.push.str (E:\project\node_modules\nodemailer\lib\smtp-connection\index.js:1293:18)
    at SMTPConnection._processResponse (E:\project\node_modules\nodemailer\lib\smtp-connection\index.js:762:20)
    at SMTPConnection._onData (E:\project\node_modules\nodemailer\lib\smtp-connection\index.js:558:14)
    at TLSSocket._socket.on.chunk (E:\project\node_modules\nodemailer\lib\smtp-connection\index.js:709:51)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
  code: 'EAUTH',
  response: '535 5.7.3 Authentication unsuccessful',
  responseCode: 535,
  command: 'AUTH LOGIN' }
[2018-11-01 07:32:04] INFO  [w4B127kKzOs] Connection closed

**Comment by Alex1233456** [comment]
@thinkMX  thanks for your Response. can you please tell me, what is ' config.smtp ' and why am i not putting my email and pass in the fields 'user: config.emailUser,
pass: config.emailPass' ?  for example : user : example@compny.com and pass: 12345

**Comment by kishoreaoe** [comment]
@Alex1233456 , I am able to solved this by removing the auth: { } object. (Before that i have confirmed from my MS team and they said, for sending emails and connecting they have not configured the authentication. after that i have removed and it got connected. ) hope this may help you.!

**Comment by Alex1233456** [comment]
@kishoreaoe  it does not work with me at all. I tried every think but its always saying that the mailbox cannot be accessed at all, although its working fine when I try to access into it via online outlook. how does your code look like please? which host and port have you used? thanks in advance

**Comment by kishoreaoe** [comment]
Dearl @Alex1233456 , Please find the code which am using in my project.

var transporter = nodemailer.createTransport({
		host: 'servername.com',
		port: 25,
		debug: true,
		logger:true,
		secure: false,
	});
We are also using the same OUTLOOK, when we open in browser it do works. Check once with the guys who have setup that email for you. (confirm whether we need to authenticate or not inorder to send email.)

**Comment by Alex1233456** [comment]
@kishoreaoe i dont understand how the outlook can allow you to send email with out Username and Password after removing Auth Object? Does that work with pki card or some thing else?

**Comment by kishoreaoe** [comment]
Dear @Alex1233456 , As i said, there was some settings with MS-Exchange team (means, Is Authentication Required to access email.) They have it unchecked. After confirming this one, I have removed auth object and then it worked fine.
Please post your options .createTransport( {<options>}, we will see once.!

**Comment by Alex1233456** [comment]
this is how i am using it and this is my error. Any idea why? 
thanks @kishoreaoe 
'
var nodemailer = require('nodemailer');
var transporter = nodemailer.createTransport({
    host: 'company.com',
    proxy:"******",
    port: 587,
    debug: true,
    logger:true,
    secure: false
    });
'



2018-11-09 11:31:10] DEBUG Creating transport: nodemailer (4.6.8; +https://nodemailer.com/; SMTP/4.6.8[client:4.6.8])
[2018-11-09 11:31:10] DEBUG Sending mail using SMTP/4.6.8[client:4.6.8]
[2018-11-09 11:31:10] INFO  Using proxied socket from proxy to company.com:587
[2018-11-09 11:31:10] INFO  [Y7ffWDGDJLk] Connection established to proxy

dex.js:520:22)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) code: 'ETIMEDOUT', command: 'CONN' }
[2018-11-09 11:31:40] INFO  [Y7ffWDGDJLk] Connection closed

**Comment by Alex1233456** [comment]
issue solved locally

**Comment by Alex1233456** [comment]
@kishoreaoe thanks for the tipps. Its working for me perfectly fine. I am wondering if its possible to get user's info automatically from the post request. for example i need to get the html variable like this:

html: 'Hello i am ${request.username} i sent this email to you' this is how i need my request looks like:
'
var transporter = nodemailer.createTransport({
host: 'servername.com',
port: 25,
debug: true,
logger:true,
secure: false,
});
// i need the mail options like the following
var mailOptions = {
from: 'MYEMAIL@COMPANYNAME.com', // sender address (who sends)
to: 'MYEMAIL@COMPANYNAME.com', // list of receivers (who receives)
subject: 'this email sent from ${request.username} ', // Subject line
text: 'Hello world ', // plaintext body
html: 'this email sent from ${request.username}' 
};

// send mail with defined transport object
transporter.sendMail(mailOptions, function(error, info){
if(error){
return console.log(error);
}'

**Comment by kishoreaoe** [comment]
Dear @Alex1233456 , 
to get this we need to write one POST api method at node side and need to hit this from your application. Please find the details below:

var express = require('express')
var app = express()
var bodyParser = require('body-parser')
var rootCas = require('ssl-root-cas').create();
const https = require('https').globalAgent.options.ca = rootCas;

//Use below to avoid CORS error
app.all("/*", function(req, res, next){
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS');
  res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization, Content-Length, X-Requested-With');
  next();
});


app.post('/sendemail', function (req, res) {

var transporter = nodemailer.createTransport({
host: 'servername.com',
port: 25,
debug: true,
logger:true,
secure: false,
});

var mailOptions = {
from: 'MYEMAIL@COMPANYNAME.com', // sender address (who sends)
to: 'MYEMAIL@COMPANYNAME.com', // list of receivers (who receives)
subject: 'this email sent from ${request.username} ', // Subject line
text: 'Hello world ', // plaintext body
html: 'this email sent from'+req.userName
};

transporter.sendMail(mailOptions, function(error, info){
if(error){
return console.log(error); }
});
//Once email is sent, send the repsonse what ever you want.
res.send({"status":"SUCCESS","CODE:"200"});

app.listen(8000,'<your defined server port>', function () {
  console.log('Internal App server started on port 8000');
})

});

Hope his will help you :) .

**Comment by kishoreaoe** [comment]
typo:
useas : req.body.userName - As in the post call from the application, you will be sending a paylod, which will be inside body.

from application post method, call like below:

this.http.postService(<url>,{'userName': <dynamicvalue>});

**Comment by 5202m** [comment]
@Alex1233456 ERROR Send Error: Connection timeout
`static async emailTo(mailBody) {
        const transportOptions = {host: 'servername.com', port: 25, secure: false, logger: true, debug: false};
        const transporter = nodeMailer.createTransport(transportOptions);
        const mailOptions = {
            from: 'test@mail.com', // 发送者
            to: '123@qq.com', // 接收者，可以同时发送多个(单独发送)，以逗号隔开或使用数组
            cc: '',
            subject: mailBody.subject, // 标题
            text: 'test text',
            html: '',
        };
        try {
            const result = await transporter.sendMail(mailOptions);
            Logger.log(result);
            Logger.log('Message sent successfully!');
            return true;
        } catch (e) {
            Logger.error(e);
            return false;
        } finally {
            transporter.close();
        }
    }`
please help

**Comment by Surajp4** [comment]
@kishoreaoe  what is the host here?

**Comment by himanshupareek** [comment]
However this issue is closed. But still I wanted to give my solution:

With almost the same config settings as above, (I have chose host as "mail.myCompanyName.com"), once I connected to VPN, it started working, now I am able to send the email.

let transport = nodemailer.createTransport({
    host: "mail.myCompanyName.com",
    auth: {
      user: process.env.email,
      pass: process.env.password,
    },
  });

**Comment by himanshupareek** [comment]
This link also helped me to get confirmation on host name:

https://stackoverflow.com/a/30439954/885627
