### ISSUE TITLE
Email send is not working

### ISSUE THREAD

**Issue by bhautik11** [nodemailer/nodemailer#950]
operating system: MAC OS 10.14, 
node version: v10.10.0, 
nodemailer version: ^4.6.8

My code :
```
const smtp = nodemailer.createTransport({
      host: "smtp.sendgrid.net",
      port: 587,
      secure: false,
      auth: {
        user: "***@gmail.com",
        pass: "***"
      }
    });

mailOptions = {
        from: "****@gmail.com",
        to: "****@gmail.co",
        subject: '*****',
        text: "***",
        html: "<b>***</b>"
      };

smtp.sendMail(mailOptions, function(error, response) {
      if (error) {
        console.log(error);
      }
    });
```

I entered correct email ID and password still it's throw this error.

```
{ Error: Invalid login: 535 Authentication failed: Bad username / password
    at SMTPConnection._formatError (/Users/user/Documents/geospark-repos/geospark-website/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
    at SMTPConnection._actionAUTHComplete (/Users/user/Documents/geospark-repos/geospark-website/node_modules/nodemailer/lib/smtp-connection/index.js:1335:34)
    at SMTPConnection._responseActions.push.str (/Users/user/Documents/geospark-repos/geospark-website/node_modules/nodemailer/lib/smtp-connection/index.js:366:26)
    at SMTPConnection._processResponse (/Users/user/Documents/geospark-repos/geospark-website/node_modules/nodemailer/lib/smtp-connection/index.js:762:20)
    at SMTPConnection._onData (/Users/user/Documents/geospark-repos/geospark-website/node_modules/nodemailer/lib/smtp-connection/index.js:558:14)
    at TLSSocket._socket.on.chunk (/Users/user/Documents/geospark-repos/geospark-website/node_modules/nodemailer/lib/smtp-connection/index.js:709:51)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:219:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  code: 'EAUTH',
  response: '535 Authentication failed: Bad username / password',
  responseCode: 535,
  command: 'AUTH PLAIN' }
```

**Comment by ashishitechnotion** [comment]
which way you solve this problem

**Comment by bhautik11** [comment]
I updated nodemailer version and made syntax changes according to new version and it's works.

**Comment by AayushiGK** [comment]
@bhautik11  i have tried what u have written above but its not working for me.

**Comment by bhautik11** [comment]
Step 1:
``` 
import nodemailer from "nodemailer";

 const smtp = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: ****,
        pass: ***
      }
    });
```
Step 2:
```
      mailOptions = {
        from: ***,
        to: ***,
        subject: ****,
        text: ***
      };
```
Step 3:
```
    smtp.sendMail(mailOptions, function(error, response) {
      if (error) {
        return response.send(***);
      } 
        return response.send(****);
    });
```
