### ISSUE TITLE
 Invalid greeting from server .. 

### ISSUE THREAD

**Issue by Akinayodeji** [nodemailer/nodemailer#952]
**Here is my code... what am i doing wrong**
```
var transporter = nodemailer.createTransport({
        host: 'mail.mydomain.com',
        port: 587,
        secure: false,
        auth: {
            user: '...........',
            pass: '.....'
        },
        tls: {
            rejectUnauthorized: false
        },
        debug:true
    });
```
{ Error: Invalid greeting from server:
451 Request action aborted on MFE proxy, SMTP server is not available.: 451 Request action aborted on MFE proxy, SMTP server is not available.
    at SMTPConnection._actionGreeting (C:\SIDE_PROJECTS\Development\_Adsnad\node_modules\nodemailer\lib\smtp-connection\index.js:1019:27)
    at SMTPConnection._processResponse (C:\SIDE_PROJECTS\Development\_Adsnad\node_modules\nodemailer\lib\smtp-connection\index.js:762:20)
    at SMTPConnection._onData (C:\SIDE_PROJECTS\Development\_Adsnad\node_modules\nodemailer\lib\smtp-connection\index.js:558:14)
    at Socket._socket.on.chunk (C:\SIDE_PROJECTS\Development\_Adsnad\node_modules\nodemailer\lib\smtp-connection\index.js:510:47)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  code: 'EPROTOCOL',
  response: '451 Request action aborted on MFE proxy, SMTP server is not available.',
  responseCode: 451,
  command: 'CONN' }

**Comment by andris9** [comment]
Your SMTP server responds with "451 Request action aborted on MFE proxy, SMTP server is not available." which should mean that there is a problem with the server.
