### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by charlou28** [nodemailer/nodemailer#955]
Hello,

Since this morning, we got this error when we try to send an email : 
`{ Error: connect ETIMEDOUT 173.194.76.108:465
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNECTION',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '173.194.76.108',
  port: 465,
  command: 'CONN' }`

Can you help me ? We try different host (1und1 and gmail) none of them are working.

Thank you

**Comment by aamakerlsa** [comment]
@charlou28  same here, any progress or additional info on this issue?
