### ISSUE TITLE
Nodemailer crashing with node version 10.14.2

### ISSUE THREAD

**Issue by rujaraju** [nodemailer/nodemailer#966]
My server is crashing everytime I run it with nodemailer, the instance I try to require nodemailer, have commented out all the other code for nodemailer, just in case. The error message implies some problem with the source code, and on stackexchange I got the answer it's about the node version, but I've updated the node version to v. 10.14.2:

Debugger listening on [::]:15454
/home/ubuntu/workspace/node_modules/nodemailer/lib/mailer/index.js:31
            compile: [(...args) => this._convertDataImages(...args)],
                       ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/nodemailer/lib/nodemailer.js:3:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/app/controllers/mailHandler.server.js:4:18)
    at Module._compile (module.js:409:26)

**Comment by andris9** [comment]
This usually happens when you have 2 node versions installed. One on your user account and the other one from a native package which most probably is a very old version. Make sure you use the newer node version when running your node apps and not the old one.
