### ISSUE TITLE
smtpTransport sendMail callback argument must be a function

### ISSUE THREAD

**Issue by stoweboarder720** [nodemailer/nodemailer#971]
When creating a new smtpTransport and attempting to sendMail in the same manner that I had been using v4.x, I run into a "callback argument must be a function" error. My code for calling send mail is as follows: 
```
var smtpTransport = nodemailer.createTransport(config.mailer.options);
function (emailHTML, user, done) {
      var mailOptions = {
        to: user.email,
        from: config.mailer.from,
        subject: "Test",
        html: emailHTML
      };
      smtpTransport.sendMail(mailOptions, function (err) {
        if (!err) {
          res.send({
            message: "Test."
          });
        } else {
          return res.status(400).send({
            message: "Failure sending email"
          });
        }
        done(err);
      });
```

The stack trace is as follows: 

```
error: uncaughtException: "callback" argument must be a function date=Mon Jan 07 2019 13:37:20 GMT-0500 (Eastern Standard Time), pid=17264, uid=null, gid=null, cwd=C:\Users\me\My Documents\ GitHub\metrics\MetricsRepository, execPath=C:\Users\me\Applications\Nodejs\node-v6.10.2-win-x64\node.exe, version=v6.10.2, argv=[C:\Users\me\Applications\Nodejs\node-v6.10.2-win-x64\node.exe, C:\Users\me\My Documents\test\node_modules\gulp\bin\gulp.js, test:server], rss=306536448, heapTotal=261087232, heapUsed=164115096, external=32531432, load avg=[0, 0, 0], uptime=602134.365619
Error: "callback" argument must be a function 
  at Object.query [as resolve4] (dns.js:229:13) 
  at resolver (C:\Users\me\Documents\test\node_modules\nodemailer\lib\shared\index.js:15:28) 
  at Object.module.exports.resolveHostname(C:\Users\me\Documents\test\node_modules\nodemailer\lib\shared\index.js:55:5) 
  at SMTPConnection.connect (C:\Users\me\Documents\test\node_modules\nodemailer\lib\smtp-connection\index.js:314:27) 
  at getSocket (C:\Users\me\Documents\test\node_modules\nodemailer\lib\smtp-transport\index.js:262:24) 
  at Immediate.setImmediate (C:\Users\me\Documents\test\node_modules\nodemailer\lib\smtp-transport\index.js:70:35) 
  at runCallback (timers.js:666:20) at tryOnImmediate (timers.js:639:5) 
  at processImmediate [as _immediateCallback] (timers.js:611:5)
```

**Comment by andris9** [comment]
From a quick look it seems that you would need to upgrade Nodejs to at least 6.11.0. Current goal is to keep Nodemailer working with latest version of 6.x, so I’m not sure if and when I’ll be able to fix this to run on older versions of 6 as well

**Comment by stoweboarder720** [comment]
I can give it a shot, I'm using 6.10.2 currently.

**Comment by andris9** [comment]
Could you try upgrading to nodemailer@5.0.1 and see if it works with your Node,js version?

**Comment by stoweboarder720** [comment]
> 
> 
> Could you try upgrading to nodemailer@5.0.1 and see if it works with your Node,js version?

That fixed it, thanks! Out of curiosity, I was looking through the 5.0.1 commit, what part of that made it compatible with 6.10.x?
