### ISSUE TITLE
Send using socks 

### ISSUE THREAD

**Issue by mohilles** [nodemailer/nodemailer#975]
Hello,

how can i handle error when using proxy socks module with nodemailer

```javascript
let transporter = nodemailer.createTransport({
    host: 'smtp.example.com',
    port: '465',
    secure: true,
    proxy: 'socks5://socks-host:1234'
});
// enable support for socks URLs
transporter.set('proxy_socks_module', require('socks'));
```
The following error catch my app:
```
/Users/nodemailer/node_modules/socks/build/common/helpers.js:23
        throw new util_1.SocksClientError(constants_1.ERRORS.InvalidSocksClientOptionsDestination, options);
        ^

Error: An invalid destination host was provided.
    at Object.validateSocksClientOptions (/Users/nodemailer/node_modules/socks/build/common/helpers.js:23:15)
    at Function.createConnection (/Users/nodemailer//node_modules/socks/build/client/socksclient.js:38:19)
    at connect (/Users/nodemailer/node_modules/nodemailer/lib/mailer/index.js:359:37)
    at QueryReqWrap.dns.resolve [as callback] (/Users/nodemailer/node_modules/nodemailer/lib/mailer/index.js:377:25)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:240:10)
```

**Comment by mohilles** [comment]
Port should be a number
